OpenRDK: RDK2::Geometry::Viewport Class Reference
RDK2::Geometry::Viewport Class Reference
#include <viewport.h>
Detailed Description
Provides a viewport (??? trasformation) over a dmatrix. Storage is delegated to DMatrix without crippling that class with coordinates methods.
Note: it is *very* important that the two mappings defined by b2w and w2b be consistent.
All the w2b throws invalid_argument if the coordinates are not valid.
Definition at line 44 of file viewport.h.
Public Member Functions
Viewport (const Point2d &rmin, const Point2d &rmax) throw (std::invalid_argument)
bool isValid () const
Checks if data is valid.
double width () const
double height () const
std::string toString () throw ()
Returns a descriptive string.
const Point2d & getMin () const
const Point2d & getMax () const
bool crossesSegment (const Point2d &p0, const Point2d &p1) const
Viewport grow (double percentIncrement) const
deprecated
template<class X>
X & w2b (DMatrix< X > &m, double x, double y) const throw (std::invalid_argument)
template<class X>
const X & w2b (const DMatrix< X > &m, double x, double y) const throw (std::invalid_argument)
template<class X>
Point2d b2w (const DMatrix< X > &m, int row, int column) const
template<class X>
Viewport getCellBoundingBox (const DMatrix< X > &m, int row, int column) const
template<class X, class PointType>
X & w2b (DMatrix< X > &m, const PointType &p) const throw (std::invalid_argument)
template<class X, class PointType>
const X & w2b (const DMatrix< X > &m, const PointType &p) const throw (std::invalid_argument)
template<class PointType>
bool isInside (const PointType &p) const
template<class X>
Point2< double > getCellSize (const DMatrix< X > &m)
bool isInside (double wx, double wy) const
Utils.
template<class PointType>
bool isInside (const PointType &p) const
template<class X>
X & w2b (DMatrix< X > &m, double x, double y) const throw (std::invalid_argument)
template<class X>
const X & w2b (const DMatrix< X > &m, double x, double y) const throw (std::invalid_argument)
template<class X, class PointType>
X & w2b (DMatrix< X > &m, const PointType &p) const throw (std::invalid_argument)
template<class X, class PointType>
const X & w2b (const DMatrix< X > &m, const PointType &p) const throw (std::invalid_argument)
Point2i w2b (const Point2d &world, int columns, int rows) const throw (std::invalid_argument)
Point2i w2b_ani (const Point2d &world, int columns, int rows) const throw ()
This does not throw if point is outside buffer.
template<class X>
Point2< double > getCellSize (const DMatrix< X > &m)
Buffer to world methods.
template<class X>
Point2< double > b2w (const DMatrix< X > &m, int row, int column) const
template<class X>
Point2< double > b2w (const DMatrix< X > &m, Point2i p) const
template<class X>
Viewport getCellBoundingBox (const DMatrix< X > &m, int row, int column) const
Returns the world bounding box for cell (row=y=i,column=x=j).
template<class X>
Viewport getCellBoundingBox (const DMatrix< X > &m, Point2i p) const
Constructor & Destructor Documentation
RDK2::Geometry::Viewport::Viewport (const Point2d & rmin, const Point2d & rmax) throw (std::invalid_argument)
Definition at line 83 of file viewport.cpp.
References RDK2::TextUtils::toString().
Referenced by grow().
Member Function Documentation
bool RDK2::Geometry::Viewport::isInside (double wx, double wy) const
Utils.
Returns true if the point is inside the bounding box.
Definition at line 116 of file viewport.cpp.
References RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Referenced by crossesSegment(), and isInside().
template<class PointType> bool RDK2::Geometry::Viewport::isInside (const PointType & p) const [inline]
See also:
isInside. Allows to use a point type (x=col=j,y=row=i) for coordinates.
Definition at line 209 of file viewport.h.
bool RDK2::Geometry::Viewport::isValid () const [inline]
Checks if data is valid.
Definition at line 66 of file viewport.h.
References height(), and width().
double RDK2::Geometry::Viewport::width () const [inline]
Definition at line 68 of file viewport.h.
References RDK2::Geometry::Point2< Numeric >::x.
Referenced by getCellSize(), grow(), and isValid().
double RDK2::Geometry::Viewport::height () const [inline]
Definition at line 69 of file viewport.h.
References RDK2::Geometry::Point2< Numeric >::y.
Referenced by getCellSize(), grow(), and isValid().
std::string RDK2::Geometry::Viewport::toString () throw ()
Returns a descriptive string.
Definition at line 135 of file viewport.cpp.
References RDK2::Geometry::Point2< Numeric >::toString().
const Point2d& RDK2::Geometry::Viewport::getMin () const [inline]
Definition at line 74 of file viewport.h.
const Point2d& RDK2::Geometry::Viewport::getMax () const [inline]
Definition at line 75 of file viewport.h.
template<class X> X & RDK2::Geometry::Viewport::w2b (DMatrix< X > & m, double x, double y) const throw (std::invalid_argument) [inline]
World to buffer methods There is a little confusion with names. Get dmatrix element corresponding to world coordinates x,y.
Definition at line 159 of file viewport.h.
Referenced by w2b().
template<class X> const X & RDK2::Geometry::Viewport::w2b (const DMatrix< X > & m, double x, double y) const throw (std::invalid_argument) [inline]
Get dmatrix element corresponding to world coordinates x,y (const version).
Definition at line 170 of file viewport.h.
template<class X, class PointType> X & RDK2::Geometry::Viewport::w2b (DMatrix< X > & m, const PointType & p) const throw (std::invalid_argument) [inline]
Get dmatrix element corresponding to world coordinates p.x,p.y.
Definition at line 196 of file viewport.h.
template<class X, class PointType> const X & RDK2::Geometry::Viewport::w2b (const DMatrix< X > & m, const PointType & p) const throw (std::invalid_argument) [inline]
Get dmatrix element corresponding to world coordinates p.x,p.y (const version).
Definition at line 202 of file viewport.h.
Point2< int > RDK2::Geometry::Viewport::w2b (const Point2d & world, int columns, int rows) const throw (std::invalid_argument)
Exceptions:
invalid_argument resulting point is not inside the buffer
Definition at line 99 of file viewport.cpp.
References RDK2::Geometry::basic_w2b(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Point2< int > RDK2::Geometry::Viewport::w2b_ani (const Point2d & world, int columns, int rows) const throw ()
This does not throw if point is outside buffer.
Definition at line 107 of file viewport.cpp.
References RDK2::Geometry::basic_w2b(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
template<class X> Point2< double > RDK2::Geometry::Viewport::getCellSize (const DMatrix< X > & m) [inline]
Buffer to world methods.
Get cell size in world units
Definition at line 215 of file viewport.h.
template<class X> Point2d RDK2::Geometry::Viewport::b2w (const DMatrix< X > & m, int row, int column) const [inline]
Buffer to world (pay attention to the order of the arguments! (m[row=y][column=x]) Returns the world-coordinates of the center of the cell (row,column)
Definition at line 181 of file viewport.h.
Referenced by b2w().
template<class X> Point2<double> RDK2::Geometry::Viewport::b2w (const DMatrix< X > & m, Point2i p) const [inline]
Definition at line 131 of file viewport.h.
References b2w(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
template<class X> Viewport RDK2::Geometry::Viewport::getCellBoundingBox (const DMatrix< X > & m, int row, int column) const [inline]
Returns the world bounding box for cell (row=y=i,column=x=j).
Definition at line 189 of file viewport.h.
Referenced by getCellBoundingBox().
template<class X> Viewport RDK2::Geometry::Viewport::getCellBoundingBox (const DMatrix< X > & m, Point2i p) const [inline]
Definition at line 139 of file viewport.h.
References getCellBoundingBox(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
bool RDK2::Geometry::Viewport::crossesSegment (const Point2d & p0, const Point2d & p1) const
Check whether the segment p0-p1 crosses this rectangle. It crosses if p0 or p1 are inside, or p0-p1 crosses any of the sides.
Definition at line 25 of file viewport_cross.cpp.
References isInside(), RDK2::Geometry::sedgewickIntersect(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Viewport RDK2::Geometry::Viewport::grow (double percentIncrement) const
deprecated
Grow the bounds of the bounding box by percentIncrement. Should it return a new object?
Definition at line 122 of file viewport.cpp.
References height(), Viewport(), width(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
template<class X> X& RDK2::Geometry::Viewport::w2b (DMatrix< X > & m, double x, double y) const throw (std::invalid_argument) [inline]
Definition at line 3 of file viewport.hpp.
References RDK2::Geometry::basic_w2b().
template<class X> const X& RDK2::Geometry::Viewport::w2b (const DMatrix< X > & m, double x, double y) const throw (std::invalid_argument) [inline]
Definition at line 14 of file viewport.hpp.
References RDK2::Geometry::basic_w2b().
template<class X> Point2d RDK2::Geometry::Viewport::b2w (const DMatrix< X > & m, int row, int column) const [inline]
Definition at line 25 of file viewport.hpp.
References RDK2::Geometry::basic_b2w(), RDK2::Geometry::DMatrix< X >::columns(), and RDK2::Geometry::DMatrix< X >::rows().
template<class X> Viewport RDK2::Geometry::Viewport::getCellBoundingBox (const DMatrix< X > & m, int row, int column) const [inline]
Definition at line 33 of file viewport.hpp.
References RDK2::Geometry::basic_cellBB(), RDK2::Geometry::DMatrix< X >::columns(), and RDK2::Geometry::DMatrix< X >::rows().
template<class X, class PointType> X& RDK2::Geometry::Viewport::w2b (DMatrix< X > & m, const PointType & p) const throw (std::invalid_argument) [inline]
Definition at line 40 of file viewport.hpp.
References w2b().
template<class X, class PointType> const X& RDK2::Geometry::Viewport::w2b (const DMatrix< X > & m, const PointType & p) const throw (std::invalid_argument) [inline]
Definition at line 46 of file viewport.hpp.
References w2b().
template<class PointType> bool RDK2::Geometry::Viewport::isInside (const PointType & p) const [inline]
Definition at line 53 of file viewport.hpp.
References isInside().
template<class X> Point2<double> RDK2::Geometry::Viewport::getCellSize (const DMatrix< X > & m) [inline]
Definition at line 59 of file viewport.hpp.
References RDK2::Geometry::DMatrix< X >::columns(), height(), RDK2::Geometry::DMatrix< X >::rows(), and width().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp
viewport.hpp
viewport_cross.cpp