OpenRDK: RDK2::Meta::Factory Class Reference
RDK2::Meta::Factory Class Reference
#include <object.h>
Detailed Description
Definition at line 169 of file object.h.
Public Member Functions
Factory (const RDK2::Object *prototype)
Constructor & Destructor Documentation
RDK2::Meta::Factory::Factory (const RDK2::Object * prototype)
Definition at line 40 of file objectmanager.cpp.
References RDK2::Object::clone(), RDK2::Meta::getClass2prot(), RDK2::Demangle::Reflective::getClassName(), and RDK_ERROR_STREAM.
The documentation for this class was generated from the following files:
object.h
objectmanager.cpp