OpenRDK: RDK2::Serialization::Writer Class Reference
RDK2::Serialization::Writer Class Reference
#include <write.h>
Detailed Description
Definition at line 48 of file write.h.
Public Member Functions
virtual std::string serialize (bool withClassName, const Writable *w)=0
virtual ~Writer ()
virtual void startWriting (cstr className, unsigned char version=1)=0 throw (WritingException)
virtual void write_u8 (uint8_t, cstr name="")=0 throw (WritingException)
virtual void write_i8 (int8_t, cstr name="")=0 throw (WritingException)
virtual void write_i16 (int16_t, cstr name="")=0 throw (WritingException)
virtual void write_i32 (int32_t, cstr name="")=0 throw (WritingException)
virtual void write_f32 (float32_t, cstr name="")=0 throw (WritingException)
virtual void write_f64 (float64_t, cstr name="")=0 throw (WritingException)
virtual void write_u8 (const uint8_t *, size_t n, cstr name="")=0 throw (WritingException)
virtual void write_i8 (const int8_t *, size_t n, cstr name="")=0 throw (WritingException)
virtual void write_i16 (const int16_t *, size_t n, cstr name="")=0 throw (WritingException)
virtual void write_i32 (const int32_t *, size_t n, cstr name="")=0 throw (WritingException)
virtual void write_f32 (const float32_t *, size_t n, cstr name="")=0 throw (WritingException)
virtual void write_f64 (const float64_t *, size_t n, cstr name="")=0 throw (WritingException)
virtual void writeBytes (const void *, size_t n, cstr name="")=0 throw (WritingException)
Scrittura di buffer.
virtual void writeString (cstr s, cstr name="")=0 throw (WritingException)
virtual void writeObject (bool needClassName, const Writable *w, cstr name="")=0 throw (WritingException)
Scrittura di oggetti.
virtual void doneWriting ()=0 throw (WritingException)
Constructor & Destructor Documentation
virtual RDK2::Serialization::Writer::~Writer () [inline, virtual]
Definition at line 53 of file write.h.
Member Function Documentation
virtual std::string RDK2::Serialization::Writer::serialize (bool withClassName, const Writable * w) [pure virtual]
Serializes the object to a string.
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
Referenced by RDK2::UnitTest::Serialization::SerializationTestBad< X >::runTest(), RDK2::UnitTest::Serialization::SerializationTest2::runTest(), and RDK2::UnitTest::Serialization::SerializationTest1< X >::runTest().
virtual void RDK2::Serialization::Writer::startWriting (cstr className, unsigned char version = 1) throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_u8 (uint8_t , cstr name = "") throw (WritingException) [pure virtual]
Occhio alle conversioni automatiche quando chiamate una di queste due
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_i8 (int8_t , cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_i16 (int16_t , cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_i32 (int32_t , cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_f32 (float32_t , cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_f64 (float64_t , cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_u8 (const uint8_t * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_i8 (const int8_t * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_i16 (const int16_t * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_i32 (const int32_t * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_f32 (const float32_t * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::write_f64 (const float64_t * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::writeBytes (const void * , size_t n, cstr name = "") throw (WritingException) [pure virtual]
Scrittura di buffer.
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::writeString (cstr s, cstr name = "") throw (WritingException) [pure virtual]
stringa tranquilla:
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::writeObject (bool needClassName, const Writable * w, cstr name = "") throw (WritingException) [pure virtual]
Scrittura di oggetti.
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
virtual void RDK2::Serialization::Writer::doneWriting () throw (WritingException) [pure virtual]
Implemented in RDK2::Serialization::Binary::BinaryWriter, and RDK2::Serialization::Xml::XmlWriter.
The documentation for this class was generated from the following file:
write.h