OpenRDK: Network::NetException Class Reference
Network::NetException Class Reference
#include <netexception.h>
Detailed Description
Definition at line 28 of file netexception.h.
Public Member Functions
NetException (const std::string &what) throw ()
virtual ~NetException () throw ()
virtual const char * what () const throw ()
Return user specified cause.
virtual int geterrno () const throw ()
Return errno when the exception whas launched.
virtual std::string fullwhat () const throw ()
Return specified cause + errno.
Protected Member Functions
NetException () throw ()
Constructor & Destructor Documentation
Network::NetException::NetException (const std::string & what) throw ()
Definition at line 28 of file netexception.cpp.
Network::NetException::~NetException () throw () [virtual]
Definition at line 31 of file netexception.cpp.
Network::NetException::NetException () throw () [protected]
Definition at line 51 of file netexception.cpp.
Member Function Documentation
const char * Network::NetException::what () const throw () [virtual]
Return user specified cause.
Definition at line 33 of file netexception.cpp.
int Network::NetException::geterrno () const throw () [virtual]
Return errno when the exception whas launched.
Definition at line 37 of file netexception.cpp.
std::string Network::NetException::fullwhat () const throw () [virtual]
Return specified cause + errno.
Definition at line 41 of file netexception.cpp.
Referenced by RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), RDK2::RNetObjects::RYellowPages::loadFromFile(), main(), receiver(), and sender().
The documentation for this class was generated from the following files:
netexception.h
netexception.cpp