OpenRDK: RDK2::Geometry::LineWalk Class Reference
RDK2::Geometry::LineWalk Class Reference
#include <walk_line.h>
Detailed Description
Definition at line 45 of file walk_line.h.
Public Member Functions
LineWalk (Point2i p0, Point2i p1)
bool next ()
void rewind ()
Point2i getPoint () const
Data Fields
int vx
int vy
double dx
double dy
Point2i p0
Point2i p1
unsigned int steps
unsigned int currentStep
Constructor & Destructor Documentation
RDK2::Geometry::LineWalk::LineWalk (Point2i p0, Point2i p1)
Definition at line 25 of file walk_line.cpp.
References currentStep, dx, dy, steps, vx, vy, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Member Function Documentation
bool RDK2::Geometry::LineWalk::next ()
Definition at line 50 of file walk_line.cpp.
References currentStep, and steps.
Referenced by RDK2::RMaps::RMapImage::distMapRayTracing(), RDK2::Geometry::QuadWalk::next(), RDK2::RMaps::RMapImage::obsDenRayTracing(), and RDK2::RMaps::RMapImage::rayTracing().
void RDK2::Geometry::LineWalk::rewind ()
Definition at line 58 of file walk_line.cpp.
References currentStep.
Referenced by RDK2::Geometry::QuadWalk::rewind().
Point2i RDK2::Geometry::LineWalk::getPoint () const
Definition at line 63 of file walk_line.cpp.
References currentStep, dx, dy, p0, vx, vy, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Referenced by RDK2::RMaps::RMapImage::distMapRayTracing(), RDK2::Geometry::QuadWalk::getPoint(), RDK2::RMaps::RMapImage::obsDenRayTracing(), and RDK2::RMaps::RMapImage::rayTracing().
Field Documentation
int RDK2::Geometry::LineWalk::vx
Definition at line 57 of file walk_line.h.
Referenced by getPoint(), and LineWalk().
int RDK2::Geometry::LineWalk::vy
Definition at line 57 of file walk_line.h.
Referenced by getPoint(), and LineWalk().
double RDK2::Geometry::LineWalk::dx
Definition at line 58 of file walk_line.h.
Referenced by getPoint(), and LineWalk().
double RDK2::Geometry::LineWalk::dy
Definition at line 58 of file walk_line.h.
Referenced by getPoint(), and LineWalk().
Point2i RDK2::Geometry::LineWalk::p0
Definition at line 59 of file walk_line.h.
Referenced by getPoint().
Point2i RDK2::Geometry::LineWalk::p1
Definition at line 59 of file walk_line.h.
unsigned int RDK2::Geometry::LineWalk::steps
Definition at line 60 of file walk_line.h.
Referenced by LineWalk(), and next().
unsigned int RDK2::Geometry::LineWalk::currentStep
Definition at line 61 of file walk_line.h.
Referenced by getPoint(), LineWalk(), next(), and rewind().
The documentation for this class was generated from the following files:
walk_line.h
walk_line.cpp