OpenRDK: RDK2::RPrimitive::RString Class Reference
RDK2::RPrimitive::RString Class Reference
#include <rstring.h>
Detailed Description
Definition at line 32 of file rstring.h.
Public Member Functions
RString (std::string text="")
bool hasStringRepresentation () const
Ritorna true se ha una rappresentazione "semplice" come stringa.
std::string getStringRepresentation () const
Ritorna la rappresentazione come stringa.
bool loadFromStringRepresentation (const std::string &)
Inversa della precedente.
bool hasStringForVisualization () const
Returns true if this object has a string that can be visualized.
void read (RDK2::Reader *r) throw (RDK2::ReadingException)
void write (RDK2::Writer *w) const throw (RDK2::WritingException)
Object * clone () const
operator const std::string & () const
std::vector< Object * > getTestCases () const
Get a vector of test cases.
bool equals (const Object *) const
Data Fields
std::string value
Constructor & Destructor Documentation
RDK2::RPrimitive::RString::RString (std::string text = "")
Definition at line 30 of file rstring.cpp.
Referenced by clone(), and getTestCases().
Member Function Documentation
bool RDK2::RPrimitive::RString::hasStringRepresentation () const [virtual]
Ritorna true se ha una rappresentazione "semplice" come stringa.
Reimplemented from RDK2::Object.
Definition at line 37 of file rstring.cpp.
std::string RDK2::RPrimitive::RString::getStringRepresentation () const [virtual]
Ritorna la rappresentazione come stringa.
Reimplemented from RDK2::Object.
Definition at line 41 of file rstring.cpp.
References value.
bool RDK2::RPrimitive::RString::loadFromStringRepresentation (const std::string &) [virtual]
Inversa della precedente.
Reimplemented from RDK2::Object.
Definition at line 45 of file rstring.cpp.
References value.
bool RDK2::RPrimitive::RString::hasStringForVisualization () const [inline, virtual]
Returns true if this object has a string that can be visualized.
Reimplemented from RDK2::Object.
Definition at line 39 of file rstring.h.
void RDK2::RPrimitive::RString::read (RDK2::Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 50 of file rstring.cpp.
References RDK2::Demangle::Reflective::getClassName(), RDK2::Statistics::r, and value.
void RDK2::RPrimitive::RString::write (RDK2::Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 56 of file rstring.cpp.
References RDK2::Demangle::Reflective::getClassName(), and value.
Object * RDK2::RPrimitive::RString::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 33 of file rstring.cpp.
References RString(), and value.
RDK2::RPrimitive::RString::operator const std::string & () const [inline]
Definition at line 45 of file rstring.h.
References value.
std::vector< Object * > RDK2::RPrimitive::RString::getTestCases () const [virtual]
Get a vector of test cases.
Reimplemented from RDK2::Object.
Definition at line 62 of file rstring.cpp.
References RString().
bool RDK2::RPrimitive::RString::equals (const Object *) const [virtual]
Compare this and another object.
Note:
For clarity, we decided not to use operator=.
Returns:
true if they are equivalent
Reimplemented from RDK2::Object.
Definition at line 71 of file rstring.cpp.
References value.
Field Documentation
std::string RDK2::RPrimitive::RString::value
Definition at line 51 of file rstring.h.
Referenced by clone(), equals(), getStringRepresentation(), loadFromStringRepresentation(), operator const std::string &(), read(), write(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::write().
The documentation for this class was generated from the following files:
rstring.h
rstring.cpp