OpenRDK: RDK2::Containers::Vector< RType > Class Template Reference
RDK2::Containers::Vector< RType > Class Template Reference
#include <container.h>
Detailed Description
template<class RType>
class RDK2::Containers::Vector< RType >
Il vero container e' un membro: e' piu' facile fare tutto in modo corretto. FIXME DC: che vuol dire membro? membro di che?
Gli oggetti dentro devono implementare anche clone().
Definition at line 82 of file container.h.
Public Types
typedef std::vector< RType * >
::iterator iterator
typedef std::vector< RType * >
::const_iterator const_iterator
Public Member Functions
Vector ()
Vector & operator= (const Vector< RType > &c2)
template<class R2>
Vector & copy (const Vector< R2 > &c2)
template<class R2>
Vector & append (const Vector< R2 > &c2)
RDK2::Object * clone () const
Vector (const Vector< RType > &c2)
virtual ~Vector ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
void resize (size_t n)
void reserve (size_t n)
RType * operator[] (uint i) const
RType * getItem (uint i) const
template<typename T>
T * getItemAs (uint i) const
string getClassName () const
void push_back (RType *t)
iterator erase (iterator it, bool alsoDelete)
void clear (bool alsoDelete)
void clear ()
virtual void read (Reader *r) throw (ReadingException)
bool sameClass (string &cl) const
bool supportedSpecial (cstr s) const
virtual void write (Writer *w) const throw (WritingException)
virtual bool knowsDiffs ()
virtual vector
< RDK2::Meta::ObjectDiff * > split (size_t)
virtual bool applyDiff (const RDK2::Meta::ObjectDiff *od)
virtual vector
< RDK2::Meta::ObjectDiff * > splitInDiffs (size_t)
Data Fields
string objsClassName
std::vector< RType * > c
Protected Attributes
uint remoteIdx
Member Typedef Documentation
template<class RType> typedef std::vector<RType*>::iterator RDK2::Containers::Vector< RType >::iterator
Definition at line 136 of file container.h.
template<class RType> typedef std::vector<RType*>::const_iterator RDK2::Containers::Vector< RType >::const_iterator
Definition at line 137 of file container.h.
Constructor & Destructor Documentation
template<class RType> RDK2::Containers::Vector< RType >::Vector () [inline]
Definition at line 94 of file container.h.
template<class RType> RDK2::Containers::Vector< RType >::Vector (const Vector< RType > & c2) [inline]
Definition at line 126 of file container.h.
template<class RType> virtual RDK2::Containers::Vector< RType >::~Vector () [inline, virtual]
Definition at line 132 of file container.h.
Member Function Documentation
template<class RType> Vector& RDK2::Containers::Vector< RType >::operator= (const Vector< RType > & c2) [inline]
Definition at line 96 of file container.h.
template<class RType> template<class R2> Vector& RDK2::Containers::Vector< RType >::copy (const Vector< R2 > & c2) [inline]
Definition at line 101 of file container.h.
Referenced by main().
template<class RType> template<class R2> Vector& RDK2::Containers::Vector< RType >::append (const Vector< R2 > & c2) [inline]
Definition at line 107 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::copy().
template<class RType> RDK2::Object* RDK2::Containers::Vector< RType >::clone () const [inline, virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 122 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::append(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::applyDiff(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::splitInDiffs().
template<class RType> iterator RDK2::Containers::Vector< RType >::begin () [inline]
Definition at line 139 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::append(), RDK2::RAgent::Module::createModuleConfig(), RDK2::RAgent::Module::initWithModuleConfig(), RDK2::RAgent::ModuleManager::instantiateModules(), and main().
template<class RType> const_iterator RDK2::Containers::Vector< RType >::begin () const [inline]
Definition at line 140 of file container.h.
template<class RType> iterator RDK2::Containers::Vector< RType >::end () [inline]
Definition at line 141 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::append(), RDK2::RAgent::Module::createModuleConfig(), RDK2::RAgent::Module::initWithModuleConfig(), RDK2::RAgent::ModuleManager::instantiateModules(), and main().
template<class RType> const_iterator RDK2::Containers::Vector< RType >::end () const [inline]
Definition at line 142 of file container.h.
template<class RType> size_t RDK2::Containers::Vector< RType >::size () const [inline]
Definition at line 144 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::applyDiff(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::read().
template<class RType> void RDK2::Containers::Vector< RType >::resize (size_t n) [inline]
Definition at line 146 of file container.h.
template<class RType> void RDK2::Containers::Vector< RType >::reserve (size_t n) [inline]
Definition at line 148 of file container.h.
template<class RType> RType* RDK2::Containers::Vector< RType >::operator[] (uint i) const [inline]
Definition at line 150 of file container.h.
template<class RType> RType* RDK2::Containers::Vector< RType >::getItem (uint i) const [inline]
Definition at line 151 of file container.h.
template<class RType> template<typename T> T* RDK2::Containers::Vector< RType >::getItemAs (uint i) const [inline]
Definition at line 154 of file container.h.
template<class RType> string RDK2::Containers::Vector< RType >::getClassName () const [inline, virtual]
Reimplemented from RDK2::Demangle::Reflective.
Definition at line 156 of file container.h.
Referenced by RDK2::RepositoryNS::Session::createVector(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::read(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::sameClass(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::write().
template<class RType> void RDK2::Containers::Vector< RType >::push_back (RType * t) [inline]
Definition at line 158 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::append(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::applyDiff(), RDK2::RAgent::Module::createModuleConfig(), RDK2::RAgent::ModuleManager::getModuleConfigs(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::splitInDiffs().
template<class RType> iterator RDK2::Containers::Vector< RType >::erase (iterator it, bool alsoDelete) [inline]
Definition at line 160 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::clear().
template<class RType> void RDK2::Containers::Vector< RType >::clear (bool alsoDelete) [inline]
Definition at line 167 of file container.h.
template<class RType> void RDK2::Containers::Vector< RType >::clear () [inline]
Definition at line 173 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::applyDiff(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::copy(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::~Vector().
template<class RType> virtual void RDK2::Containers::Vector< RType >::read (Reader * r) throw (ReadingException) [inline, virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 181 of file container.h.
template<class RType> bool RDK2::Containers::Vector< RType >::sameClass (string & cl) const [inline]
Definition at line 221 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::write().
template<class RType> bool RDK2::Containers::Vector< RType >::supportedSpecial (cstr s) const [inline]
Definition at line 232 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::read(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::write().
template<class RType> virtual void RDK2::Containers::Vector< RType >::write (Writer *) const throw (WritingException) [inline, virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 237 of file container.h.
template<class RType> virtual bool RDK2::Containers::Vector< RType >::knowsDiffs () [inline, virtual]
Reimplemented from RDK2::Object.
Definition at line 265 of file container.h.
template<class RType> virtual vector<RDK2::Meta::ObjectDiff*> RDK2::Containers::Vector< RType >::split (size_t) [inline, virtual]
Implements RDK2::Meta::ObjectDiff.
Definition at line 269 of file container.h.
template<class RType> virtual bool RDK2::Containers::Vector< RType >::applyDiff (const RDK2::Meta::ObjectDiff * od) [inline, virtual]
Reimplemented from RDK2::Object.
Definition at line 272 of file container.h.
template<class RType> virtual vector<RDK2::Meta::ObjectDiff*> RDK2::Containers::Vector< RType >::splitInDiffs (size_t) [inline, virtual]
Reimplemented from RDK2::Object.
Definition at line 290 of file container.h.
Field Documentation
template<class RType> uint RDK2::Containers::Vector< RType >::remoteIdx [protected]
Definition at line 85 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::applyDiff(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::read(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::splitInDiffs(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::write().
template<class RType> string RDK2::Containers::Vector< RType >::objsClassName
Definition at line 88 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::append(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::getClassName(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::Vector().
template<class RType> std::vector<RType*> RDK2::Containers::Vector< RType >::c
Definition at line 92 of file container.h.
Referenced by RDK2::Containers::Vector< RDK2::RAgent::Pair >::begin(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::clear(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::end(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::erase(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::getItem(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::getItemAs(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::operator[](), RDK2::Containers::Vector< RDK2::RAgent::Pair >::push_back(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::read(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::reserve(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::resize(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::sameClass(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::size(), RDK2::Containers::Vector< RDK2::RAgent::Pair >::splitInDiffs(), and RDK2::Containers::Vector< RDK2::RAgent::Pair >::write().
The documentation for this class was generated from the following file:
container.h