OpenRDK: Network::UDPSocket Class Reference
Network::UDPSocket Class Reference
#include <udpsocket.h>
Detailed Description
Definition at line 30 of file udpsocket.h.
Public Types
enum ShutdownType { READ = SHUT_RD, WRITE = SHUT_WR, ALL = SHUT_RDWR }
Public Member Functions
UDPSocket () throw ()
UDPSocket (unsigned short port) throw (UDPException, NetException)
UDPSocket (const InetAddress &address) throw (UDPException)
~UDPSocket ()
bool isBound () throw ()
bool shutdown (ShutdownType how)
void unbind () throw ()
void rebind () throw (UDPException)
void bind (unsigned short port) throw (UDPException, NetException)
void bind (const InetAddress &address) throw (UDPException)
void newBuffer (unsigned short buffersize) throw ()
int getRealAddress (InetAddress &addr) throw ()
InetAddress getAddress ()
int getSocket () const
unsigned short send (const std::string &data, const InetAddress &address) throw (UDPException)
unsigned short recv (std::string &data, InetAddress &address, double timeoutSecs=0.0) throw (UDPException)
unsigned short recv (std::string &data) throw (UDPException)
Protected Attributes
unsigned short buffersize
InetAddress address
int socket
char * buffer
Member Enumeration Documentation
enum Network::UDPSocket::ShutdownType
Enumerator:
READ
WRITE
ALL
Definition at line 43 of file udpsocket.h.
Constructor & Destructor Documentation
Network::UDPSocket::UDPSocket () throw ()
Definition at line 54 of file udpsocket.cpp.
References buffer, DOUT, and rebind().
Network::UDPSocket::UDPSocket (unsigned short port) throw (UDPException, NetException)
Definition at line 64 of file udpsocket.cpp.
References DOUT, and UDP_SOCKET_DEFAULT_BUFFER_SIZE.
Network::UDPSocket::UDPSocket (const InetAddress & address) throw (UDPException)
Definition at line 75 of file udpsocket.cpp.
References DOUT, and UDP_SOCKET_DEFAULT_BUFFER_SIZE.
Network::UDPSocket::~UDPSocket ()
Definition at line 86 of file udpsocket.cpp.
References ALL, buffer, shutdown(), and socket.
Member Function Documentation
bool Network::UDPSocket::isBound () throw ()
Definition at line 94 of file udpsocket.cpp.
References socket.
bool Network::UDPSocket::shutdown (ShutdownType how)
Definition at line 236 of file udpsocket.cpp.
References socket.
Referenced by rebind(), unbind(), RDK2::RepositoryNS::UdpManager::~UdpManager(), and ~UDPSocket().
void Network::UDPSocket::unbind () throw ()
Definition at line 98 of file udpsocket.cpp.
References ALL, shutdown(), and socket.
Referenced by bind(), and rebind().
void Network::UDPSocket::rebind () throw (UDPException)
Definition at line 106 of file udpsocket.cpp.
References address, ALL, bind(), DOUT, Network::InetAddress::getAddress(), Network::InetAddress::getIPAddress(), Network::InetAddress::getPort(), shutdown(), socket, and unbind().
Referenced by bind(), and UDPSocket().
void Network::UDPSocket::bind (unsigned short port) throw (UDPException, NetException)
Definition at line 134 of file udpsocket.cpp.
References address, rebind(), and unbind().
Referenced by RDK2::RepositoryNS::UdpManager::init(), and rebind().
void Network::UDPSocket::bind (const InetAddress & address) throw (UDPException)
Definition at line 140 of file udpsocket.cpp.
References address, rebind(), and unbind().
void Network::UDPSocket::newBuffer (unsigned short buffersize) throw ()
Definition at line 146 of file udpsocket.cpp.
References buffer, and buffersize.
int Network::UDPSocket::getRealAddress (InetAddress & addr) throw () [inline]
Definition at line 61 of file udpsocket.h.
References socket.
InetAddress Network::UDPSocket::getAddress () [inline]
Definition at line 66 of file udpsocket.h.
int Network::UDPSocket::getSocket () const [inline]
Definition at line 68 of file udpsocket.h.
References socket.
unsigned short Network::UDPSocket::send (const std::string & data, const InetAddress & address) throw (UDPException)
Definition at line 152 of file udpsocket.cpp.
References address, buffersize, DOUT, Network::InetAddress::getAddress(), Network::InetAddress::getIPAddress(), Network::InetAddress::getPort(), and socket.
Referenced by main().
unsigned short Network::UDPSocket::recv (std::string & data, InetAddress & address, double timeoutSecs = 0.0) throw (UDPException)
Definition at line 182 of file udpsocket.cpp.
References address, buffer, buffersize, Network::InetAddress::getAddress(), Network::InetAddress::getIPAddress(), Network::InetAddress::getPort(), IPERDOUT, RECVDOUT, and socket.
Referenced by main(), and recv().
unsigned short Network::UDPSocket::recv (std::string & data) throw (UDPException) [inline]
Definition at line 77 of file udpsocket.h.
References recv().
Field Documentation
unsigned short Network::UDPSocket::buffersize [protected]
Definition at line 79 of file udpsocket.h.
Referenced by newBuffer(), recv(), and send().
InetAddress Network::UDPSocket::address [protected]
Definition at line 80 of file udpsocket.h.
Referenced by bind(), rebind(), recv(), and send().
int Network::UDPSocket::socket [protected]
Definition at line 81 of file udpsocket.h.
Referenced by getRealAddress(), getSocket(), isBound(), rebind(), recv(), send(), shutdown(), unbind(), and ~UDPSocket().
char* Network::UDPSocket::buffer [protected]
Definition at line 82 of file udpsocket.h.
Referenced by newBuffer(), recv(), UDPSocket(), and ~UDPSocket().
The documentation for this class was generated from the following files:
udpsocket.h
udpsocket.cpp