OpenRDK: RDK2::Serialization::Xml::XmlWriter Class Reference
RDK2::Serialization::Xml::XmlWriter Class Reference
#include <xmlwriter.h>
Detailed Description
An xml writer
Definition at line 44 of file xmlwriter.h.
Public Member Functions
XmlWriter (bool indent)
virtual ~XmlWriter ()
std::string serialize (bool withClassName, const Writable *w)
void startWriting (cstr myClassName, unsigned char version=1) throw (WritingException)
void write_u8 (uint8_t, cstr name) throw (WritingException)
void write_i8 (int8_t, cstr name) throw (WritingException)
void write_i16 (int16_t, cstr name) throw (WritingException)
void write_i32 (int32_t, cstr name) throw (WritingException)
void write_f32 (float32_t, cstr name) throw (WritingException)
void write_f64 (float64_t, cstr name) throw (WritingException)
void write_u8 (const uint8_t *, size_t n, cstr name) throw (WritingException)
void write_i8 (const int8_t *, size_t n, cstr name) throw (WritingException)
void write_i16 (const int16_t *, size_t n, cstr name) throw (WritingException)
void write_i32 (const int32_t *, size_t n, cstr name) throw (WritingException)
void write_f32 (const float32_t *, size_t n, cstr name) throw (WritingException)
void write_f64 (const float64_t *, size_t n, cstr name) throw (WritingException)
void writeBytes (const void *i, size_t n, cstr name) throw (WritingException)
Scrittura di buffer.
void writeString (cstr s, cstr name) throw (WritingException)
void writeObject (bool needClassName, const Writable *w, cstr name="") throw (WritingException)
Scrittura di oggetti.
void doneWriting () throw (WritingException)
Constructor & Destructor Documentation
RDK2::Serialization::Xml::XmlWriter::XmlWriter (bool indent) [inline]
Public interface
Definition at line 50 of file xmlwriter.h.
virtual RDK2::Serialization::Xml::XmlWriter::~XmlWriter () [inline, virtual]
Definition at line 51 of file xmlwriter.h.
Member Function Documentation
string RDK2::Serialization::Xml::XmlWriter::serialize (bool withClassName, const Writable * w) [virtual]
Serializes the object to a string.
Implements RDK2::Serialization::Writer.
Definition at line 28 of file xmlwriter.cpp.
References RDK2::Statistics::r, writeObject(), XML_CHECK_ERROR, XML_ENCODING, and XML_INDENTATION_STRING.
Referenced by main().
void RDK2::Serialization::Xml::XmlWriter::startWriting (cstr myClassName, unsigned char version = 1) throw (WritingException) [virtual]
Writer interface
Implements RDK2::Serialization::Writer.
Definition at line 59 of file xmlwriter.cpp.
References XML_NAMESPACE_PREFIX, XML_NAMESPACE_URI, and XML_NAMESPACE_URI_ROOT.
void RDK2::Serialization::Xml::XmlWriter::write_u8 (uint8_t , cstr name) throw (WritingException) [virtual]
Occhio alle conversioni automatiche quando chiamate una di queste due
Implements RDK2::Serialization::Writer.
Definition at line 70 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_i8 (int8_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 77 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_i16 (int16_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 84 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_i32 (int32_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 91 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_f32 (float32_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 98 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_FLOATING_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_f64 (float64_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 105 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_FLOATING_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_u8 (const uint8_t * v, size_t n, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 135 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_i8 (const int8_t * v, size_t n, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 123 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_i16 (const int16_t * v, size_t n, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 147 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_i32 (const int32_t * v, size_t n, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 159 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_INTEGER_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_f32 (const float32_t * v, size_t n, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 171 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_FLOATING_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::write_f64 (const float64_t * v, size_t n, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 183 of file xmlwriter.cpp.
References RDK2::Serialization::Xml::vtos(), and XML_FLOATING_VALUE_PRINTF_FORMAT.
void RDK2::Serialization::Xml::XmlWriter::writeBytes (const void * , size_t n, cstr name) throw (WritingException) [virtual]
Scrittura di buffer.
Implements RDK2::Serialization::Writer.
Definition at line 112 of file xmlwriter.cpp.
References encode64().
void RDK2::Serialization::Xml::XmlWriter::writeString (cstr s, cstr name) throw (WritingException) [virtual]
stringa tranquilla:
Implements RDK2::Serialization::Writer.
Definition at line 195 of file xmlwriter.cpp.
References xmlEncode().
void RDK2::Serialization::Xml::XmlWriter::writeObject (bool needClassName, const Writable * w, cstr name = "") throw (WritingException) [virtual]
Scrittura di oggetti.
Implements RDK2::Serialization::Writer.
Definition at line 206 of file xmlwriter.cpp.
Referenced by serialize().
void RDK2::Serialization::Xml::XmlWriter::doneWriting () throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 212 of file xmlwriter.cpp.
The documentation for this class was generated from the following files:
xmlwriter.h
xmlwriter.cpp