OpenRDK: Network::InetAddress Class Reference
Network::InetAddress Class Reference
#include <inetaddress.h>
Detailed Description
Definition at line 31 of file inetaddress.h.
Public Member Functions
InetAddress () throw ()
Create a non usefull address (all 0).
InetAddress (unsigned short port) throw ()
Create an address perfect for internet receiving on port.
InetAddress (const std::string &address, unsigned short port) throw (NetException)
Create a complete address.
InetAddress (const struct sockaddr_in &address) throw ()
Create an address from a struct sockaddr_in.
InetAddress (const SocketAddress &address) throw (NetException)
const std::string & getCreationAddress () const throw ()
Get the address used for generate the ip real address.
std::string getIPAddress () const throw ()
Get the ip address in dot notation.
unsigned short getPort () const throw ()
Get the port.
short getFamily () const throw ()
Get the family of the address.
struct sockaddr_in & getAddress () const throw ()
Get the struct sockaddr_in (const version).
struct sockaddr_in & getAddress () throw ()
Get the struct sockaddr_in.
void setAddress (const std::string &address) throw (NetException)
Set a new address.
void setPort (unsigned short port) throw ()
Set a new port.
void setAddress (const struct sockaddr_in &address) throw ()
Set a new address from a struct sockaddr_in.
bool operator< (const InetAddress &) const
Constructor & Destructor Documentation
Network::InetAddress::InetAddress () throw ()
Create a non usefull address (all 0).
Definition at line 37 of file inetaddress.cpp.
References Network::SocketAddress::address.
Network::InetAddress::InetAddress (unsigned short port) throw ()
Create an address perfect for internet receiving on port.
Definition at line 44 of file inetaddress.cpp.
References Network::SocketAddress::address.
Network::InetAddress::InetAddress (const std::string & address, unsigned short port) throw (NetException)
Create a complete address.
Definition at line 51 of file inetaddress.cpp.
References Network::SocketAddress::address, and setAddress().
Network::InetAddress::InetAddress (const struct sockaddr_in & address) throw () [inline]
Create an address from a struct sockaddr_in.
Definition at line 44 of file inetaddress.h.
Network::InetAddress::InetAddress (const SocketAddress & address) throw (NetException)
Definition at line 59 of file inetaddress.cpp.
References Network::SocketAddress::address.
Member Function Documentation
const std::string& Network::InetAddress::getCreationAddress () const throw () [inline]
Get the address used for generate the ip real address.
Definition at line 51 of file inetaddress.h.
std::string Network::InetAddress::getIPAddress () const throw () [inline]
Get the ip address in dot notation.
Definition at line 54 of file inetaddress.h.
Referenced by main(), Network::UDPSocket::rebind(), Network::UDPSocket::recv(), Network::UDPSocket::send(), and Network::TCPSocket::underflow().
unsigned short Network::InetAddress::getPort () const throw () [inline]
Get the port.
Definition at line 57 of file inetaddress.h.
Referenced by RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), main(), Network::UDPSocket::rebind(), Network::UDPSocket::recv(), and Network::UDPSocket::send().
short Network::InetAddress::getFamily () const throw () [inline]
Get the family of the address.
Reimplemented from Network::SocketAddress.
Definition at line 60 of file inetaddress.h.
struct sockaddr_in& Network::InetAddress::getAddress () const throw () [inline, read]
Get the struct sockaddr_in (const version).
Reimplemented from Network::SocketAddress.
Definition at line 63 of file inetaddress.h.
Referenced by Network::TCPServerSocket::accept(), Network::UDPSocket::rebind(), Network::UDPSocket::recv(), and Network::UDPSocket::send().
struct sockaddr_in& Network::InetAddress::getAddress () throw () [inline, read]
Get the struct sockaddr_in.
Reimplemented from Network::SocketAddress.
Definition at line 66 of file inetaddress.h.
void Network::InetAddress::setAddress (const std::string & address) throw (NetException)
Set a new address.
Definition at line 67 of file inetaddress.cpp.
References Network::SocketAddress::address, DEBUG_STREAM, and h_errno.
Referenced by InetAddress().
void Network::InetAddress::setPort (unsigned short port) throw () [inline]
Set a new port.
Definition at line 74 of file inetaddress.h.
Referenced by main().
void Network::InetAddress::setAddress (const struct sockaddr_in & address) throw () [inline]
Set a new address from a struct sockaddr_in.
Definition at line 77 of file inetaddress.h.
bool Network::InetAddress::operator< (const InetAddress & addr) const
Definition at line 89 of file inetaddress.cpp.
References Network::SocketAddress::address.
The documentation for this class was generated from the following files:
inetaddress.h
inetaddress.cpp