OpenRDK: RDK2::RepositoryNS::Repository Class Reference
RDK2::RepositoryNS::Repository Class Reference
#include <repository.h>
Detailed Description
Definition at line 66 of file repository.h.
Queue push
string repositoryName
PosixConstructs::PosixMutex propertiesMutex
Repository properties.
map< Url, Property * > localProperties
map< Url, Property * > remoteProperties
PosixConstructs::PosixMutex sessionsListeningToTreeMutex
Sessions listening to tree changes.
multimap< string, Session * > sessionsListeningToTree
volatile bool exitTimerThread
PosixConstructs::PosixMutex sessionsListeningToTimerMutex
map< Session *, SessionTimer > sessionsListeningToTimer
pthread_t timerThreadId
bool timerThreadStarted
UdpManager * udpManager
Comunication threads.
TcpManager * tcpManager
RemotePropertyManager * remotePropertyManager
RemoteSubscriptionRegister remoteSubscriptionRegister
bool queuePush (CUrl Curl, RDK2::Object *object) throw (NoSuchProperty, InvalidOperation)
void saveAllDefaultPropertyDefs ()
void timerThread ()
void remotePropertyOptions (CUrl url, Network::NetProtocol socketType=Network::TCP_IP, RRemoteSubscription::What what=RRemoteSubscription::STORAGE_DIFFS, RRemoteSubscription::When when=RRemoteSubscription::PERIODIC, double minPeriod=50., double maxPeriod=500.) throw (NoSuchProperty, InvalidOperation)
static void * timerThreadExec (Repository *repository)
Remote stuff utilities
class Session
class RemotePropertyManager
class TcpManager
class RemoteSubscriptionRegister
void sendStorageValueToHost (CUrl completeUrl, cstr askingHost, Network::NetProtocol socketType, RDK2::Object *objToSend=0) throw ()
void sendStorageValuesToRemoteValueSubscribers (CUrl completeUrl, cstr askingHost, Network::NetProtocol socketType, RRemoteSubscription::What what, RRemoteSubscription::When when) throw ()
void sendStorageDiffToHost (CUrl completeUrl, cstr askingHost, Network::NetProtocol socketType, ObjectDiff *diffToSend) throw ()
void sendObjectsToRemoteQueueSubscribers (CUrl completeUrl, const RDK2::Object *objToSend) throw ()
void setRemotePropertyDef (CUrl url, const RPropertyDef *def)
Public Member Functions
Repository (cstr repositoryName)
virtual ~Repository ()
Destructor.
string getRepositoryName ()
Each repository has a unique name, i.e. the one used in the constructor.
Url getBaseUrl ()
Globally, each property of this repository begins with its base url, i.e. "rdk://" + repositoryName.
Session * createSession (cstr name, cstr descName, cstr urlContext)
bool loadYellowPages (cstr ypFilename)
void startRepositoryThreads ()
Starts the comunication threads (UDP, TCP, and Remote property manager).
void endRepositoryThreads ()
map< Url, string > getLocalPropertyNames ()
map< Url, string > getRemotePropertyNames (cstr host)
vector< Url > getLocalPropertiesStartingWith (string prefix)
Utilities
void setPropertyValueFromTextConfig (cstr key, cstr val, CUrl urlContext, Session *session) throw (NoSuchProperty, InvalidOperation)
Protected Member Functions
Property * getProperty (CUrl url) throw (NoSuchProperty, InvalidOperation)
Property * getProperty (CUrl url, Session *) throw (NoSuchProperty)
Property * getLocalProperty (CUrl url) throw (NoSuchProperty)
Property * getRemoteProperty (CUrl url, Session *askingSession) throw ()
bool isLocalProperty (CUrl) throw ()
void addGenericProperty (cstr className, CUrl url, cstr description, RDK2::Object *defaultObject=0) throw (InvalidOperation)
void deleteProperty (CUrl url) throw (NoSuchProperty, InvalidOperation)
Storage locking
void lock (CUrl url, Stack w) throw (NoSuchProperty, InvalidOperation)
void unlock (CUrl url) throw (NoSuchProperty, InvalidOperation)
Storage creation
Create a storage property.
Parameters:
url *absolute* url of the property, i.e. starting with "/" and WITHOUT host name
void createStorage (cstr className, CUrl url, cstr description, RDK2::Object *defaultObject=0) throw (InvalidOperation)
Storage value
const RDK2::Object * getObjectLC (CUrl url) throw (NoSuchProperty)
RDK2::Object * getObjectL (CUrl url) throw (NoSuchProperty)
template<typename T>
const T * getObjectAsLC (CUrl url) throw (NoSuchProperty, ValueNotSet, WrongType)
template<typename T>
T * getObjectAsL (CUrl url) throw (NoSuchProperty, ValueNotSet, WrongType)
RDK2::Object * getObjectOrCreateItL (CUrl url) throw (NoSuchProperty, InvalidOperation)
Storage modifying
void setObject (CUrl, RDK2::Object *object) throw (NoSuchProperty, InvalidOperation, WrongType)
bool pushDiffInDiffQueue (CUrl, ObjectDiff *diff) throw (NoSuchProperty, InvalidOperation)
Events
void valueChanged (CUrl url) throw (NoSuchProperty, InvalidOperation)
void valueChanged (CUrl url, const vector< ObjectDiff * > &diffs) throw (NoSuchProperty, InvalidOperation)
void wakeUpListeningSessions (CUrl url, Event *event) throw (NoSuchProperty)
Data Structures
struct SessionTimer
Timer thread stuff.
Constructor & Destructor Documentation
RDK2::RepositoryNS::Repository::Repository (cstr repositoryName)
Constructor
Parameters:
repositoryName repository name, globally unique (it is the "host" part of the url)
Definition at line 41 of file repository.cpp.
References addGenericProperty(), createStorage(), getLocalProperty(), RDK2::RPrimitive::RDouble::MS, PROPERTY_INBOX, PROPERTY_OUTBOX, PROPERTY_TCP_LISTENING_PORT, PROPERTY_UDP_PORT, PROPERTY_UDP_RENEWAL_INTERVAL, PROPERTY_UDP_RENEWAL_TIMEOUT, PROPERTY_YELLOWPAGES, PROPERTY_YELLOWPAGES_FILENAME, QUEUE_CLASSNAME, RDK_ERROR_PRINTF, RDK2::RepositoryNS::Property::setObject(), RDK2::RepositoryNS::Property::setPersistent(), and RDK2::RepositoryNS::Property::setReadonly().
RDK2::RepositoryNS::Repository::~Repository () [virtual]
Destructor.
Definition at line 72 of file repository.cpp.
References endRepositoryThreads(), RDK2::RAgent::for(), HERE, localProperties, PosixConstructs::PosixMutex::lock(), propertiesMutex, remoteProperties, and PosixConstructs::PosixMutex::unlock().
Member Function Documentation
string RDK2::RepositoryNS::Repository::getRepositoryName () [inline]
Each repository has a unique name, i.e. the one used in the constructor.
Definition at line 76 of file repository.h.
Referenced by RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription(), RDK2::RepositoryNS::Session::getRepositoryName(), and RDK2::RepositoryNS::TcpManager::tryConnectTo().
Url RDK2::RepositoryNS::Repository::getBaseUrl () [inline]
Globally, each property of this repository begins with its base url, i.e. "rdk://" + repositoryName.
Definition at line 79 of file repository.h.
Session * RDK2::RepositoryNS::Repository::createSession (cstr name, cstr descName, cstr urlContext)
Creation of a new session.
Parameters:
urlContext context for the session (absolute url, starting with "/" and without host name)
descName descriptive name
Definition at line 217 of file repository.cpp.
References Session.
Referenced by RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), RDK2::RepositoryNS::RemotePropertyManager::periodicSender(), RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal(), and RDK2::RepositoryNS::RemotePropertyManager::receiver().
bool RDK2::RepositoryNS::Repository::loadYellowPages (cstr ypFilename)
Loads the yellow pages
Parameters:
ypFilename the file name
Definition at line 99 of file repository.cpp.
References RDK2::RNetObjects::RYellowPages::loadFromFile(), lock(), PROPERTY_YELLOWPAGES, PROPERTY_YELLOWPAGES_FILENAME, RDK_ERROR_PRINTF, RDK_INFO_PRINTF, setObject(), unlock(), and WHERE.
void RDK2::RepositoryNS::Repository::startRepositoryThreads ()
Starts the comunication threads (UDP, TCP, and Remote property manager).
Definition at line 199 of file repository.cpp.
References RDK2::RepositoryNS::RemotePropertyManager::init(), RDK2::RepositoryNS::TcpManager::init(), RDK2::RepositoryNS::UdpManager::init(), RemotePropertyManager, remotePropertyManager, RDK2::RepositoryNS::RemotePropertyManager::start(), RDK2::RepositoryNS::TcpManager::start(), RDK2::RepositoryNS::UdpManager::start(), TcpManager, tcpManager, timerThreadExec(), timerThreadId, timerThreadStarted, and udpManager.
void RDK2::RepositoryNS::Repository::endRepositoryThreads ()
Definition at line 83 of file repository.cpp.
References DELETE_AND_SET_ZERO, exitTimerThread, RDK_DEBUG_PRINTF, remotePropertyManager, tcpManager, timerThreadId, timerThreadStarted, and udpManager.
Referenced by ~Repository().
map< Url, string > RDK2::RepositoryNS::Repository::getLocalPropertyNames ()
Returns:
a map: url (absolute), class name
Definition at line 329 of file repository.cpp.
References HERE, localProperties, PosixConstructs::PosixMutex::lock(), propertiesMutex, and PosixConstructs::PosixMutex::unlock().
map< Url, string > RDK2::RepositoryNS::Repository::getRemotePropertyNames (cstr host)
Returns:
a map: url (complete), class name
Definition at line 341 of file repository.cpp.
References HERE, PosixConstructs::PosixMutex::lock(), propertiesMutex, remoteProperties, and PosixConstructs::PosixMutex::unlock().
vector< Url > RDK2::RepositoryNS::Repository::getLocalPropertiesStartingWith (string prefix)
Definition at line 357 of file repository.cpp.
References HERE, localProperties, PosixConstructs::PosixMutex::lock(), propertiesMutex, RDK2::TextUtils::startsWith(), and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RAgent::Module::createModuleConfig().
Property * RDK2::RepositoryNS::Repository::getProperty (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Take the address of a property.
Parameters:
url absolute or complete url of the property, can be remote
Definition at line 64 of file repository_utils.cpp.
References RDK2::RepositoryNS::Property::deleted, RDK2::RepositoryNS::Url::getPath(), HERE, RDK2::RepositoryNS::Url::isComplete(), RDK2::RepositoryNS::Property::isLink(), RDK2::RepositoryNS::Property::linkTo, PosixConstructs::PosixMutex::lock(), MAX_LINK_LEVELS, and PosixConstructs::PosixMutex::unlock().
Referenced by getObjectAsL(), getObjectAsLC(), getObjectL(), getObjectLC(), getObjectOrCreateItL(), lock(), RDK2::RepositoryNS::Session::lockAndGetProperty(), RDK2::RepositoryNS::Session::propertyExists(), unlock(), and wakeUpListeningSessions().
Property * RDK2::RepositoryNS::Repository::getProperty (CUrl url, Session * session) throw (NoSuchProperty) [protected]
Definition at line 36 of file repository_utils.cpp.
Property * RDK2::RepositoryNS::Repository::getLocalProperty (CUrl url) throw (NoSuchProperty) [protected]
Definition at line 42 of file repository_utils.cpp.
References RDK2::RepositoryNS::Url::getHost(), RDK2::RepositoryNS::Url::getPath(), HERE, and RDK2::RepositoryNS::Url::isComplete().
Referenced by Repository().
Property * RDK2::RepositoryNS::Repository::getRemoteProperty (CUrl url, Session * askingSession) throw () [protected]
Definition at line 41 of file repository_remote.cpp.
References RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription(), RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::completeUrl, Network::CONNECTED, DOUT, HERE, PosixConstructs::PosixMutex::lock(), Network::NETPROTOCOL_ANY, RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToReceive(), RDK2::RepositoryNS::RRemoteSubscription::socketType, Network::TCP_IP, Network::UDP_IP, RDK2::RepositoryNS::RRemoteSubscription::WHAT_ANY, and RDK2::RepositoryNS::RRemoteSubscription::WHEN_ANY.
Referenced by RDK2::RepositoryNS::Session::getProperty(), and RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage().
bool RDK2::RepositoryNS::Repository::isLocalProperty (CUrl url) throw () [protected]
Definition at line 100 of file repository_utils.cpp.
Referenced by RDK2::RepositoryNS::Session::getProperty(), and setRemotePropertyDef().
void RDK2::RepositoryNS::Repository::addGenericProperty (cstr className, CUrl url, cstr description, RDK2::Object * defaultObject = 0) throw (InvalidOperation) [protected]
XXX aggiornare quella precedente (cosi' c'e' memory leak)
Definition at line 222 of file repository.cpp.
References RDK2::RepositoryNS::Property::def, RDK2::RepositoryNS::Property::description, HERE, localProperties, PosixConstructs::PosixMutex::lock(), propertiesMutex, sessionsListeningToTree, RDK2::RepositoryNS::PropertyDef::setDescription(), and PosixConstructs::PosixMutex::unlock().
Referenced by Repository().
void RDK2::RepositoryNS::Repository::deleteProperty (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 268 of file repository.cpp.
References HERE, localProperties, PosixConstructs::PosixMutex::lock(), propertiesMutex, sessionsListeningToTree, and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::Session::deleteProperty(), and RDK2::RepositoryNS::Session::~Session().
void RDK2::RepositoryNS::Repository::lock (CUrl url, Stack w) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 319 of file repository.cpp.
References getProperty(), and PosixConstructs::PosixMutex::lock().
Referenced by loadYellowPages(), RDK2::RepositoryNS::Session::lock(), RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), and wakeUpListeningSessions().
void RDK2::RepositoryNS::Repository::unlock (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 324 of file repository.cpp.
References getProperty(), and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::Session::getObjectClone(), loadYellowPages(), RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), RDK2::RepositoryNS::Session::unlock(), and wakeUpListeningSessions().
void RDK2::RepositoryNS::Repository::createStorage (cstr className, CUrl url, cstr description, RDK2::Object * defaultObject = 0) throw (InvalidOperation) [protected]
Definition at line 35 of file repository_storage.cpp.
References QUEUE_CLASSNAME.
Referenced by RDK2::RepositoryNS::Session::createStorage(), and Repository().
const RDK2::Object * RDK2::RepositoryNS::Repository::getObjectLC (CUrl url) throw (NoSuchProperty) [protected]
Definition at line 292 of file repository.cpp.
References RDK2::RepositoryNS::Property::getObjectLC(), and getProperty().
RDK2::Object * RDK2::RepositoryNS::Repository::getObjectL (CUrl url) throw (NoSuchProperty) [protected]
Definition at line 297 of file repository.cpp.
References RDK2::RepositoryNS::Property::getObjectL(), and getProperty().
template<typename T> const T * RDK2::RepositoryNS::Repository::getObjectAsLC (CUrl url) throw (NoSuchProperty, ValueNotSet, WrongType) [inline, protected]
Definition at line 215 of file repository.h.
References RDK2::RepositoryNS::Property::getObjectAsLC(), and getProperty().
template<typename T> T * RDK2::RepositoryNS::Repository::getObjectAsL (CUrl url) throw (NoSuchProperty, ValueNotSet, WrongType) [inline, protected]
Definition at line 221 of file repository.h.
References RDK2::RepositoryNS::Property::getObjectAsL(), and getProperty().
RDK2::Object * RDK2::RepositoryNS::Repository::getObjectOrCreateItL (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 302 of file repository.cpp.
References RDK2::Meta::forName(), RDK2::RepositoryNS::Property::getObjectClassName(), RDK2::RepositoryNS::Property::getObjectL(), getProperty(), and RDK2::RepositoryNS::Property::setObjectL().
Referenced by RDK2::RepositoryNS::Session::getObjectOrCreateItL(), and RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage().
void RDK2::RepositoryNS::Repository::setObject (CUrl url, RDK2::Object * object) throw (NoSuchProperty, InvalidOperation, WrongType) [protected]
Definition at line 114 of file repository_storage.cpp.
References HERE, RDK2::RepositoryNS::Property::isStorage(), and RDK2::RepositoryNS::Property::setObjectL().
Referenced by loadYellowPages(), RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), and RDK2::RepositoryNS::Session::setObject().
bool RDK2::RepositoryNS::Repository::pushDiffInDiffQueue (CUrl url, ObjectDiff * diff) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 126 of file repository_storage.cpp.
References RDK2::Geometry::diff(), RDK2::RepositoryNS::Property::diffsQueue, PosixQueues::PipeQueue< T >::gc(), HERE, RDK2::RepositoryNS::Property::isStorage(), and PosixQueues::PipeQueue< T >::push().
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage().
void RDK2::RepositoryNS::Repository::valueChanged (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 42 of file repository_storage.cpp.
Referenced by RDK2::RepositoryNS::Session::valueChanged().
void RDK2::RepositoryNS::Repository::valueChanged (CUrl url, const vector< ObjectDiff * > & diffs) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 48 of file repository_storage.cpp.
References Network::NETPROTOCOL_ANY, RDK2::RepositoryNS::RRemoteSubscription::ON_CHANGE, RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToSend(), RDK2::RepositoryNS::RRemoteSubscription::STORAGE_DIFFS, RDK2::RepositoryNS::RRemoteSubscription::STORAGE_VALUE, and Network::TCP_IP.
void RDK2::RepositoryNS::Repository::wakeUpListeningSessions (CUrl url, Event * event) throw (NoSuchProperty) [protected]
Definition at line 95 of file repository_storage.cpp.
References getProperty(), HERE, RDK2::RepositoryNS::Property::listeningSessions, lock(), and unlock().
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage().
bool RDK2::RepositoryNS::Repository::queuePush (CUrl Curl, RDK2::Object * object) throw (NoSuchProperty, InvalidOperation)
Definition at line 28 of file repository_queue.cpp.
References PosixQueues::PipeQueue< T >::gc(), RDK2::RepositoryNS::Url::getHost(), RDK2::RepositoryNS::Property::getObjectClassName(), HERE, RDK2::RepositoryNS::Url::isComplete(), RDK2::RepositoryNS::Property::isQueue(), PosixConstructs::PosixMutex::lock(), PosixQueues::PipeQueue< T >::push(), QUEUE_CLASSNAME, RDK_DEBUG_PRINTF, RDK2::RepositoryNS::Property::setObjectClassName(), PosixConstructs::PosixMutex::unlock(), and RDK2::RepositoryNS::Property::url.
Referenced by RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription(), and RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage().
void RDK2::RepositoryNS::Repository::saveAllDefaultPropertyDefs ()
Definition at line 408 of file repository.cpp.
References HERE, localProperties, PosixConstructs::PosixMutex::lock(), propertiesMutex, and PosixConstructs::PosixMutex::unlock().
static void* RDK2::RepositoryNS::Repository::timerThreadExec (Repository * repository) [inline, static, protected]
Definition at line 174 of file repository.h.
References timerThread().
Referenced by startRepositoryThreads().
void RDK2::RepositoryNS::Repository::timerThread () [protected]
Definition at line 383 of file repository.cpp.
References exitTimerThread, RDK2::RepositoryNS::gcd(), HERE, PosixConstructs::PosixMutex::lock(), RDK_INFO_PRINTF, sessionsListeningToTimer, sessionsListeningToTimerMutex, and PosixConstructs::PosixMutex::unlock().
Referenced by timerThreadExec().
void RDK2::RepositoryNS::Repository::remotePropertyOptions (CUrl url, Network::NetProtocol socketType = Network::TCP_IP, RRemoteSubscription::What what = RRemoteSubscription::STORAGE_DIFFS, RRemoteSubscription::When when = RRemoteSubscription::PERIODIC, double minPeriod = 50., double maxPeriod = 500.) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 328 of file repository_remote.cpp.
References RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription(), RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::completeUrl, HERE, RDK2::RepositoryNS::RRemoteSubscription::maxPeriod, RDK2::RepositoryNS::RRemoteSubscription::minPeriod, RDK2::RepositoryNS::RRemoteSubscription::socketType, RDK2::RepositoryNS::RRemoteSubscription::what, and RDK2::RepositoryNS::RRemoteSubscription::when.
Referenced by RDK2::RepositoryNS::Session::remotePropertyOptions().
void RDK2::RepositoryNS::Repository::setPropertyValueFromTextConfig (cstr key, cstr val, CUrl urlContext, Session * session) throw (NoSuchProperty, InvalidOperation)
Definition at line 143 of file repository.cpp.
References HERE, RDK2::Object::loadFromStringRepresentation(), and RDK_ERROR_PRINTF.
void RDK2::RepositoryNS::Repository::sendStorageValueToHost (CUrl completeUrl, cstr askingHost, Network::NetProtocol socketType, RDK2::Object * objToSend = 0) throw ()
Definition at line 127 of file repository_remote.cpp.
References RDK2::Object::clone(), RDK2::RepositoryNS::RPropertyUpdate::DIFF, DOUT, RDK2::RepositoryNS::Property::getObjectClassName(), PROPERTY_OUTBOX, RDK2::RNetObjects::RNetMessage::PROPERTY_UPDATE, RDK_ERROR_PRINTF, Network::TCP_IP, Network::UDP_IP, RDK2::RepositoryNS::RPropertyUpdate::VALUE, and WHERE.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageSubscriptionMessage().
void RDK2::RepositoryNS::Repository::sendStorageValuesToRemoteValueSubscribers (CUrl completeUrl, cstr askingHost, Network::NetProtocol socketType, RRemoteSubscription::What what, RRemoteSubscription::When when) throw ()
Definition at line 111 of file repository_remote.cpp.
References RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToSend(), and RDK2::RepositoryNS::RemoteSubscriptionRegister::refreshLastSendingTimestamp().
Referenced by RDK2::RepositoryNS::RemotePropertyManager::periodicSender().
void RDK2::RepositoryNS::Repository::sendStorageDiffToHost (CUrl completeUrl, cstr askingHost, Network::NetProtocol socketType, ObjectDiff * diffToSend) throw ()
Definition at line 276 of file repository_remote.cpp.
References RDK2::RepositoryNS::RPropertyUpdate::DIFF, DOUT, HERE, PROPERTY_OUTBOX, RDK2::RNetObjects::RNetMessage::PROPERTY_UPDATE, RDK_ERROR_PRINTF, Network::TCP_IP, and Network::UDP_IP.
void RDK2::RepositoryNS::Repository::sendObjectsToRemoteQueueSubscribers (CUrl completeUrl, const RDK2::Object * objToSend) throw ()
Definition at line 96 of file repository_remote.cpp.
References RDK2::RepositoryNS::RPropertyUpdate::ENQUEUE, Network::NETPROTOCOL_ANY, PROPERTY_OUTBOX, RDK2::RNetObjects::RNetMessage::PROPERTY_UPDATE, RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToSend(), RDK2::RepositoryNS::RRemoteSubscription::QUEUE, RDK_DEBUG_PRINTF, and RDK2::RepositoryNS::RRemoteSubscription::WHEN_ANY.
void RDK2::RepositoryNS::Repository::setRemotePropertyDef (CUrl url, const RPropertyDef * def)
Definition at line 353 of file repository_remote.cpp.
References RDK2::RepositoryNS::Property::getObjectClassName(), HERE, isLocalProperty(), PosixConstructs::PosixMutex::lock(), propertiesMutex, RDK_DEBUG_PRINTF, remoteProperties, sessionsListeningToTree, RDK2::RepositoryNS::Url::startsWith(), and PosixConstructs::PosixMutex::unlock().
Friends And Related Function Documentation
friend class Session [friend]
Definition at line 208 of file repository.h.
Referenced by createSession().
friend class RemotePropertyManager [friend]
Definition at line 209 of file repository.h.
Referenced by startRepositoryThreads().
friend class TcpManager [friend]
Definition at line 210 of file repository.h.
Referenced by startRepositoryThreads().
friend class RemoteSubscriptionRegister [friend]
Definition at line 211 of file repository.h.
Field Documentation
string RDK2::RepositoryNS::Repository::repositoryName [protected]
Definition at line 153 of file repository.h.
PosixConstructs::PosixMutex RDK2::RepositoryNS::Repository::propertiesMutex [protected]
Repository properties.
Definition at line 156 of file repository.h.
Referenced by addGenericProperty(), deleteProperty(), getLocalPropertiesStartingWith(), getLocalPropertyNames(), RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Session::getPropertyNamesStartingWith(), getRemotePropertyNames(), saveAllDefaultPropertyDefs(), setRemotePropertyDef(), ~Repository(), and RDK2::RepositoryNS::Session::~Session().
map<Url, Property*> RDK2::RepositoryNS::Repository::localProperties [protected]
Definition at line 157 of file repository.h.
Referenced by addGenericProperty(), deleteProperty(), getLocalPropertiesStartingWith(), getLocalPropertyNames(), RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Session::getPropertyNamesStartingWith(), saveAllDefaultPropertyDefs(), ~Repository(), and RDK2::RepositoryNS::Session::~Session().
map<Url, Property*> RDK2::RepositoryNS::Repository::remoteProperties [protected]
Definition at line 158 of file repository.h.
Referenced by RDK2::RepositoryNS::Session::getPropertyNamesStartingWith(), getRemotePropertyNames(), setRemotePropertyDef(), ~Repository(), and RDK2::RepositoryNS::Session::~Session().
PosixConstructs::PosixMutex RDK2::RepositoryNS::Repository::sessionsListeningToTreeMutex [protected]
Sessions listening to tree changes.
Definition at line 161 of file repository.h.
Referenced by RDK2::RepositoryNS::Session::~Session().
multimap<string, Session*> RDK2::RepositoryNS::Repository::sessionsListeningToTree [protected]
Definition at line 162 of file repository.h.
Referenced by addGenericProperty(), deleteProperty(), setRemotePropertyDef(), and RDK2::RepositoryNS::Session::~Session().
volatile bool RDK2::RepositoryNS::Repository::exitTimerThread [protected]
Definition at line 169 of file repository.h.
Referenced by endRepositoryThreads(), and timerThread().
PosixConstructs::PosixMutex RDK2::RepositoryNS::Repository::sessionsListeningToTimerMutex [protected]
Definition at line 170 of file repository.h.
Referenced by timerThread(), and RDK2::RepositoryNS::Session::~Session().
map<Session*, SessionTimer> RDK2::RepositoryNS::Repository::sessionsListeningToTimer [protected]
Definition at line 171 of file repository.h.
Referenced by timerThread(), and RDK2::RepositoryNS::Session::~Session().
pthread_t RDK2::RepositoryNS::Repository::timerThreadId [protected]
Definition at line 172 of file repository.h.
Referenced by endRepositoryThreads(), and startRepositoryThreads().
bool RDK2::RepositoryNS::Repository::timerThreadStarted [protected]
Definition at line 173 of file repository.h.
Referenced by endRepositoryThreads(), and startRepositoryThreads().
UdpManager* RDK2::RepositoryNS::Repository::udpManager [protected]
Comunication threads.
Definition at line 178 of file repository.h.
Referenced by endRepositoryThreads(), and startRepositoryThreads().
TcpManager* RDK2::RepositoryNS::Repository::tcpManager [protected]
Definition at line 179 of file repository.h.
Referenced by endRepositoryThreads(), RDK2::RepositoryNS::Session::getConnectionStatusWith(), startRepositoryThreads(), and RDK2::RepositoryNS::Session::tryConnectTo().
RemotePropertyManager* RDK2::RepositoryNS::Repository::remotePropertyManager [protected]
Definition at line 180 of file repository.h.
Referenced by endRepositoryThreads(), and startRepositoryThreads().
RemoteSubscriptionRegister RDK2::RepositoryNS::Repository::remoteSubscriptionRegister
Definition at line 183 of file repository.h.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageSubscriptionMessage(), RDK2::RepositoryNS::RemotePropertyManager::periodicSender(), RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal(), and RDK2::RepositoryNS::Session::~Session().
The documentation for this class was generated from the following files:
repository.h
repository.cpp
repository_queue.cpp
repository_remote.cpp
repository_storage.cpp
repository_utils.cpp