OpenRDK: RDK2::Time::TimerR Class Reference
RDK2::Time::TimerR Class Reference
#include <time.h>
Detailed Description
This measures the real time.
Definition at line 94 of file time.h.
Public Member Functions
TimerR ()
void start ()
double getMs ()
double getSeconds ()
Constructor & Destructor Documentation
RDK2::Time::TimerR::TimerR () [inline]
Definition at line 96 of file time.h.
References start().
Member Function Documentation
void RDK2::Time::TimerR::start () [inline]
Definition at line 97 of file time.h.
References RDK2::Time::Timestamp::setToNow().
Referenced by RDK2::RepositoryNS::Session::start(), and TimerR().
double RDK2::Time::TimerR::getMs () [inline]
Definition at line 98 of file time.h.
References RDK2::Time::Timestamp::getMs().
Referenced by getSeconds().
double RDK2::Time::TimerR::getSeconds () [inline]
Definition at line 99 of file time.h.
References getMs().
Referenced by RDK2::RepositoryNS::Session::start().
The documentation for this class was generated from the following file:
time.h