OpenRDK: RDK2::RGraphics::RImage Class Reference
RDK2::RGraphics::RImage Class Reference
#include <rimage.h>
Detailed Description
Definition at line 37 of file rimage.h.
Image attributes
size_t getWidth () const
size_t getHeight () const
Type getType () const
size_t getBufferSize () const
size_t getDataSize () const
size_t getBytesPerPixel ()
unsigned char * getBuffer ()
const unsigned char * getBuffer () const
static size_t getBytesPerPixel (Type t)
Public Types
enum Type {
RGB32 = FOURCC('R', 'G', 'B', '4'), RGB24 = FOURCC('R', 'G', 'B', '3'), GREY = FOURCC('G', 'R', 'E', 'Y'), C8 = FOURCC('R', 'D', 'K', 'M'),
JPEG = FOURCC('J', 'P', 'E', 'G'), YUYV = FOURCC('Y', 'U', 'Y', 'V')
}
enum C8Color {
C8Unset = 0, C8Black = 1, C8Blue = 2, C8Green = 4,
C8Cyan = 8, C8Red = 16, C8Magenta = 32, C8White = 64,
C8Grey = 128
}
Public Member Functions
RImage ()
RImage (int w, int h, Type t, unsigned char *buf=0)
RImage (const RImage &img, int x0, int y0, int x1, int y1)
virtual ~RImage ()
RImage (const RImage &)
RImage & operator= (const RImage &)
virtual void setSizeAndType (size_t w, size_t h, Type t)
virtual void canvasResize (size_t w, size_t h, size_t x=0, size_t y=0, unsigned char fillValue=0)
virtual void fillBuffer (unsigned char fillValue)
virtual void imageResize (size_t w, size_t h)
virtual RImage * convertTo (Type t) const
RDK::Object Interface
virtual RDK2::Object * clone () const
Pixel access
void setPixel (size_t x, size_t y, size_t component, unsigned char value)
unsigned char getPixel (size_t x, size_t y, size_t component) const
bool safeSetPixel (size_t x, size_t y, size_t component, unsigned char value)
unsigned char safeGetPixel (size_t x, size_t y, size_t component, unsigned char defaultValue) const
virtual bool knowsDiffs ()
virtual bool applyDiff (const ObjectDiff *diff)
virtual vector< ObjectDiff * > splitInDiffs (size_t maxSize)
Serialization interface
virtual void read (Reader *r) throw (ReadingException)
virtual void write (Writer *w) const throw (WritingException)
ImageMagick (Magick++) functions
bool loadMagick (std::string filename, double occupied=0.5, double equal=0.1)
bool saveMagick (std::string filename, bool trimImage=false)
Protected Member Functions
virtual void initBuffer (int width, int height, Type type, void *buf, unsigned char fillValue, bool freeOldBuffer=true)
void readImpl (Reader *r) throw (ReadingException)
void writeImpl (Writer *w) const throw (WritingException)
Conversions implementation
virtual RImage * toRGB32 () const
virtual RImage * toRGB24 () const
virtual RImage * toGrey () const
virtual RImage * toC8 () const
Protected Attributes
Image attributes
size_t width
size_t height
Type type
size_t bpp
unsigned char * buffer
unsigned char ** rows
size_t bufferSize
size_t dataSize
Member Enumeration Documentation
enum RDK2::RGraphics::RImage::Type
Image types
Enumerator:
RGB32
RGB24
GREY
C8 OpenRDK eight-colors map format.
JPEG
YUYV
Definition at line 40 of file rimage.h.
enum RDK2::RGraphics::RImage::C8Color
Colors for OpenRDK eight-colors map format
Enumerator:
C8Unset
C8Black
C8Blue
C8Green
C8Cyan
C8Red
C8Magenta
C8White
C8Grey
Definition at line 50 of file rimage.h.
Constructor & Destructor Documentation
RDK2::RGraphics::RImage::RImage ()
Create an empty image: this should be used only internally by the RDK2::Object prototype database
Definition at line 64 of file rimage.cpp.
References C8, and initBuffer().
Referenced by clone(), convertTo(), and toRGB32().
RDK2::RGraphics::RImage::RImage (int w, int h, Type t, unsigned char * buf = 0)
Create an image with the given dimensions and type
Parameters:
w image width
h image height
t image type
buf buffer with image data, this will be COPIED; if
buf is not given, image data is not initialized
Definition at line 69 of file rimage.cpp.
References initBuffer().
RDK2::RGraphics::RImage::RImage (const RImage & img, int x0, int y0, int x1, int y1)
Create a new image, "clipping" an existing image
Parameters:
img image to clip
x0 left
y0 top
x1 right
y1 bottom
RDK2::RGraphics::RImage::~RImage () [virtual]
RImage destructor, deallocates memory
Definition at line 104 of file rimage.cpp.
References buffer, and rows.
RDK2::RGraphics::RImage::RImage (const RImage & img)
Copy constructor: the returned image is a deep copy of the original one, i.e., the buffer is copied, not shared
See also:
RImage::operator=
Definition at line 74 of file rimage.cpp.
References buffer, height, initBuffer(), type, and width.
Member Function Documentation
RImage & RDK2::RGraphics::RImage::operator= (const RImage & img)
Assignment operator
Definition at line 98 of file rimage.cpp.
References buffer, height, initBuffer(), type, and width.
void RDK2::RGraphics::RImage::initBuffer (int width, int height, Type type, void * buf, unsigned char fillValue, bool freeOldBuffer = true) [protected, virtual]
Used by constructors. Sets up the buffer and rows. If buf!=0, copies the buffer from buf; else, the buffer is set to 'color'.
Definition at line 40 of file rimage.cpp.
References bpp, buffer, bufferSize, dataSize, getBytesPerPixel(), height, rows, type, and width.
Referenced by canvasResize(), imageResize(), operator=(), RImage(), and setSizeAndType().
RDK2::Object * RDK2::RGraphics::RImage::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 92 of file rimage.cpp.
References RImage().
Referenced by RDK2::RMaps::RVictimOnMap::clone().
void RDK2::RGraphics::RImage::setSizeAndType (size_t w, size_t h, Type t) [virtual]
Changes the width, height and type of the image; the buffer is resized accordingly, the image data are lost
Parameters:
w width
h height
t type
Definition at line 110 of file rimage.cpp.
References height, initBuffer(), type, and width.
Referenced by applyDiff(), and loadMagick().
void RDK2::RGraphics::RImage::canvasResize (size_t w, size_t h, size_t x = 0, size_t y = 0, unsigned char fillValue = 0) [virtual]
Resizes the image buffer, the original image is placed inside the new buffer, at the given coordinates
Parameters:
w width of the new buffer
h height of the new buffer
x x coordinate where to place the old image
y y coordinate where to place the old image
fillValue fill value for the pixels not set by the old image placement
Definition at line 121 of file rimage.cpp.
References bpp, buffer, height, initBuffer(), RDK2::Geometry::max(), RDK2::Geometry::min(), rows, type, and width.
Referenced by RDK2::RMaps::RMapImage::canvasReshape().
void RDK2::RGraphics::RImage::fillBuffer (unsigned char fillValue) [virtual]
Fill the buffer with a specified value
Parameters:
fillValue value used to fill the buffer
Definition at line 116 of file rimage.cpp.
References buffer, and bufferSize.
void RDK2::RGraphics::RImage::imageResize (size_t w, size_t h) [virtual]
Resizes the image, using sampling technique
Parameters:
w width of the new image
h height of the new image
Definition at line 152 of file rimage.cpp.
References bpp, buffer, height, initBuffer(), rows, type, and width.
size_t RDK2::RGraphics::RImage::getWidth () const [inline]
Returns:
image width
Definition at line 135 of file rimage.h.
References width.
Referenced by RDK2::RMaps::RMapImage::buf2world(), RDK2::RMaps::RMapImage::calcClearance_b(), RDK2::RMaps::RMapImage::distMapRayTracing(), RDK2::RMaps::RMapImage::getMapDelta(), RDK2::RMaps::RMapImage::getRealHeight(), RDK2::RMaps::RMapImage::line(), RDK2::RMaps::RMapImage::minWorldY(), RDK2::RMaps::RMapImage::move(), RDK2::RMaps::RMapImage::obsDenRayTracing(), RDK2::RMaps::RMapImage::rayTracing(), RDK2::RMaps::RMapImage::rayTracing2(), RDK2::RGraphics::RImageDiffPoints::RImageDiffPoints(), RDK2::RGraphics::RImageDiffRect::RImageDiffRect(), RDK2::RMaps::RMapImage::splitInDiffs(), splitInDiffs(), RDK2::RMaps::RMapImage::toString(), RDK2::RMaps::RMapImage::visibilityCheck(), and RDK2::RMaps::RMapImage::world2buf().
size_t RDK2::RGraphics::RImage::getHeight () const [inline]
Returns:
image height
Definition at line 138 of file rimage.h.
References height.
Referenced by RDK2::RMaps::RMapImage::calcClearance_b(), RDK2::RMaps::RMapImage::distMapRayTracing(), RDK2::RMaps::RMapImage::getRealHeight(), RDK2::RMaps::RMapImage::line(), RDK2::RMaps::RMapImage::minWorldY(), RDK2::RMaps::RMapImage::move(), RDK2::RMaps::RMapImage::obsDenRayTracing(), RDK2::RMaps::RMapImage::rayTracing(), RDK2::RMaps::RMapImage::rayTracing2(), RDK2::RGraphics::RImageDiffRect::RImageDiffRect(), RDK2::RMaps::RMapImage::sameGeometry(), RDK2::RMaps::RMapImage::splitInDiffs(), splitInDiffs(), RDK2::RMaps::RMapImage::toString(), RDK2::RMaps::RMapImage::visibilityCheck(), and RDK2::RMaps::RMapImage::world2buf().
Type RDK2::RGraphics::RImage::getType () const [inline]
Returns:
image type
Definition at line 141 of file rimage.h.
References type.
Referenced by applyDiff(), RDK2::RGraphics::RImageDiffPoints::RImageDiffPoints(), and RDK2::RGraphics::RImageDiffRect::RImageDiffRect().
size_t RDK2::RGraphics::RImage::getBufferSize () const [inline]
Returns:
data buffer size
Definition at line 144 of file rimage.h.
References bufferSize.
size_t RDK2::RGraphics::RImage::getDataSize () const [inline]
Returns:
data size (i.e., the actual size of data in the buffer; for non-compressed images, it is the same of getBufferSize())
Definition at line 149 of file rimage.h.
References dataSize.
size_t RDK2::RGraphics::RImage::getBytesPerPixel (RImage::Type t) [static]
Returns:
bytes per pixel for the given type
Definition at line 79 of file rimage.cpp.
References C8, GREY, JPEG, RGB24, RGB32, and YUYV.
size_t RDK2::RGraphics::RImage::getBytesPerPixel () [inline]
Returns:
bytes per pixel for this image
Definition at line 155 of file rimage.h.
References bpp.
Referenced by RDK2::RGraphics::compressImgLine(), initBuffer(), saveMagick(), and RDK2::RGraphics::uncompressImgDiffCBuf().
unsigned char* RDK2::RGraphics::RImage::getBuffer () [inline]
Returns:
the buffer where data resides
Definition at line 159 of file rimage.h.
References buffer.
Referenced by RDK2::RMaps::RMapImage::move(), RDK2::RGraphics::RImageDiffPoints::RImageDiffPoints(), and RDK2::RGraphics::RImageDiffRect::RImageDiffRect().
const unsigned char* RDK2::RGraphics::RImage::getBuffer () const [inline]
Definition at line 160 of file rimage.h.
References buffer.
void RDK2::RGraphics::RImage::setPixel (size_t x, size_t y, size_t component, unsigned char value) [inline]
Definition at line 165 of file rimage.h.
References bpp, and rows.
Referenced by safeSetPixel(), and RDK2::RMaps::RMapImage::setPixelB().
unsigned char RDK2::RGraphics::RImage::getPixel (size_t x, size_t y, size_t component) const [inline]
Definition at line 166 of file rimage.h.
References bpp, and rows.
Referenced by RDK2::RMaps::RMapImage::getPixelB(), and safeGetPixel().
bool RDK2::RGraphics::RImage::safeSetPixel (size_t x, size_t y, size_t component, unsigned char value) [inline]
This function set a pixel only if the (x, y) coordinates are inside the image
Returns:
true if the (x, y) coordinates were inside the image, false otherwise
Definition at line 172 of file rimage.h.
References height, setPixel(), and width.
Referenced by RDK2::RMaps::RMapImage::safeSetPixelB().
unsigned char RDK2::RGraphics::RImage::safeGetPixel (size_t x, size_t y, size_t component, unsigned char defaultValue) const [inline]
This function gets the pixel at coordinates (x, y) if they are inside the image, otherwise defaultValue
Returns:
the color at coordinates (x, y) if the pixel is inside the image, otherwise it returns defaultValue
Definition at line 179 of file rimage.h.
References getPixel(), height, and width.
Referenced by RDK2::RMaps::RMapImage::safeGetPixelB().
virtual bool RDK2::RGraphics::RImage::knowsDiffs () [inline, virtual]
Diff management (maybe will be DEPRECATED)
Reimplemented from RDK2::Object.
Definition at line 186 of file rimage.h.
bool RDK2::RGraphics::RImage::applyDiff (const ObjectDiff * diff) [virtual]
Reimplemented from RDK2::Object.
Definition at line 83 of file rimage_diffs.cpp.
References buffer, C8, RDK2::RGraphics::RImageDiffPoints::colorsC8, getType(), RDK2::RGraphics::RImageDiffPoints::points, RDK_ERROR_PRINTF, RDK2::RGraphics::RImageDiffRect::refImageHeight, RDK2::RGraphics::RImageDiffRect::refImageType, RDK2::RGraphics::RImageDiffRect::refImageWidth, setSizeAndType(), and width.
Referenced by RDK2::RMaps::RMapImage::applyDiff().
vector< ObjectDiff * > RDK2::RGraphics::RImage::splitInDiffs (size_t maxSize) [virtual]
Reimplemented from RDK2::Object.
Definition at line 44 of file rimage_diffs.cpp.
References buffer, RDK2::RGraphics::RImageDiffJpegPacket::data, getHeight(), getWidth(), JPEG_QUALITY, RDK2::RGraphics::RImageDiffJpegPacket::packetNumber, RGB32, RDK2::RGraphics::RImageDiffRect::split(), and type.
void RDK2::RGraphics::RImage::read (Reader * r) throw (ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 133 of file rimage_serialization.cpp.
References RDK2::Statistics::r.
void RDK2::RGraphics::RImage::write (Writer *) const throw (WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 95 of file rimage_serialization.cpp.
void RDK2::RGraphics::RImage::readImpl (Reader * r) throw (ReadingException) [protected]
Does the real job of serialization except for startReading() and doneReading() This method exists to be called by the subclasses.
Author:
Matteo Leonetti (the one to blame)
Definition at line 102 of file rimage_serialization.cpp.
References C8, RDK2::RGraphics::expandC8(), and RDK2::Statistics::r.
void RDK2::RGraphics::RImage::writeImpl (Writer * w) const throw (WritingException) [protected]
Does the real job of serialization except for startWriting() and doneWriting() This method exists to be called by the subclasses.
Author:
Matteo Leonetti (the one to blame)
Definition at line 67 of file rimage_serialization.cpp.
References C8, and RDK2::RGraphics::reduceC8().
RImage * RDK2::RGraphics::RImage::convertTo (Type t) const [virtual]
Convert the image to a different type
Definition at line 31 of file rimage_conversions.cpp.
References C8, GREY, RDK_ERROR_PRINTF, RGB24, RGB32, RImage(), toC8(), toGrey(), toRGB24(), toRGB32(), and type.
Referenced by saveMagick().
RImage * RDK2::RGraphics::RImage::toRGB32 () const [protected, virtual]
Definition at line 52 of file rimage_conversions.cpp.
References buffer, bufferSize, C8, C8Black, C8Blue, C8Cyan, C8Green, C8Grey, C8Magenta, C8Red, C8Unset, C8White, RDK2::RPrimitive::d, GREY, height, RGB24, RGB32, RImage(), type, width, and YUYV.
Referenced by convertTo().
RImage * RDK2::RGraphics::RImage::toRGB24 () const [protected, virtual]
Definition at line 105 of file rimage_conversions.cpp.
References C8, GREY, RGB32, and type.
Referenced by convertTo().
RImage * RDK2::RGraphics::RImage::toGrey () const [protected, virtual]
Definition at line 120 of file rimage_conversions.cpp.
References C8, RGB24, RGB32, and type.
Referenced by convertTo().
RImage * RDK2::RGraphics::RImage::toC8 () const [protected, virtual]
Definition at line 135 of file rimage_conversions.cpp.
References GREY, RGB24, RGB32, and type.
Referenced by convertTo().
bool RDK2::RGraphics::RImage::loadMagick (std::string filename, double occupied = 0.5, double equal = 0.1)
Definition at line 41 of file rimage_magick.cpp.
References buffer, C8, C8Black, C8Blue, C8White, RDK_ERROR_PRINTF, RGB32, setSizeAndType(), type, and width.
bool RDK2::RGraphics::RImage::saveMagick (std::string filename, bool trimImage = false)
Definition at line 92 of file rimage_magick.cpp.
References buffer, convertTo(), getBytesPerPixel(), height, RDK_ERROR_PRINTF, RGB24, RGB32, type, and width.
Field Documentation
size_t RDK2::RGraphics::RImage::width [protected]
Image width
Definition at line 234 of file rimage.h.
Referenced by applyDiff(), canvasResize(), getWidth(), imageResize(), initBuffer(), loadMagick(), operator=(), RImage(), safeGetPixel(), safeSetPixel(), saveMagick(), setSizeAndType(), and toRGB32().
size_t RDK2::RGraphics::RImage::height [protected]
Image height
Definition at line 237 of file rimage.h.
Referenced by canvasResize(), getHeight(), imageResize(), initBuffer(), operator=(), RImage(), safeGetPixel(), safeSetPixel(), saveMagick(), setSizeAndType(), and toRGB32().
Type RDK2::RGraphics::RImage::type [protected]
Image type
Definition at line 240 of file rimage.h.
Referenced by canvasResize(), convertTo(), getType(), imageResize(), initBuffer(), loadMagick(), operator=(), RImage(), saveMagick(), setSizeAndType(), splitInDiffs(), toC8(), toGrey(), toRGB24(), and toRGB32().
size_t RDK2::RGraphics::RImage::bpp [protected]
Bytes per pixel
Definition at line 243 of file rimage.h.
Referenced by canvasResize(), getBytesPerPixel(), getPixel(), imageResize(), initBuffer(), and setPixel().
unsigned char* RDK2::RGraphics::RImage::buffer [protected]
Buffer containing image data
Definition at line 246 of file rimage.h.
Referenced by applyDiff(), canvasResize(), fillBuffer(), getBuffer(), imageResize(), initBuffer(), loadMagick(), operator=(), RImage(), saveMagick(), splitInDiffs(), toRGB32(), and ~RImage().
unsigned char** RDK2::RGraphics::RImage::rows [protected]
Pointers to rows
Definition at line 249 of file rimage.h.
Referenced by canvasResize(), getPixel(), imageResize(), initBuffer(), setPixel(), and ~RImage().
size_t RDK2::RGraphics::RImage::bufferSize [protected]
Buffer size
Definition at line 252 of file rimage.h.
Referenced by fillBuffer(), getBufferSize(), initBuffer(), and toRGB32().
size_t RDK2::RGraphics::RImage::dataSize [protected]
Real data size (for non-compressed format it is the same as buffer size
Definition at line 255 of file rimage.h.
Referenced by getDataSize(), and initBuffer().
The documentation for this class was generated from the following files:
rimage.h
rimage.cpp
rimage_conversions.cpp
rimage_diffs.cpp
rimage_magick.cpp
rimage_serialization.cpp