OpenRDK: RDK2::SensorData::LaserDataTracker Class Reference
RDK2::SensorData::LaserDataTracker Class Reference
#include <laserdatatracker.h>
Detailed Description
Definition at line 30 of file laserdatatracker.h.
Public Member Functions
void reset ()
Resets the object, you need to call update to have a valid object.
void update (const LaserData &laserData, const Point2od &sensorPose)
Updates the laser data structure according with laserData and robotPose.
const LaserData & getLaserData () const
Returns the tracked laser data.
Protected Attributes
LaserData extLaserData
Point2od lastSensorPose
Member Function Documentation
void RDK2::SensorData::LaserDataTracker::reset ()
Resets the object, you need to call update to have a valid object.
Definition at line 27 of file laserdatatracker.cpp.
References extLaserData, and RDK2::SensorData::LaserData::points.
void RDK2::SensorData::LaserDataTracker::update (const LaserData & laserData, const Point2od & sensorPose)
Updates the laser data structure according with laserData and robotPose.
Parameters:
laserData the current laser data.
robotPose the pose of the sensor when laserData has been taken.
Definition at line 32 of file laserdatatracker.cpp.
References RDK2::Geometry::Point2< Numeric >::distTo(), extLaserData, RDK2::RAgent::for(), RDK2::SensorData::LaserData::getNearestIndex(), RDK2::SensorData::LaserData::getRayWidth(), lastSensorPose, RDK2::SensorData::LaserData::maxTheta, RDK2::SensorData::LaserData::minTheta, RDK2::SensorData::LaserData::points, RDK2::Geometry::Point2< Numeric >::rot(), RDK2::Geometry::Point2o< Numeric >::theta, RDK2::Geometry::Point2< Numeric >::thetaWith(), RDK2::SensorData::LaserData::updateThetas(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
const LaserData& RDK2::SensorData::LaserDataTracker::getLaserData () const [inline]
Returns the tracked laser data.
Definition at line 43 of file laserdatatracker.h.
References extLaserData.
Field Documentation
LaserData RDK2::SensorData::LaserDataTracker::extLaserData [protected]
Definition at line 46 of file laserdatatracker.h.
Referenced by getLaserData(), reset(), and update().
Point2od RDK2::SensorData::LaserDataTracker::lastSensorPose [protected]
Definition at line 47 of file laserdatatracker.h.
Referenced by update().
The documentation for this class was generated from the following files:
laserdatatracker.h
laserdatatracker.cpp