OpenRDK: RDK2::Geometry::CircleWalk Class Reference
RDK2::Geometry::CircleWalk Class Reference
#include <walk_circle.h>
Detailed Description
Definition at line 29 of file walk_circle.h.
Public Member Functions
CircleWalk (Point2i c, double ra)
bool next ()
void rewind ()
Point2i getPoint () const
void createCirclePoints ()
Data Fields
std::vector< Point2i > circlePoints
Point2i center
int radius
Constructor & Destructor Documentation
RDK2::Geometry::CircleWalk::CircleWalk (Point2i c, double ra)
Definition at line 24 of file walk_circle.cpp.
References center, createCirclePoints(), and radius.
Member Function Documentation
bool RDK2::Geometry::CircleWalk::next ()
Definition at line 32 of file walk_circle.cpp.
References circlePoints.
void RDK2::Geometry::CircleWalk::rewind ()
Definition at line 37 of file walk_circle.cpp.
References createCirclePoints(), and radius.
Point2i RDK2::Geometry::CircleWalk::getPoint () const
Definition at line 42 of file walk_circle.cpp.
References circlePoints.
void RDK2::Geometry::CircleWalk::createCirclePoints ()
Definition at line 44 of file walk_circle.cpp.
References center, circlePoints, radius, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Referenced by CircleWalk(), and rewind().
Field Documentation
std::vector<Point2i> RDK2::Geometry::CircleWalk::circlePoints
Definition at line 41 of file walk_circle.h.
Referenced by createCirclePoints(), getPoint(), and next().
Point2i RDK2::Geometry::CircleWalk::center
Definition at line 42 of file walk_circle.h.
Referenced by CircleWalk(), and createCirclePoints().
int RDK2::Geometry::CircleWalk::radius
Definition at line 43 of file walk_circle.h.
Referenced by CircleWalk(), createCirclePoints(), and rewind().
The documentation for this class was generated from the following files:
walk_circle.h
walk_circle.cpp