OpenRDK: Logging::StreamSink Class Reference
Logging::StreamSink Class Reference
#include <streamsink.h>
Detailed Description
Definition at line 24 of file streamsink.h.
Public Member Functions
StreamSink (std::ostream *os_, bool usecolor, bool manage=false)
void handle (const LogMessage &)
virtual ~StreamSink ()
Constructor & Destructor Documentation
Logging::StreamSink::StreamSink (std::ostream * os_, bool usecolor, bool manage = false)
Definition at line 29 of file streamsink.cpp.
Logging::StreamSink::~StreamSink () [virtual]
Definition at line 149 of file streamsink.cpp.
Member Function Documentation
void Logging::StreamSink::handle (const LogMessage & l) [virtual]
Implements Logging::LogHandler.
Definition at line 79 of file streamsink.cpp.
References Logging::align(), Logging::Debug, Logging::Error, Logging::Fatal, Logging::LogMessage::file, Logging::Info, Logging::LogMessage::level, Logging::LogMessage::line, Logging::LogMessage::message, Logging::LogMessage::module, Logging::splitString(), Logging::splitStringToSize(), Logging::toString(), and Logging::Trace.
The documentation for this class was generated from the following files:
streamsink.h
streamsink.cpp