OpenRDK: RDK2::RepositoryNS::PropertyDef Class Reference
RDK2::RepositoryNS::PropertyDef Class Reference
#include <property.h>
Detailed Description
Definition at line 67 of file property.h.
Public Member Functions
PropertyDef (int poe=(PERSISTENT|EDITABLE))
Url getLinkTo () const
bool isLink () const
void setLinkTo (CUrl url)
string getDescription () const
void setDescription (cstr s)
string getObjectClassName () const
void setObjectClassName (cstr s) throw (InvalidOperation)
bool isPersistent () const
bool isVolatile () const
bool isKeepThis () const
void setPersistent ()
void setVolatile ()
void setKeepThis ()
string getExternalFileName () const
void setExternalFileName (cstr fileName)
bool isExternalSaved () const
bool isExternalFileBinary () const
bool isExternalFileXml () const
void setExternalFileBinary ()
void setExternalFileXml ()
bool isEditable () const
bool isNotEditable () const
void setEditable ()
void setNotEditable ()
Static Public Member Functions
static bool isClassPersistent (cstr objectClassName)
static bool isClassVolatile (cstr objectClassName)
static bool isClassKeepThis (cstr objectClassName)
Protected Attributes
std::string objectClassName
std::string description
Url linkTo
int persistenceOptions
bool rconsoleEditable
string externalFileName
bool externalFileBinary
Constructor & Destructor Documentation
RDK2::RepositoryNS::PropertyDef::PropertyDef (int poe = (PERSISTENT | EDITABLE)) [inline]
Definition at line 80 of file property.h.
References description, RDK2::RepositoryNS::KEEP_THIS, RDK2::RepositoryNS::NOT_EDITABLE, persistenceOptions, rconsoleEditable, and RDK2::RepositoryNS::VOLATILE.
Member Function Documentation
Url RDK2::RepositoryNS::PropertyDef::getLinkTo () const [inline]
Definition at line 97 of file property.h.
References linkTo.
Referenced by RDK2::RAgent::Module::createModuleConfig().
bool RDK2::RepositoryNS::PropertyDef::isLink () const [inline]
Definition at line 98 of file property.h.
References linkTo.
Referenced by RDK2::RAgent::Module::createModuleConfig().
void RDK2::RepositoryNS::PropertyDef::setLinkTo (CUrl url) [inline]
Definition at line 99 of file property.h.
References linkTo.
Referenced by RDK2::RepositoryNS::Session::linkCreate().
string RDK2::RepositoryNS::PropertyDef::getDescription () const [inline]
Definition at line 102 of file property.h.
References description.
void RDK2::RepositoryNS::PropertyDef::setDescription (cstr s) [inline]
Definition at line 103 of file property.h.
References description.
Referenced by RDK2::RepositoryNS::Repository::addGenericProperty().
string RDK2::RepositoryNS::PropertyDef::getObjectClassName () const
Definition at line 119 of file property.cpp.
References objectClassName.
void RDK2::RepositoryNS::PropertyDef::setObjectClassName (cstr s) throw (InvalidOperation)
Definition at line 85 of file property.cpp.
References RDK2::RepositoryNS::Property::setPersistent().
Referenced by RDK2::RepositoryNS::Property::Property().
bool RDK2::RepositoryNS::PropertyDef::isPersistent () const [inline]
Definition at line 108 of file property.h.
References RDK2::RepositoryNS::KEEP_THIS, persistenceOptions, and RDK2::RepositoryNS::VOLATILE.
Referenced by RDK2::RAgent::Module::createModuleConfig(), RDK2::RAgent::for(), and RDK2::RAgent::Module::initWithModuleConfig().
bool RDK2::RepositoryNS::PropertyDef::isVolatile () const [inline]
Definition at line 109 of file property.h.
References persistenceOptions, and RDK2::RepositoryNS::VOLATILE.
Referenced by RDK2::RAgent::Module::createModuleConfig(), and RDK2::RAgent::Module::initWithModuleConfig().
bool RDK2::RepositoryNS::PropertyDef::isKeepThis () const [inline]
Definition at line 110 of file property.h.
References RDK2::RepositoryNS::KEEP_THIS, and persistenceOptions.
Referenced by RDK2::RAgent::Module::createModuleConfig(), RDK2::RAgent::for(), and RDK2::RAgent::Module::initWithModuleConfig().
void RDK2::RepositoryNS::PropertyDef::setPersistent () [inline]
Definition at line 111 of file property.h.
References RDK2::RepositoryNS::KEEP_THIS, persistenceOptions, and RDK2::RepositoryNS::VOLATILE.
Referenced by RDK2::RepositoryNS::Session::setPersistent().
void RDK2::RepositoryNS::PropertyDef::setVolatile () [inline]
Definition at line 112 of file property.h.
References RDK2::RepositoryNS::KEEP_THIS, persistenceOptions, and RDK2::RepositoryNS::VOLATILE.
Referenced by RDK2::RepositoryNS::Session::setPropertyOptions(), and RDK2::RepositoryNS::Session::setVolatile().
void RDK2::RepositoryNS::PropertyDef::setKeepThis () [inline]
Definition at line 113 of file property.h.
References RDK2::RepositoryNS::KEEP_THIS, persistenceOptions, and RDK2::RepositoryNS::VOLATILE.
Referenced by RDK2::RepositoryNS::Session::setKeepThis().
string RDK2::RepositoryNS::PropertyDef::getExternalFileName () const [inline]
Definition at line 116 of file property.h.
References externalFileName.
void RDK2::RepositoryNS::PropertyDef::setExternalFileName (cstr fileName) [inline]
Definition at line 117 of file property.h.
References externalFileName.
Referenced by RDK2::RepositoryNS::Session::setExternalFileName().
bool RDK2::RepositoryNS::PropertyDef::isExternalSaved () const [inline]
Definition at line 118 of file property.h.
References externalFileName.
bool RDK2::RepositoryNS::PropertyDef::isExternalFileBinary () const [inline]
Definition at line 119 of file property.h.
References externalFileBinary.
bool RDK2::RepositoryNS::PropertyDef::isExternalFileXml () const [inline]
Definition at line 120 of file property.h.
References externalFileBinary.
void RDK2::RepositoryNS::PropertyDef::setExternalFileBinary () [inline]
Definition at line 121 of file property.h.
References externalFileBinary.
Referenced by RDK2::RepositoryNS::Session::setExternalFileBinary().
void RDK2::RepositoryNS::PropertyDef::setExternalFileXml () [inline]
Definition at line 122 of file property.h.
References externalFileBinary.
Referenced by RDK2::RepositoryNS::Session::setExternalFileXml().
bool RDK2::RepositoryNS::PropertyDef::isEditable () const [inline]
Definition at line 125 of file property.h.
References rconsoleEditable.
bool RDK2::RepositoryNS::PropertyDef::isNotEditable () const [inline]
Definition at line 126 of file property.h.
References rconsoleEditable.
void RDK2::RepositoryNS::PropertyDef::setEditable () [inline]
Definition at line 127 of file property.h.
References rconsoleEditable.
Referenced by RDK2::RepositoryNS::Session::setEditable().
void RDK2::RepositoryNS::PropertyDef::setNotEditable () [inline]
Definition at line 128 of file property.h.
References rconsoleEditable.
Referenced by RDK2::RepositoryNS::Session::setNotEditable().
bool RDK2::RepositoryNS::PropertyDef::isClassPersistent (cstr objectClassName) [static]
Definition at line 97 of file property.cpp.
Referenced by isClassVolatile().
bool RDK2::RepositoryNS::PropertyDef::isClassVolatile (cstr objectClassName) [static]
Definition at line 114 of file property.cpp.
References isClassPersistent().
bool RDK2::RepositoryNS::PropertyDef::isClassKeepThis (cstr objectClassName) [static]
Definition at line 109 of file property.cpp.
Field Documentation
std::string RDK2::RepositoryNS::PropertyDef::objectClassName [protected]
Definition at line 69 of file property.h.
Referenced by getObjectClassName().
std::string RDK2::RepositoryNS::PropertyDef::description [protected]
Definition at line 70 of file property.h.
Referenced by getDescription(), PropertyDef(), and setDescription().
Url RDK2::RepositoryNS::PropertyDef::linkTo [protected]
Definition at line 72 of file property.h.
Referenced by getLinkTo(), isLink(), and setLinkTo().
int RDK2::RepositoryNS::PropertyDef::persistenceOptions [protected]
Definition at line 74 of file property.h.
Referenced by isKeepThis(), isPersistent(), isVolatile(), PropertyDef(), setKeepThis(), setPersistent(), and setVolatile().
bool RDK2::RepositoryNS::PropertyDef::rconsoleEditable [protected]
Definition at line 75 of file property.h.
Referenced by isEditable(), isNotEditable(), PropertyDef(), setEditable(), and setNotEditable().
string RDK2::RepositoryNS::PropertyDef::externalFileName [protected]
Definition at line 76 of file property.h.
Referenced by getExternalFileName(), isExternalSaved(), and setExternalFileName().
bool RDK2::RepositoryNS::PropertyDef::externalFileBinary [protected]
Definition at line 77 of file property.h.
Referenced by isExternalFileBinary(), isExternalFileXml(), setExternalFileBinary(), and setExternalFileXml().
The documentation for this class was generated from the following files:
property.h
property.cpp