OpenRDK: RDK2::RNetObjects::RNetMessage Class Reference
RDK2::RNetObjects::RNetMessage Class Reference
#include <rnetmessage.h>
Detailed Description
Contains a message
Author:
Alberto Ingenito (alberto.ing@gmail.com)
Definition at line 40 of file rnetmessage.h.
Public Types
enum Type {
PEER_IDENTIFICATION = 1, PROPERTY_UPDATE = 2, COORDINATION = 3, TEST = 4,
HARDWARE_SERVER = 5, PROPERTY_SUBSCRIPTION = 6, AGENT_CMD = 7, HOTSPOT_MESSAGE = 8,
PROPERTY_TREE = 9, MAPPERDATA = 10, HBD = 11, USER = 999,
USAR_COMSTATION = 12, HARDWARESERVER = HARDWARE_SERVER
}
List of Type of Message (Extensions are coordinated here).
Public Member Functions
RNetMessage ()
Builds an empty RNetMessage.
RNetMessage (const std::string &addressees, const std::string &sender, Type type, Network::NetProtocol socketType, const RDK2::Object *const payload=0)
Build a complete RNetMessage (the payload is NOT cloned and the netmessage now owns it).
virtual ~RNetMessage ()
RNetMessage (const RNetMessage &_message)
Copy constructor.
RNetMessage & operator= (const RNetMessage &_message)
Copy the data inside an RNetMessage.
bool reset ()
Delete the RDK2::Object contained in the message.
void read (Reader *r) throw (RDK2::ReadingException)
void write (Writer *w) const throw (RDK2::WritingException)
RDK2::Object * clone () const
bool equals (const Object *p) const
std::vector< Object * > getTestCases () const
Get a vector of test cases.
const std::string & getAddressees () const
Return the addressees.
const std::string & getSender () const
Return the sender string.
Type getType () const
Get type.
Network::NetProtocol getNetProtocol () const
Get method.
const RDK2::Object * getPayload () const
Get the payload (NOT CLONED).
template<typename T>
const T * getPayloadAs () const
double getDelay () const
Static Public Member Functions
static std::size_t getOverheadSize (const std::string &addressees, const std::string &sender, Type type, Network::NetProtocol socketType)
static std::size_t getBaseHeadSize ()
Data Fields
double timestamp
Member Enumeration Documentation
enum RDK2::RNetObjects::RNetMessage::Type
List of Type of Message (Extensions are coordinated here).
Enumerator:
PEER_IDENTIFICATION Identification message from the peer.
PROPERTY_UPDATE A property update.
COORDINATION Message for coordination tasks.
TEST Message for testing purpose (feel free to use this :D).
HARDWARE_SERVER Message to/from the hardware layer.
PROPERTY_SUBSCRIPTION A property subscription.
AGENT_CMD A command sent to tasks' parseCommand().
HOTSPOT_MESSAGE HotSpot message (RHotSpot with relative pos, with absolute pos,
PROPERTY_TREE or snapshot for the last RHotSpot)
Property tree (with empty objects/values)
MAPPERDATA Message for mapper data (laser,rfid,...).
HBD Message from Human Body Detection module.
USER
USAR_COMSTATION USARSim ComStation message (to and from).
HARDWARESERVER
Definition at line 44 of file rnetmessage.h.
Constructor & Destructor Documentation
RDK2::RNetObjects::RNetMessage::RNetMessage ()
Builds an empty RNetMessage.
Definition at line 155 of file rnetmessage.cpp.
References IN_DEBUG_STREAM.
Referenced by clone(), and getTestCases().
RDK2::RNetObjects::RNetMessage::RNetMessage (const std::string & addressees, const std::string & sender, Type type, Network::NetProtocol socketType, const RDK2::Object *const payload = 0)
Build a complete RNetMessage (the payload is NOT cloned and the netmessage now owns it).
Definition at line 161 of file rnetmessage.cpp.
References OUT_DEBUG_STREAM, and timestamp.
RDK2::RNetObjects::RNetMessage::~RNetMessage () [virtual]
Definition at line 175 of file rnetmessage.cpp.
RDK2::RNetObjects::RNetMessage::RNetMessage (const RNetMessage & _message)
Copy constructor.
Definition at line 129 of file rnetmessage.cpp.
References RDK2::Object::clone(), payload, and timestamp.
Member Function Documentation
RNetMessage & RDK2::RNetObjects::RNetMessage::operator= (const RNetMessage & _message)
Copy the data inside an RNetMessage.
Definition at line 143 of file rnetmessage.cpp.
References addressees, RDK2::Object::clone(), payload, reset(), sender, sender(), socketType, and type.
bool RDK2::RNetObjects::RNetMessage::reset ()
Delete the RDK2::Object contained in the message.
Definition at line 113 of file rnetmessage.cpp.
Referenced by operator=().
void RDK2::RNetObjects::RNetMessage::read (Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 57 of file rnetmessage.cpp.
References RDK2::Statistics::r, and sender().
void RDK2::RNetObjects::RNetMessage::write (Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 68 of file rnetmessage.cpp.
References sender().
RDK2::Object * RDK2::RNetObjects::RNetMessage::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 122 of file rnetmessage.cpp.
References RDK2::Object::clone(), RNetMessage(), and sender().
bool RDK2::RNetObjects::RNetMessage::equals (const Object *) const [virtual]
Compare this and another object.
Note:
For clarity, we decided not to use operator=.
Returns:
true if they are equivalent
Reimplemented from RDK2::Object.
Definition at line 95 of file rnetmessage.cpp.
References addressees, RDK2::Object::equals(), payload, sender, socketType, and type.
std::vector< Object * > RDK2::RNetObjects::RNetMessage::getTestCases () const [virtual]
Get a vector of test cases.
Reimplemented from RDK2::Object.
Definition at line 82 of file rnetmessage.cpp.
References addressees, payload, PEER_IDENTIFICATION, RNetMessage(), sender, socketType, Network::TCP_IP, and type.
std::size_t RDK2::RNetObjects::RNetMessage::getOverheadSize (const std::string & addressees, const std::string & sender, Type type, Network::NetProtocol socketType) [static]
Definition at line 214 of file rnetmessage.cpp.
References RDK2::RNetObjects::charcount(), and getBaseHeadSize().
std::size_t RDK2::RNetObjects::RNetMessage::getBaseHeadSize () [static]
Definition at line 220 of file rnetmessage.cpp.
References RDK_DEBUG_STREAM.
Referenced by getOverheadSize().
const std::string & RDK2::RNetObjects::RNetMessage::getAddressees () const
Return the addressees.
Definition at line 184 of file rnetmessage.cpp.
const std::string & RDK2::RNetObjects::RNetMessage::getSender () const
Return the sender string.
Definition at line 189 of file rnetmessage.cpp.
References IN_DEBUG_STREAM, and sender().
RNetMessage::Type RDK2::RNetObjects::RNetMessage::getType () const
Get type.
Definition at line 195 of file rnetmessage.cpp.
Referenced by RDK2::RNetObjects::MessageWithTypeQueueFilter::areYouInterested(), RDK2::RepositoryNS::RemotePropertyManager::RemotePropertyManagerInterests::areYouInterested(), and RDK2::RepositoryNS::RemotePropertyManager::receiver().
Network::NetProtocol RDK2::RNetObjects::RNetMessage::getNetProtocol () const
Get method.
Definition at line 200 of file rnetmessage.cpp.
const RDK2::Object * RDK2::RNetObjects::RNetMessage::getPayload () const
Get the payload (NOT CLONED).
Definition at line 205 of file rnetmessage.cpp.
Referenced by getPayloadAs().
template<typename T> const T* RDK2::RNetObjects::RNetMessage::getPayloadAs () const [inline]
Definition at line 113 of file rnetmessage.h.
References getPayload().
double RDK2::RNetObjects::RNetMessage::getDelay () const
Definition at line 107 of file rnetmessage.cpp.
References timestamp.
Field Documentation
double RDK2::RNetObjects::RNetMessage::timestamp
Definition at line 117 of file rnetmessage.h.
Referenced by getDelay(), and RNetMessage().
The documentation for this class was generated from the following files:
rnetmessage.h
rnetmessage.cpp