OpenRDK: RDK2::TextUtils::LineStream Class Reference
RDK2::TextUtils::LineStream Class Reference
#include <linestream.h>
Detailed Description
This class allows to read a text file, line by line, without seeing lines beginnings with a comment character (ex: "#").
Definition at line 35 of file linestream.h.
Public Member Functions
LineStream (std::istream &i, char commentChar= '#')
LineStream (std::istream *i, char commentChar= '#')
bool readLine ()
const std::string & getLine ()
const std::string & getLastComment ()
StringVector tokenize ()
Constructor & Destructor Documentation
RDK2::TextUtils::LineStream::LineStream (std::istream & i, char commentChar = '#')
Definition at line 27 of file linestream.cpp.
RDK2::TextUtils::LineStream::LineStream (std::istream * i, char commentChar = '#')
Definition at line 30 of file linestream.cpp.
Member Function Documentation
bool RDK2::TextUtils::LineStream::readLine ()
Returns false if stream fail()s.
Definition at line 33 of file linestream.cpp.
Referenced by RDK2::SensorData::LogReader::getNext().
const std::string& RDK2::TextUtils::LineStream::getLine () [inline]
Returns last line read.
Definition at line 44 of file linestream.h.
Referenced by RDK2::SensorData::LogReader::getNext(), and tokenize().
const std::string& RDK2::TextUtils::LineStream::getLastComment () [inline]
Returns last comment read.
Definition at line 47 of file linestream.h.
vector< string > RDK2::TextUtils::LineStream::tokenize ()
Returns a istream to a istringstream of last line. Tokenizes last line
Definition at line 60 of file linestream.cpp.
References getLine(), and RDK2::TextUtils::tokenize().
The documentation for this class was generated from the following files:
linestream.h
linestream.cpp