OpenRDK: RDK2::RepositoryNS::Property Class Reference
RDK2::RepositoryNS::Property Class Reference
#include <property.h>
Detailed Description
Definition at line 136 of file property.h.
Public Member Functions
PropertyDef getPropertyDef ()
PropertyDef getDefaultPropertyDef ()
void saveDefaultPropertyDef ()
Property (Url url, cstr objectClass, RDK2::Object *defaultObject=0)
virtual ~Property ()
void setObject (RDK2::Object *object) throw (WrongType)
void setObjectL (RDK2::Object *object) throw (WrongType)
RDK2::Object * getObjectL ()
const RDK2::Object * getObjectLC ()
template<typename T>
T * getObjectAsL () throw (WrongType, ValueNotSet)
template<typename T>
const T * getObjectAsLC () throw (WrongType, ValueNotSet)
bool isQueue ()
bool isStorage ()
bool isReadonly ()
void setReadonly (bool readonly)
bool isPersistent ()
void setPersistent (bool persistent)
bool isEnum ()
bool isLink ()
void setObjectClassName (cstr objectClass)
string getObjectClassName () const
template<typename T>
const T * getObjectAsLC () throw (ValueNotSet, WrongType)
template<typename T>
T * getObjectAsL () throw (ValueNotSet, WrongType)
Data Fields
RDK2::Object * object
const RDK2::Object * defaultObject
Url url
PropertyDef def
PropertyDef defaultDef
std::string description
PropertyOptions options
bool isEnumB
Valid when property is an Enum.
vector< PropertyEnumItem > enumItems
bool isLinkB
Valid when property is a link.
Url linkTo
bool deleted
bool savedExternally
Valid when property has to be saved externally.
string externalFilename
RDK2::RPrimitive::RDouble::Unit defaultDoubleUnit
Valid when property is a double.
RObjectPipeQueue diffsQueue
Stuff for people listening to this property's diffs.
set< Session * > listeningSessions
Protected Attributes
std::string objectClass
Friends
class Repository
class Session
Constructor & Destructor Documentation
RDK2::RepositoryNS::Property::Property (Url url, cstr objectClass, RDK2::Object * defaultObject = 0) [inline]
Definition at line 180 of file property.h.
References def, and RDK2::RepositoryNS::PropertyDef::setObjectClassName().
RDK2::RepositoryNS::Property::~Property () [virtual]
Definition at line 26 of file property.cpp.
Member Function Documentation
PropertyDef RDK2::RepositoryNS::Property::getPropertyDef () [inline]
Definition at line 154 of file property.h.
References def.
Referenced by RDK2::RepositoryNS::Session::getPropertyDef().
PropertyDef RDK2::RepositoryNS::Property::getDefaultPropertyDef () [inline]
Definition at line 155 of file property.h.
References defaultDef.
Referenced by RDK2::RepositoryNS::Session::getDefaultPropertyDef().
void RDK2::RepositoryNS::Property::saveDefaultPropertyDef () [inline]
Definition at line 156 of file property.h.
References def, and defaultDef.
void RDK2::RepositoryNS::Property::setObject (RDK2::Object * object) throw (WrongType)
Definition at line 53 of file property.cpp.
References PosixConstructs::PosixMutex::lock(), setObjectL(), PosixConstructs::PosixMutex::unlock(), and WHERE.
Referenced by RDK2::RepositoryNS::Session::queueCreate(), and RDK2::RepositoryNS::Repository::Repository().
void RDK2::RepositoryNS::Property::setObjectL (RDK2::Object * object) throw (WrongType)
Definition at line 59 of file property.cpp.
References RDK2::Demangle::Reflective::getClassName(), object, objectClass, and setObjectClassName().
Referenced by RDK2::RepositoryNS::Repository::getObjectOrCreateItL(), RDK2::RepositoryNS::Repository::setObject(), and setObject().
RDK2::Object * RDK2::RepositoryNS::Property::getObjectL ()
Definition at line 48 of file property.cpp.
References RDK2::Object::clone(), and defaultObject.
Referenced by getObjectAsL(), RDK2::RepositoryNS::Session::getObjectClone(), RDK2::RepositoryNS::Session::getObjectL(), RDK2::RepositoryNS::Repository::getObjectL(), RDK2::RepositoryNS::Repository::getObjectOrCreateItL(), RDK2::RepositoryNS::Session::getValue(), and RDK2::RepositoryNS::Session::haveSameObject().
const RDK2::Object * RDK2::RepositoryNS::Property::getObjectLC ()
Definition at line 44 of file property.cpp.
References defaultObject.
Referenced by getObjectAsLC(), RDK2::RepositoryNS::Session::getObjectLC(), and RDK2::RepositoryNS::Repository::getObjectLC().
template<typename T> T * RDK2::RepositoryNS::Property::getObjectAsL () throw (WrongType, ValueNotSet) [inline]
Definition at line 238 of file property.h.
Referenced by RDK2::RepositoryNS::Repository::getObjectAsL(), RDK2::RepositoryNS::Session::listenToQueue(), RDK2::RepositoryNS::Session::queueGetSubscription(), RDK2::RepositoryNS::Session::queueSetInterests(), RDK2::RepositoryNS::Session::queueUnsubscribe(), and RDK2::RepositoryNS::Session::unlistenToQueue().
template<typename T> const T * RDK2::RepositoryNS::Property::getObjectAsLC () throw (WrongType, ValueNotSet) [inline]
Definition at line 225 of file property.h.
Referenced by RDK2::RepositoryNS::Session::getEnumString(), RDK2::RepositoryNS::Repository::getObjectAsLC(), and RDK2::RepositoryNS::Session::getValue().
bool RDK2::RepositoryNS::Property::isQueue ()
Definition at line 33 of file property.cpp.
References objectClass, and QUEUE_CLASSNAME.
Referenced by RDK2::RepositoryNS::Session::listen(), RDK2::RepositoryNS::Session::queuePush(), RDK2::RepositoryNS::Repository::queuePush(), RDK2::RepositoryNS::Session::queueSize(), and RDK2::RepositoryNS::Session::unlisten().
bool RDK2::RepositoryNS::Property::isStorage ()
Definition at line 34 of file property.cpp.
References objectClass, and QUEUE_CLASSNAME.
Referenced by RDK2::RepositoryNS::Repository::pushDiffInDiffQueue(), and RDK2::RepositoryNS::Repository::setObject().
bool RDK2::RepositoryNS::Property::isReadonly ()
Definition at line 35 of file property.cpp.
References options, and RDK2::RepositoryNS::READ_ONLY.
Referenced by RDK2::RepositoryNS::Session::isReadonly().
void RDK2::RepositoryNS::Property::setReadonly (bool readonly)
Definition at line 36 of file property.cpp.
References HERE, PosixConstructs::PosixMutex::lock(), RDK2::RepositoryNS::READ_ONLY, SET_OPTION, and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::Repository::Repository(), and RDK2::RepositoryNS::Session::setReadonly().
bool RDK2::RepositoryNS::Property::isPersistent ()
Definition at line 38 of file property.cpp.
References RDK2::RepositoryNS::NOT_PERSISTENT, and options.
Referenced by RDK2::RepositoryNS::Session::isPersistent().
void RDK2::RepositoryNS::Property::setPersistent (bool persistent)
Definition at line 39 of file property.cpp.
References HERE, PosixConstructs::PosixMutex::lock(), RDK2::RepositoryNS::NOT_PERSISTENT, SET_OPTION, and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::Repository::Repository(), and RDK2::RepositoryNS::PropertyDef::setObjectClassName().
bool RDK2::RepositoryNS::Property::isEnum ()
Definition at line 41 of file property.cpp.
References isEnumB.
bool RDK2::RepositoryNS::Property::isLink ()
Definition at line 42 of file property.cpp.
References isLinkB.
Referenced by RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Repository::getProperty(), RDK2::RepositoryNS::Session::getPropertyLinkTo(), and RDK2::RepositoryNS::Session::lockAndGetProperty().
void RDK2::RepositoryNS::Property::setObjectClassName (cstr objectClass)
Definition at line 76 of file property.cpp.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), RDK2::RepositoryNS::Session::queuePush(), RDK2::RepositoryNS::Repository::queuePush(), RDK2::RepositoryNS::Session::queueSize(), and setObjectL().
string RDK2::RepositoryNS::Property::getObjectClassName () const
FIXME: referenza circolare: rforeignproperties ha rpropertydef che deriva da Property, quindi il link non puo riuscire workaround: mettere questa funzione nel .h
Definition at line 81 of file property.cpp.
References objectClass.
Referenced by RDK2::RepositoryNS::Repository::getObjectOrCreateItL(), RDK2::RepositoryNS::Session::getPropertyClassName(), RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), RDK2::RepositoryNS::Session::queuePush(), RDK2::RepositoryNS::Repository::queuePush(), RDK2::RepositoryNS::Session::queueSize(), RDK2::RepositoryNS::Repository::sendStorageValueToHost(), and RDK2::RepositoryNS::Repository::setRemotePropertyDef().
template<typename T> const T* RDK2::RepositoryNS::Property::getObjectAsLC () throw (ValueNotSet, WrongType) [inline]
Definition at line 2 of file property.hpp.
References RDK2::Demangle::Reflective::getClassName(), and getObjectLC().
template<typename T> T* RDK2::RepositoryNS::Property::getObjectAsL () throw (ValueNotSet, WrongType) [inline]
Definition at line 15 of file property.hpp.
References RDK2::Demangle::Reflective::getClassName(), and getObjectL().
Friends And Related Function Documentation
friend class Repository [friend]
Definition at line 220 of file property.h.
friend class Session [friend]
Definition at line 221 of file property.h.
Field Documentation
std::string RDK2::RepositoryNS::Property::objectClass [protected]
Definition at line 138 of file property.h.
Referenced by getObjectClassName(), isQueue(), isStorage(), and setObjectL().
RDK2::Object* RDK2::RepositoryNS::Property::object
Definition at line 140 of file property.h.
Referenced by RDK2::RepositoryNS::Session::isSet(), RDK2::RepositoryNS::Session::linkCreate(), and setObjectL().
const RDK2::Object* RDK2::RepositoryNS::Property::defaultObject
Definition at line 141 of file property.h.
Referenced by getObjectL(), and getObjectLC().
Url RDK2::RepositoryNS::Property::url
Definition at line 142 of file property.h.
Referenced by RDK2::RepositoryNS::Session::queuePush(), RDK2::RepositoryNS::Repository::queuePush(), and RDK2::RepositoryNS::Session::unlockProperty().
PropertyDef RDK2::RepositoryNS::Property::def
this is the current definition of this property
Definition at line 145 of file property.h.
Referenced by RDK2::RepositoryNS::Repository::addGenericProperty(), getPropertyDef(), RDK2::RepositoryNS::Session::linkCreate(), Property(), saveDefaultPropertyDef(), RDK2::RepositoryNS::Session::setEditable(), RDK2::RepositoryNS::Session::setExternalFileBinary(), RDK2::RepositoryNS::Session::setExternalFileName(), RDK2::RepositoryNS::Session::setExternalFileXml(), RDK2::RepositoryNS::Session::setKeepThis(), RDK2::RepositoryNS::Session::setNotEditable(), RDK2::RepositoryNS::Session::setPersistent(), RDK2::RepositoryNS::Session::setPropertyOptions(), and RDK2::RepositoryNS::Session::setVolatile().
PropertyDef RDK2::RepositoryNS::Property::defaultDef
this is the default definition of this property, decided in initConfigurationProperties
Definition at line 148 of file property.h.
Referenced by getDefaultPropertyDef(), and saveDefaultPropertyDef().
std::string RDK2::RepositoryNS::Property::description
Definition at line 150 of file property.h.
Referenced by RDK2::RepositoryNS::Repository::addGenericProperty(), and RDK2::RepositoryNS::Session::getPropertyDescription().
PropertyOptions RDK2::RepositoryNS::Property::options
Definition at line 152 of file property.h.
Referenced by isPersistent(), isReadonly(), and RDK2::RepositoryNS::Session::setPropertyOptions().
bool RDK2::RepositoryNS::Property::isEnumB
Valid when property is an Enum.
Definition at line 159 of file property.h.
Referenced by RDK2::RepositoryNS::Session::createEnum(), and isEnum().
vector<PropertyEnumItem> RDK2::RepositoryNS::Property::enumItems
Definition at line 160 of file property.h.
Referenced by RDK2::RepositoryNS::Session::createEnum(), RDK2::RepositoryNS::Session::getEnumString(), and RDK2::RepositoryNS::Session::getPropertyEnumItems().
bool RDK2::RepositoryNS::Property::isLinkB
Valid when property is a link.
Definition at line 163 of file property.h.
Referenced by isLink(), and RDK2::RepositoryNS::Session::linkCreate().
Url RDK2::RepositoryNS::Property::linkTo
Definition at line 164 of file property.h.
Referenced by RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Repository::getProperty(), RDK2::RepositoryNS::Session::getPropertyLinkTo(), RDK2::RepositoryNS::Session::linkCreate(), and RDK2::RepositoryNS::Session::lockAndGetProperty().
bool RDK2::RepositoryNS::Property::deleted
Definition at line 166 of file property.h.
Referenced by RDK2::RepositoryNS::Session::getProperty(), and RDK2::RepositoryNS::Repository::getProperty().
bool RDK2::RepositoryNS::Property::savedExternally
Valid when property has to be saved externally.
Definition at line 169 of file property.h.
Referenced by RDK2::RepositoryNS::Session::textConfigLineForProperty().
string RDK2::RepositoryNS::Property::externalFilename
Definition at line 170 of file property.h.
Referenced by RDK2::RepositoryNS::Session::textConfigLineForProperty().
RDK2::RPrimitive::RDouble::Unit RDK2::RepositoryNS::Property::defaultDoubleUnit
Valid when property is a double.
Definition at line 173 of file property.h.
RObjectPipeQueue RDK2::RepositoryNS::Property::diffsQueue
Stuff for people listening to this property's diffs.
Definition at line 176 of file property.h.
Referenced by RDK2::RepositoryNS::Repository::pushDiffInDiffQueue(), RDK2::RepositoryNS::Session::storageSubscribeDiffs(), and RDK2::RepositoryNS::Session::storageUnsubscribeDiffs().
set<Session*> RDK2::RepositoryNS::Property::listeningSessions
Definition at line 177 of file property.h.
Referenced by RDK2::RepositoryNS::Session::listen(), RDK2::RepositoryNS::Session::unlisten(), and RDK2::RepositoryNS::Repository::wakeUpListeningSessions().
The documentation for this class was generated from the following files:
property.h
property.cpp
property.hpp