OpenRDK: RDK2::RepositoryNS::TcpManager Class Reference
RDK2::RepositoryNS::TcpManager Class Reference
#include <tcpmanager.h>
Detailed Description
Definition at line 41 of file tcpmanager.h.
Public Member Functions
TcpManager (Repository *repository)
~TcpManager ()
bool init ()
bool start ()
bool tryConnectTo (const string &peerName, time_t timeout=(time_t) 0)
Network::ConnectionStatus getConnectionStatusWith (const string &peerName)
Data Structures
class PeerManager
Constructor & Destructor Documentation
RDK2::RepositoryNS::TcpManager::TcpManager (Repository * repository)
Definition at line 49 of file tcpmanager.cpp.
RDK2::RepositoryNS::TcpManager::~TcpManager ()
Definition at line 207 of file tcpmanager.cpp.
References RDK_INFO_PRINTF, Network::TCPServerSocket::unbind(), and RDK2::RepositoryNS::Session::wakeUp().
Member Function Documentation
bool RDK2::RepositoryNS::TcpManager::init ()
Definition at line 54 of file tcpmanager.cpp.
References Network::TCPServerSocket::bind(), RDK2::RepositoryNS::Repository::createSession(), RDK2::RepositoryNS::Session::end(), Network::NetException::fullwhat(), RDK2::RepositoryNS::Session::getObjectAsL(), Network::InetAddress::getPort(), RDK2::RepositoryNS::Session::getRepositoryName(), RDK2::RNetObjects::RYellowPages::getSocketAddress(), RDK2::RepositoryNS::Session::lock(), PROPERTY_TCP_LISTENING_PORT, PROPERTY_YELLOWPAGES, RDK_ERROR_PRINTF, RDK_ERROR_STREAM, RDK2::RepositoryNS::Session::setIntB(), RDK2::RepositoryNS::Session::start(), Network::TCP_IP, RDK2::RepositoryNS::Session::terminate(), RDK2::RepositoryNS::Session::unlock(), and WHERE.
Referenced by RDK2::RepositoryNS::Repository::startRepositoryThreads().
bool RDK2::RepositoryNS::TcpManager::start ()
Definition at line 106 of file tcpmanager.cpp.
References RDK2::Common::createThread().
Referenced by RDK2::RepositoryNS::Repository::startRepositoryThreads().
bool RDK2::RepositoryNS::TcpManager::tryConnectTo (const string & peerName, time_t timeout = (time_t) 0)
Definition at line 234 of file tcpmanager.cpp.
References DOUT, RDK2::RepositoryNS::Repository::getRepositoryName(), RDK_DEBUG_PRINTF, and RDK_ERROR_STREAM.
Referenced by RDK2::RepositoryNS::Session::tryConnectTo().
Network::ConnectionStatus RDK2::RepositoryNS::TcpManager::getConnectionStatusWith (const string & peerName)
Definition at line 270 of file tcpmanager.cpp.
References Network::NOT_CONNECTED.
Referenced by RDK2::RepositoryNS::Session::getConnectionStatusWith().
The documentation for this class was generated from the following files:
tcpmanager.h
tcpmanager.cpp