OpenRDK: Network::TCPServerSocket Class Reference
Network::TCPServerSocket Class Reference
#include <tcpserversocket.h>
Detailed Description
Definition at line 30 of file tcpserversocket.h.
Public Member Functions
TCPServerSocket () throw ()
TCPServerSocket (unsigned short port, unsigned short backlog=10) throw (TCPException, NetException)
TCPServerSocket (const InetAddress &address, unsigned short backlog=10) throw (TCPException)
~TCPServerSocket () throw ()
void unbind () throw ()
void rebind () throw (TCPException)
void bind (unsigned short port, unsigned short backlog=10) throw (TCPException, NetException)
void bind (const InetAddress &address, unsigned short backlog=10) throw (TCPException)
TCPSocket * accept () throw (TCPException)
const InetAddress & getAddress ()
Constructor & Destructor Documentation
Network::TCPServerSocket::TCPServerSocket () throw ()
Definition at line 30 of file tcpserversocket.cpp.
Network::TCPServerSocket::TCPServerSocket (unsigned short port, unsigned short backlog = 10) throw (TCPException, NetException)
Definition at line 34 of file tcpserversocket.cpp.
Network::TCPServerSocket::TCPServerSocket (const InetAddress & address, unsigned short backlog = 10) throw (TCPException)
Definition at line 42 of file tcpserversocket.cpp.
Network::TCPServerSocket::~TCPServerSocket () throw ()
Definition at line 48 of file tcpserversocket.cpp.
References unbind().
Member Function Documentation
void Network::TCPServerSocket::unbind () throw ()
Definition at line 52 of file tcpserversocket.cpp.
Referenced by bind(), rebind(), RDK2::RepositoryNS::TcpManager::~TcpManager(), and ~TCPServerSocket().
void Network::TCPServerSocket::rebind () throw (TCPException) [inline]
Definition at line 39 of file tcpserversocket.h.
References bind(), and unbind().
void Network::TCPServerSocket::bind (unsigned short port, unsigned short backlog = 10) throw (TCPException, NetException)
Definition at line 60 of file tcpserversocket.cpp.
References bind(), and unbind().
Referenced by bind(), RDK2::RepositoryNS::TcpManager::init(), and rebind().
void Network::TCPServerSocket::bind (const InetAddress & address, unsigned short backlog = 10) throw (TCPException)
Definition at line 71 of file tcpserversocket.cpp.
References bind(), and unbind().
TCPSocket * Network::TCPServerSocket::accept () throw (TCPException)
Definition at line 82 of file tcpserversocket.cpp.
References Network::InetAddress::getAddress().
Referenced by main().
const InetAddress& Network::TCPServerSocket::getAddress () [inline]
Definition at line 45 of file tcpserversocket.h.
The documentation for this class was generated from the following files:
tcpserversocket.h
tcpserversocket.cpp