OpenRDK: RDK2::TextUtils::KaGetOpt Class Reference
RDK2::TextUtils::KaGetOpt Class Reference
#include <kagetopt.h>
Detailed Description
Definition at line 18 of file kagetopt.h.
Public Member Functions
KaGetOpt ()
*structors
void optionString (const string &option, const string &description)
params declaration
void optionString (const string &option, const string &description, const string &defaultValue)
void optionInt (const string &option, const string &description)
void optionInt (const string &option, const string &description, int defaultValue)
void optionDouble (const string &option, const string &description)
void optionDouble (const string &option, const string &description, double defaultValue)
void optionBool (const string &option, const string &description)
void optionBool (const string &option, const string &description, bool defaultValue)
bool bind (const string &option, string &s)
automatic variable binding during parseArgs
bool bind (const string &option, int &i)
bool bind (const string &option, double &d)
bool bind (const string &option, bool &b)
bool bindParam (const string &option, const string &description, string &s, const string &defaultValue)
params declaration and bind
bool bindParam (const string &option, const string &description, string &s)
bool bindParam (const string &option, const string &description, int &i, int defaultValue)
bool bindParam (const string &option, const string &description, int &i)
bool bindParam (const string &option, const string &description, double &d, double defaultValue)
bool bindParam (const string &option, const string &description, double &d)
bool bindParam (const string &option, const string &description, bool &b, bool defaultValue)
bool bindParam (const string &option, const string &description, bool &b)
bool parseArgs (int argc, char **argv)
string getStrippedArgs ()
returns the string without parameters
string getHelp ()
returns help message
string getLastError ()
returns the string explaining the last error occurred
bool getString (const string &option, string &value)
gets option values
bool getInt (const string &option, int &value)
bool getDouble (const string &option, double &value)
bool getBool (const string &option, bool &value)
Data Structures
struct Option
Constructor & Destructor Documentation
RDK2::TextUtils::KaGetOpt::KaGetOpt () [inline]
*structors
Definition at line 21 of file kagetopt.h.
Member Function Documentation
void RDK2::TextUtils::KaGetOpt::optionString (const string & option, const string & description)
params declaration
Definition at line 49 of file kagetopt.cpp.
Referenced by bindParam().
void RDK2::TextUtils::KaGetOpt::optionString (const string & option, const string & description, const string & defaultValue)
Definition at line 54 of file kagetopt.cpp.
void RDK2::TextUtils::KaGetOpt::optionInt (const string & option, const string & description)
Definition at line 59 of file kagetopt.cpp.
Referenced by bindParam().
void RDK2::TextUtils::KaGetOpt::optionInt (const string & option, const string & description, int defaultValue)
Definition at line 64 of file kagetopt.cpp.
References RDK2::TextUtils::toString().
void RDK2::TextUtils::KaGetOpt::optionDouble (const string & option, const string & description)
Definition at line 69 of file kagetopt.cpp.
Referenced by bindParam().
void RDK2::TextUtils::KaGetOpt::optionDouble (const string & option, const string & description, double defaultValue)
Definition at line 74 of file kagetopt.cpp.
References RDK2::TextUtils::toString().
void RDK2::TextUtils::KaGetOpt::optionBool (const string & option, const string & description)
Definition at line 79 of file kagetopt.cpp.
Referenced by bindParam().
void RDK2::TextUtils::KaGetOpt::optionBool (const string & option, const string & description, bool defaultValue)
Definition at line 84 of file kagetopt.cpp.
References RDK2::TextUtils::toString().
bool RDK2::TextUtils::KaGetOpt::bind (const string & option, string & s)
automatic variable binding during parseArgs
Definition at line 145 of file kagetopt.cpp.
Referenced by bindParam().
bool RDK2::TextUtils::KaGetOpt::bind (const string & option, int & i)
Definition at line 155 of file kagetopt.cpp.
bool RDK2::TextUtils::KaGetOpt::bind (const string & option, double & d)
Definition at line 165 of file kagetopt.cpp.
bool RDK2::TextUtils::KaGetOpt::bind (const string & option, bool & b)
Definition at line 175 of file kagetopt.cpp.
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, string & s, const string & defaultValue) [inline]
params declaration and bind
Definition at line 40 of file kagetopt.h.
References bind(), and optionString().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, string & s) [inline]
Definition at line 41 of file kagetopt.h.
References bind(), and optionString().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, int & i, int defaultValue) [inline]
Definition at line 42 of file kagetopt.h.
References bind(), and optionInt().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, int & i) [inline]
Definition at line 43 of file kagetopt.h.
References bind(), and optionInt().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, double & d, double defaultValue) [inline]
Definition at line 44 of file kagetopt.h.
References bind(), and optionDouble().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, double & d) [inline]
Definition at line 45 of file kagetopt.h.
References bind(), and optionDouble().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, bool & b, bool defaultValue) [inline]
Definition at line 46 of file kagetopt.h.
References bind(), and optionBool().
bool RDK2::TextUtils::KaGetOpt::bindParam (const string & option, const string & description, bool & b) [inline]
Definition at line 47 of file kagetopt.h.
References bind(), and optionBool().
bool RDK2::TextUtils::KaGetOpt::parseArgs (int argc, char ** argv)
Definition at line 185 of file kagetopt.cpp.
string RDK2::TextUtils::KaGetOpt::getStrippedArgs () [inline]
returns the string without parameters
Definition at line 53 of file kagetopt.h.
string RDK2::TextUtils::KaGetOpt::getHelp ()
returns help message
Definition at line 89 of file kagetopt.cpp.
string RDK2::TextUtils::KaGetOpt::getLastError () [inline]
returns the string explaining the last error occurred
Definition at line 59 of file kagetopt.h.
bool RDK2::TextUtils::KaGetOpt::getString (const string & option, string & value)
gets option values
Definition at line 239 of file kagetopt.cpp.
bool RDK2::TextUtils::KaGetOpt::getInt (const string & option, int & value)
Definition at line 244 of file kagetopt.cpp.
bool RDK2::TextUtils::KaGetOpt::getDouble (const string & option, double & value)
Definition at line 252 of file kagetopt.cpp.
bool RDK2::TextUtils::KaGetOpt::getBool (const string & option, bool & value)
Definition at line 260 of file kagetopt.cpp.
The documentation for this class was generated from the following files:
kagetopt.h
kagetopt.cpp