OpenRDK: RDK2::RepositoryNS::UdpManager Class Reference
RDK2::RepositoryNS::UdpManager Class Reference
#include <udpmanager.h>
Detailed Description
Definition at line 33 of file udpmanager.h.
Public Member Functions
UdpManager (Repository *repository)
~UdpManager ()
bool init ()
bool start ()
Data Structures
class UdpSenderInterests
Constructor & Destructor Documentation
RDK2::RepositoryNS::UdpManager::UdpManager (Repository * repository)
Definition at line 46 of file udpmanager.cpp.
RDK2::RepositoryNS::UdpManager::~UdpManager ()
Definition at line 246 of file udpmanager.cpp.
References Network::UDPSocket::ALL, RDK_INFO_PRINTF, Network::UDPSocket::shutdown(), and RDK2::RepositoryNS::Session::wakeUp().
Member Function Documentation
bool RDK2::RepositoryNS::UdpManager::init ()
Definition at line 50 of file udpmanager.cpp.
References Network::UDPSocket::bind(), RDK2::RepositoryNS::Repository::createSession(), RDK2::RepositoryNS::Session::end(), Network::NetException::fullwhat(), RDK2::RepositoryNS::Session::getObjectAsL(), Network::InetAddress::getPort(), RDK2::RepositoryNS::Session::getRepositoryName(), RDK2::RNetObjects::RYellowPages::getSocketAddress(), RDK2::RepositoryNS::Session::lock(), PROPERTY_UDP_PORT, PROPERTY_YELLOWPAGES, RDK_ERROR_PRINTF, RDK_ERROR_STREAM, RDK_INFO_PRINTF, RDK2::RepositoryNS::Session::setIntB(), RDK2::RepositoryNS::Session::start(), RDK2::RepositoryNS::Session::terminate(), Network::UDP_IP, RDK2::RepositoryNS::Session::unlock(), and WHERE.
Referenced by RDK2::RepositoryNS::Repository::startRepositoryThreads().
bool RDK2::RepositoryNS::UdpManager::start ()
Definition at line 96 of file udpmanager.cpp.
References RDK2::Common::createThread().
Referenced by RDK2::RepositoryNS::Repository::startRepositoryThreads().
The documentation for this class was generated from the following files:
udpmanager.h
udpmanager.cpp