OpenRDK: RDK2::RepositoryNS::Url Class Reference
RDK2::RepositoryNS::Url Class Reference
#include <url.h>
Detailed Description
Definition at line 66 of file url.h.
Public Member Functions
Url (const string &urlString) throw (MalformedUrlException)
Url (const char *) throw (MalformedUrlException)
Url & operator= (const Url &url) throw (MalformedUrlException)
Url contextualize (const string &context) const throw (MalformedUrlException)
Url decontextualize (const string &context) const throw (MalformedUrlException)
string getHost () const
Returns the host of the url, if it is complete; otherwise it returns "".
string getPath () const
Url getRelativeUrl (unsigned int partsToSkip) const
If the url is absolute or complete, strips the protocol and host part and.
bool startsWith (const string &prefix) const
Returns true if this url begins with.
bool isComplete () const
Url is complete when it has also the host part (i.e. it begins with "rdk://").
bool isRelative () const
Url is relative if it isn't complete and doesn't begin with a "/".
bool isAbsolute () const
Url is absolute if it isn't complete and begins with a "/".
int getLevel () const
Constructor & Destructor Documentation
RDK2::RepositoryNS::Url::Url (const string & urlString) throw (MalformedUrlException)
Definition at line 44 of file url.cpp.
RDK2::RepositoryNS::Url::Url (const char * urlString) throw (MalformedUrlException)
Definition at line 50 of file url.cpp.
Member Function Documentation
Url & RDK2::RepositoryNS::Url::operator= (const Url & url) throw (MalformedUrlException)
Definition at line 56 of file url.cpp.
References RDK2::Geometry::normalize().
Url RDK2::RepositoryNS::Url::contextualize (const string & context) const throw (MalformedUrlException)
Returns the url contextualized in the
Parameters:
context ; if this url is complete, return this url itself, regardless of the context
context the context
Definition at line 63 of file url.cpp.
References DOUT, RDK2::Geometry::normalize(), and RDK2::TextUtils::tokenize().
Referenced by RDK2::RepositoryNS::Session::getAbsoluteUrl().
Url RDK2::RepositoryNS::Url::decontextualize (const string & context) const throw (MalformedUrlException)
string RDK2::RepositoryNS::Url::getHost () const
Returns the host of the url, if it is complete; otherwise it returns "".
Definition at line 104 of file url.cpp.
References isComplete().
Referenced by RDK2::RepositoryNS::Repository::getLocalProperty(), getPath(), RDK2::RepositoryNS::RemotePropertyManager::manageSubscriptionMessage(), and RDK2::RepositoryNS::Repository::queuePush().
string RDK2::RepositoryNS::Url::getPath () const
If the url is complete, returns the corresponding absolute url (without the host part), otherwise it returns the url unchanged
Definition at line 110 of file url.cpp.
References getHost(), and isComplete().
Referenced by RDK2::RepositoryNS::Repository::getLocalProperty(), RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Repository::getProperty(), and getRelativeUrl().
Url RDK2::RepositoryNS::Url::getRelativeUrl (unsigned int partsToSkip) const
If the url is absolute or complete, strips the protocol and host part and.
Parameters:
n "directories"
Definition at line 93 of file url.cpp.
References getPath(), RDK2::Statistics::r, and RDK2::TextUtils::tokenize().
bool RDK2::RepositoryNS::Url::startsWith (const string & prefix) const [inline]
Returns true if this url begins with.
Parameters:
prefix
Definition at line 89 of file url.h.
Referenced by RDK2::RepositoryNS::Repository::setRemotePropertyDef().
bool RDK2::RepositoryNS::Url::isComplete () const [inline]
Url is complete when it has also the host part (i.e. it begins with "rdk://").
Definition at line 93 of file url.h.
Referenced by RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription(), RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription(), RDK2::RepositoryNS::RemoteSubscriptionRegister::completePropertyToReceiveSubscription(), getHost(), getLevel(), RDK2::RepositoryNS::Repository::getLocalProperty(), getPath(), RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Repository::getProperty(), isAbsolute(), isRelative(), RDK2::RepositoryNS::Session::lockAndGetProperty(), RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), RDK2::RepositoryNS::Session::propertyExists(), and RDK2::RepositoryNS::Repository::queuePush().
bool RDK2::RepositoryNS::Url::isRelative () const [inline]
Url is relative if it isn't complete and doesn't begin with a "/".
Definition at line 96 of file url.h.
References isComplete().
Referenced by getLevel().
bool RDK2::RepositoryNS::Url::isAbsolute () const [inline]
Url is absolute if it isn't complete and begins with a "/".
Definition at line 99 of file url.h.
References isComplete().
Referenced by RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Session::lockAndGetProperty(), and RDK2::RepositoryNS::Session::propertyExists().
int RDK2::RepositoryNS::Url::getLevel () const
Definition at line 134 of file url.cpp.
References isComplete(), and isRelative().
The documentation for this class was generated from the following files:
url.h
url.cpp