OpenRDK: RDK2::Common Namespace Reference
RDK2::Common Namespace Reference
Enumerations
enum RobotShape { CIRCULAR = 0, RECTANGULAR = 1 }
enum RobotWhicStalled { NONE = 0, LEFT = 1, RIGHT = 2, BOTH = 3 }
enum ModuleState { STATE_INACTIVE = 0, STATE_COMPUTING = 1, STATE_DONE = 2, STATE_FAILED = 3 }
Functions
bool createThread (pthread_t *threadId, void *(*threadFunction)(void *), void *functionParam, const std::string &threadName)
void createDefaultProperties (Session *session, bool defaultEnabled, bool haveToCreateStateProperty) throw (SessionException)
void createStateProperty (Session *session, string propertyName) throw (SessionException)
void createRobotProperties (Session *session) throw (SessionException)
void getRobotSizes (Session *session, double &robotMinSize, double &robotMaxSize) throw (SessionException)
Variables
vector
< RDK2::RSensorData::RUsarVictimRfidData * > cheIlCieloMiPerdoni
PosixConstructs::PosixMutex cheIlCieloMiFulmini
Enumeration Type Documentation
enum RDK2::Common::ModuleState
This enum defines the possible states that a "working" module can assume.
Enumerator:
STATE_INACTIVE
STATE_COMPUTING
STATE_DONE
STATE_FAILED
Definition at line 107 of file robotmodule.h.
enum RDK2::Common::RobotShape
Enumerator:
CIRCULAR
RECTANGULAR
Definition at line 87 of file robotmodule.h.
enum RDK2::Common::RobotWhicStalled
Enumerator:
NONE
LEFT
RIGHT
BOTH
Definition at line 88 of file robotmodule.h.
Function Documentation
void RDK2::Common::createDefaultProperties (Session * session, bool defaultEnabled, bool createStateProperty = true) throw (SessionException)
Create the properties every module should have
Definition at line 37 of file robotmodule.cpp.
References createStateProperty(), RDK2::RepositoryNS::INFO, PROPERTY_MODULE_ACTIVITY_COUNTER, PROPERTY_MODULE_ENABLED, PROPERTY_MODULE_ITERATION_DURATION_MEAN, PROPERTY_MODULE_LAST_ITERATION_TIMER, PROPERTY_MODULE_SCHEDULE_INTERVAL_MEAN, PROPERTY_MODULE_STATE, RDK2::RPrimitive::RDouble::SEC, SESSION_CATCH_RETHROW, and SESSION_TRY.
void RDK2::Common::createRobotProperties (Session * session) throw (SessionException)
Creates the properties every robot should have
Definition at line 66 of file robotmodule.cpp.
References BOTH, CIRCULAR, ENUM_CREATE, ENUM_ITEM, RDK2::RepositoryNS::INFO, LEFT, RDK2::RPrimitive::RDouble::M, RDK2::RPrimitive::RDouble::M_SEC, NONE, RDK2::RepositoryNS::NOT_PERSISTENT, PROPERTY_ROBOT_DATA_QUEUE, PROPERTY_ROBOT_DESIRED_JOG, PROPERTY_ROBOT_DESIRED_SPEED, PROPERTY_ROBOT_ESTIMATED_POSE, PROPERTY_ROBOT_HEIGHT, PROPERTY_ROBOT_JOG, PROPERTY_ROBOT_LASER_DATA, PROPERTY_ROBOT_LASER_POSE, PROPERTY_ROBOT_MAX_WHEEL_SPEED, PROPERTY_ROBOT_ODOMETRY_POSE, PROPERTY_ROBOT_RADIUS, PROPERTY_ROBOT_SHAPE, PROPERTY_ROBOT_SONAR_DATA, PROPERTY_ROBOT_SPEED, PROPERTY_ROBOT_STALLED, PROPERTY_ROBOT_TARGET_POSE, PROPERTY_ROBOT_WHICH_STALLED, PROPERTY_ROBOT_WIDTH, RDK2::RPrimitive::RDouble::RAD_SEC, RECTANGULAR, RIGHT, SESSION_CATCH_RETHROW, and SESSION_TRY.
void RDK2::Common::createStateProperty (Session * session, string propertyName) throw (SessionException)
Create a property that holds a ModuleState
Definition at line 56 of file robotmodule.cpp.
References ENUM_CREATE, ENUM_ITEM, RDK2::RepositoryNS::INFO, STATE_COMPUTING, STATE_DONE, STATE_FAILED, and STATE_INACTIVE.
Referenced by createDefaultProperties().
bool RDK2::Common::createThread (pthread_t * threadId, void *(*)(void *) threadFunction, void * functionParam, const std::string & threadName)
Definition at line 29 of file threads.cpp.
References RDK_ERROR_PRINTF.
Referenced by RDK2::RepositoryNS::UdpManager::start(), RDK2::RepositoryNS::TcpManager::start(), and RDK2::RepositoryNS::RemotePropertyManager::start().
void RDK2::Common::getRobotSizes (Session * session, double & robotMinSize, double & robotMaxSize) throw (SessionException)
Definition at line 105 of file robotmodule.cpp.
References CIRCULAR, PROPERTY_ROBOT_HEIGHT, PROPERTY_ROBOT_RADIUS, PROPERTY_ROBOT_SHAPE, PROPERTY_ROBOT_WIDTH, and ROBOT_PREFIX.
Variable Documentation
PosixConstructs::PosixMutex RDK2::Common::cheIlCieloMiFulmini
Definition at line 35 of file robotmodule.cpp.
vector< RDK2::RSensorData::RUsarVictimRfidData * > RDK2::Common::cheIlCieloMiPerdoni
Definition at line 34 of file robotmodule.cpp.