OpenRDK: Network Namespace Reference
Network Namespace Reference
Data Structures
class InetAddress
class NetException
class TCPException
class UDPException
class SocketAddress
class TCPServerSocket
class TCPSocket
class UDPSocket
Enumerations
enum NetProtocol {
NETPROTOCOL_ANY = 0, NETPROTOCOL_UNKNOWN = NETPROTOCOL_ANY, TCP_IP = 1, UDP_IP = 2,
USAR_WC = 3
}
enum ConnectionStatus {
NOT_CONNECTED = 0, CONNECTED = 1, TRYING = 2, FAILED = 3,
CONNECTION_RESET = 4
}
Functions
string netProtocolToString (NetProtocol netProtocol)
NetProtocol stringToNetProtocol (const string &s)
ConnectionStatus stringToConnectionStatus (const string &s)
string connectionStatusToString (ConnectionStatus status)
Enumeration Type Documentation
enum Network::ConnectionStatus
Enumerator:
NOT_CONNECTED
CONNECTED
TRYING
FAILED
CONNECTION_RESET
Definition at line 32 of file nettypes.h.
enum Network::NetProtocol
Enumerator:
NETPROTOCOL_ANY
NETPROTOCOL_UNKNOWN
TCP_IP
UDP_IP
USAR_WC
Definition at line 29 of file nettypes.h.
Function Documentation
string Network::connectionStatusToString (ConnectionStatus status)
Definition at line 53 of file nettypes.cpp.
References CONNECTED, CONNECTION_RESET, FAILED, NOT_CONNECTED, and TRYING.
string Network::netProtocolToString (NetProtocol netProtocol)
Definition at line 24 of file nettypes.cpp.
References NETPROTOCOL_UNKNOWN, TCP_IP, UDP_IP, and USAR_WC.
Referenced by RDK2::RepositoryNS::Session::getConnectionStatusWith(), RDK2::RepositoryNS::RRemoteSubscription::getStringForVisualization(), RDK2::RepositoryNS::Session::tryConnectTo(), and RDK2::RepositoryNS::Session::tryDisconnectFrom().
ConnectionStatus Network::stringToConnectionStatus (const string & s)
Definition at line 43 of file nettypes.cpp.
References CONNECTED, CONNECTION_RESET, FAILED, NOT_CONNECTED, and TRYING.
Referenced by RDK2::RepositoryNS::Session::getConnectionStatusWith().
NetProtocol Network::stringToNetProtocol (const string & s)
Definition at line 35 of file nettypes.cpp.
References NETPROTOCOL_UNKNOWN, TCP_IP, UDP_IP, and USAR_WC.
Referenced by RDK2::RNetObjects::RYellowPages::loadFromFile().