OpenRDK: Logging Namespace Reference
Logging Namespace Reference
Data Structures
class LevelFilter
class LogFile
struct LogMessage
struct LogHandler
class StreamSink
Typedefs
typedef std::vector< LogHandler * > Handlers
Enumerations
enum LogFileOptions { NORMAL = 0, TIMESTAMP_ON_FILENAME = 1, APPEND = 2 }
enum LogLevel {
Trace = 0, Debug = 1, Info = 2, Error = 3,
Fatal = 4
}
Functions
void log_message (int level, const string &module, const string &file, int line, const string &function, const string &prettyFunction, const string &message)
void log_message (int level, const string &module, const string &file, int line, const string &function, const string &prettyFunction, const char *printf_format,...)
void addLogHandler (LogHandler *h)
void removeLogHandler (LogHandler *)
void log_message (const LogMessage &l)
string pad (const string &r, unsigned int l, const string &t=" ")
string chop (const string &r, unsigned int len)
string align (const string &r, unsigned int len)
template<class T>
string toString (const T &t)
int splitString (const string &input, const string &delimiter, vector< string > &results, bool includeEmpties)
void splitStringToSize (string s, size_t size, vector< string > &results)
Variables
Handlers handlers
Typedef Documentation
typedef std::vector<LogHandler*> Logging::Handlers
Definition at line 81 of file logging.cpp.
Enumeration Type Documentation
enum Logging::LogFileOptions
Enumerator:
NORMAL
TIMESTAMP_ON_FILENAME
APPEND
Definition at line 27 of file logging/logfile.cpp.
enum Logging::LogLevel
Enumerator:
Trace
Debug
Info
Error
Fatal
Definition at line 58 of file logging.h.
Function Documentation
void Logging::addLogHandler (LogHandler * h)
Definition at line 84 of file logging.cpp.
References handlers, and logging_mutex.
Referenced by log_message().
string Logging::align (const string & r, unsigned int len)
Definition at line 53 of file streamsink.cpp.
References chop(), and pad().
Referenced by Logging::StreamSink::handle().
string Logging::chop (const string & r, unsigned int len)
Definition at line 49 of file streamsink.cpp.
Referenced by align().
void Logging::log_message (const LogMessage &)
Distributes log to the registered handlers.
Definition at line 94 of file logging.cpp.
References addLogHandler(), Debug, Error, handlers, Info, logging_mutex, RDK_LOG_COLOR, RDK_LOG_ENV, and Trace.
void Logging::log_message (int level, const string & module, const string & file, int line, const string & function, const string & prettyFunction, const char * printf_format, ...)
Definition at line 59 of file logging.cpp.
References BUFSIZE, and log_message().
void Logging::log_message (int level, const string & module, const string & file, int line, const string & function, const string & prettyFunction, const string & message)
Definition at line 38 of file logging.cpp.
References Logging::LogMessage::file, Logging::LogMessage::function, Logging::LogMessage::level, Logging::LogMessage::line, Logging::LogMessage::message, Logging::LogMessage::module, and Logging::LogMessage::prettyFunction.
Referenced by log_message().
string Logging::pad (const string & r, unsigned int l, const string & t = " ")
Definition at line 43 of file streamsink.cpp.
Referenced by align(), and RDK2::Geometry::matrix33().
void Logging::removeLogHandler (LogHandler *)
Definition at line 90 of file logging.cpp.
int Logging::splitString (const string & input, const string & delimiter, vector< string > & results, bool includeEmpties)
Definition at line 153 of file streamsink.cpp.
Referenced by Logging::StreamSink::handle().
void Logging::splitStringToSize (string s, size_t size, vector< string > & results)
Definition at line 69 of file streamsink.cpp.
Referenced by Logging::StreamSink::handle().
template<class T> string Logging::toString (const T & t) [inline]
Definition at line 57 of file streamsink.cpp.
Referenced by Logging::StreamSink::handle().
Variable Documentation
Handlers Logging::handlers
Definition at line 82 of file logging.cpp.
Referenced by addLogHandler(), and log_message().