OpenRDK: RDK2::RAgent Namespace Reference
RDK2::RAgent Namespace Reference
Data Structures
class Module
class ModuleManager
class ModuleConfig
struct Pair
struct RAgentConfig
Typedefs
typedef
RDK2::Containers::Vector
< ModuleConfig > ModuleConfigVector
typedef
RDK2::Containers::Vector< Pair > PropertyList
Functions
for (map< string, string >::const_iterator it=cm.textObjConfigs.begin();it!=cm.textObjConfigs.end();++it)
RDK2_FACTORY (ModuleConfig)
vector< string > stripOptionsFromTextConfigValue (string &val)
RDK2_FACTORY (Pair)
RDK2_FACTORY (RAgentConfig)
Typedef Documentation
typedef RDK2::Containers::Vector<ModuleConfig> RDK2::RAgent::ModuleConfigVector
Definition at line 63 of file moduleconfig.h.
typedef RDK2::Containers::Vector<Pair> RDK2::RAgent::PropertyList
Definition at line 57 of file pair.h.
Function Documentation
RDK2::RAgent::for (map< string, string >::const_iterator it = cm.textObjConfigs.begin(); it != cm.textObjConfigs.end(); ++it)
Definition at line 240 of file module.cpp.
References RDK2::RepositoryNS::PropertyDef::isKeepThis(), RDK2::RepositoryNS::PropertyDef::isPersistent(), RDK_ERROR_PRINTF, SESSION_CATCH, and SESSION_TRY_START.
Referenced by RDK2::SensorData::LaserDataTracker::update(), and RDK2::RepositoryNS::Repository::~Repository().
RDK2::RAgent::RDK2_FACTORY (RAgentConfig)
RDK2::RAgent::RDK2_FACTORY (Pair)
RDK2::RAgent::RDK2_FACTORY (ModuleConfig)
vector<string> RDK2::RAgent::stripOptionsFromTextConfigValue (string & val)
Definition at line 66 of file moduleconfig.cpp.
References RDK_ERROR_PRINTF, RDK2::TextUtils::tokenize(), and RDK2::TextUtils::trim().
Referenced by RDK2::RAgent::ModuleConfig::parseTextConfig().