OpenRDK: RDK2::SensorData Namespace Reference
RDK2::SensorData Namespace Reference
Data Structures
struct ActuaData
struct IrcData
struct LaserData
class LaserDataTracker
struct LaserParser
struct Parser
class LogReader
struct OdometryData
struct PantiltData
struct BaseSensorData
struct Unknown
struct SonarDevice
struct SonarData
struct XsensData
Functions
void laserdata2avv (const LaserData &scan, int npoints, double maxDist, AVV &avv)
Function Documentation
void RDK2::SensorData::laserdata2avv (const LaserData & scan, int nregpoints, double maxDist, RDK2::Geometry::AVV & avv)
Extracts oriented points from a carmen scan using regression. Note that it does not care if some rays are set to 0.
Definition at line 32 of file laserdata.cpp.
References RDK2::Geometry::max(), RDK2::Geometry::min(), RDK2::SensorData::LaserData::points, RDK2::Geometry::regression(), RDK2::Geometry::AppliedVector::theta, RDK2::Geometry::AppliedVector::weight, and RDK2::Geometry::AppliedVector::where.