OpenRDK: RDK2::Serialization::Xml Namespace Reference
RDK2::Serialization::Xml Namespace Reference
Data Structures
class XmlReader
class XmlWriter
Functions
template<typename T>
std::string vtos (T v, const char *format)
Function Documentation
template<typename T> std::string RDK2::Serialization::Xml::vtos (T v, const char * format) [inline]
Definition at line 36 of file xmlwriter.h.
Referenced by RDK2::Serialization::Xml::XmlWriter::write_f32(), RDK2::Serialization::Xml::XmlWriter::write_f64(), RDK2::Serialization::Xml::XmlWriter::write_i16(), RDK2::Serialization::Xml::XmlWriter::write_i32(), RDK2::Serialization::Xml::XmlWriter::write_i8(), and RDK2::Serialization::Xml::XmlWriter::write_u8().