OpenRDK: RDK2::RepositoryNS Namespace Reference
RDK2::RepositoryNS Namespace Reference
Data Structures
struct Event
struct EventPropertyUpdateDiff
struct EventPropertyUpdateValue
struct EventPropertyTreeAdded
struct EventPropertyTreeDeleted
struct EventQueuePush
struct EventTimer
class RemotePropertyManager
class RemoteSubscriptionRegister
class Repository
class Session
struct SessionInterfaceCore
struct SessionInterface
class TcpManager
class UdpManager
struct PropertyEnumItem
class PropertyDef
class Property
struct RObjectPipeQueue
struct RPropertyDef
struct RPropertyUpdate
struct RRemoteSubscription
class Url
Typedefs
typedef
PosixQueues::PipeQueueConsumer
< RDK2::Object > RConsumerObjectPipeQueue
typedef
RDK2::Containers::Vector
< RPropertyDef > RPropertyDefVector
typedef const Url & CUrl
Enumerations
enum QueueSubscriptionMode { QUEUE_LAST_OBJECT, QUEUE_ALL }
enum PropertyOptions {
NORMAL = 0x00, READ_ONLY = 0x01, DONT_SAVE = 0x02, INFO = READ_ONLY | DONT_SAVE,
NOT_PERSISTENT = DONT_SAVE
}
enum PropertyOptionsEnum {
PERSISTENT = 0x00, VOLATILE = 0x01, KEEP_THIS = 0x02, EDITABLE = 0x00,
NOT_EDITABLE = 0x04
}
Functions
DECLARE_EXCEPTION (SessionException, std::runtime_error)
DECLARE_EXCEPTION (NoSuchProperty, SessionException)
DECLARE_EXCEPTION (ValueNotSet, SessionException)
DECLARE_EXCEPTION (WrongType, SessionException)
DECLARE_EXCEPTION (InvalidOperation, SessionException)
DECLARE_EXCEPTION (MalformedUrlException, SessionException)
int gcd (int n, int m)
vector< string > getOptionsFromTextConfig (cstr val, string &newVal)
uint gcd (uint a, uint b)
Timer thread.
RDK2_FACTORY (RPropertyDef)
RDK2_FACTORY (RPropertyDefVector)
RDK2_FACTORY (RPropertyUpdate)
RDK2_FACTORY (RRemoteSubscription)
Typedef Documentation
typedef const Url& RDK2::RepositoryNS::CUrl
Definition at line 108 of file url.h.
typedef PosixQueues::PipeQueueConsumer<RDK2::Object> RDK2::RepositoryNS::RConsumerObjectPipeQueue
Definition at line 40 of file robjectqueue.h.
typedef RDK2::Containers::Vector<RPropertyDef> RDK2::RepositoryNS::RPropertyDefVector
Definition at line 28 of file rpropertydefvector.h.
Enumeration Type Documentation
enum RDK2::RepositoryNS::PropertyOptions
Enumerator:
NORMAL
READ_ONLY
DONT_SAVE
INFO
NOT_PERSISTENT
Definition at line 49 of file property.h.
enum RDK2::RepositoryNS::PropertyOptionsEnum
Enumerator:
PERSISTENT
VOLATILE
KEEP_THIS
EDITABLE
NOT_EDITABLE
Definition at line 57 of file property.h.
enum RDK2::RepositoryNS::QueueSubscriptionMode
Enumerator:
QUEUE_LAST_OBJECT I just need the last.
QUEUE_ALL Please send every object.
Definition at line 78 of file session.h.
Function Documentation
RDK2::RepositoryNS::DECLARE_EXCEPTION (MalformedUrlException , SessionException)
RDK2::RepositoryNS::DECLARE_EXCEPTION (InvalidOperation , SessionException)
Other exeptions
RDK2::RepositoryNS::DECLARE_EXCEPTION (WrongType , SessionException)
You are asking an object of a type and the property contains objects of another type.
RDK2::RepositoryNS::DECLARE_EXCEPTION (ValueNotSet , SessionException)
You are asking for a property which is not set and doesn't have a default value.
RDK2::RepositoryNS::DECLARE_EXCEPTION (NoSuchProperty , SessionException)
Can't find a property with the specified name.
RDK2::RepositoryNS::DECLARE_EXCEPTION (SessionException , std::runtime_error)
Base for exception generated by this class.
uint RDK2::RepositoryNS::gcd (uint a, uint b)
Timer thread.
Definition at line 372 of file repository.cpp.
int RDK2::RepositoryNS::gcd (int n, int m)
Definition at line 215 of file remotepropertymanager.cpp.
Referenced by RDK2::RepositoryNS::Repository::timerThread().
vector<string> RDK2::RepositoryNS::getOptionsFromTextConfig (cstr val, string & newVal)
Definition at line 123 of file repository.cpp.
References RDK_ERROR_PRINTF, RDK2::TextUtils::tokenize(), and RDK2::TextUtils::trim().
RDK2::RepositoryNS::RDK2_FACTORY (RRemoteSubscription)
RDK2::RepositoryNS::RDK2_FACTORY (RPropertyUpdate)
RDK2::RepositoryNS::RDK2_FACTORY (RPropertyDefVector)
RDK2::RepositoryNS::RDK2_FACTORY (RPropertyDef)