OpenRDK: RDK2::Demangle Namespace Reference
RDK2::Demangle Namespace Reference
Data Structures
struct Reflective
Functions
std::string deleteNamespaces (const std::string &s)
void rdemangle (const char *sym, char *buf)
std::string demangle (const char *symbol)
void try_type (global &g)
void simple_class (global &g)
void native_type (global &g)
void pointer (global &g)
void reference (global &g)
void qualified_class (global &g)
void template_class (global &g)
Function Documentation
std::string RDK2::Demangle::deleteNamespaces (const std::string & s)
X -> X (..::)*X->X
Definition at line 28 of file demangle.cpp.
Referenced by demangle().
std::string RDK2::Demangle::demangle (const char * symbol)
Definition at line 38 of file demangle.cpp.
References deleteNamespaces(), and rdemangle().
Referenced by RDK2::Demangle::Reflective::getClassName(), and RDK2::UnitTest::Object::TestReflection1::runTest().
void RDK2::Demangle::native_type (global & g)
Definition at line 83 of file demangle.cpp.
Referenced by try_type().
void RDK2::Demangle::pointer (global & g)
Definition at line 124 of file demangle.cpp.
References try_type().
Referenced by try_type().
void RDK2::Demangle::qualified_class (global & g)
Definition at line 136 of file demangle.cpp.
References try_type().
Referenced by try_type().
void RDK2::Demangle::rdemangle (const char * sym, char * buf)
Vecchia implementazione
Definition at line 63 of file demangle.cpp.
References try_type().
Referenced by demangle().
void RDK2::Demangle::reference (global & g)
Definition at line 130 of file demangle.cpp.
References try_type().
Referenced by try_type().
void RDK2::Demangle::simple_class (global & g)
Definition at line 74 of file demangle.cpp.
Referenced by try_type().
void RDK2::Demangle::template_class (global & g)
Definition at line 149 of file demangle.cpp.
References try_type().
Referenced by try_type().
void RDK2::Demangle::try_type (global & g)
Definition at line 172 of file demangle.cpp.
References native_type(), pointer(), qualified_class(), reference(), simple_class(), and template_class().
Referenced by pointer(), qualified_class(), rdemangle(), reference(), and template_class().