OpenRDK: RDK2::Filesystem Namespace Reference
RDK2::Filesystem Namespace Reference
Functions
double modificationTime (cstr file)
bool fsDirContent (const string &directory, vector< string > &dirContent)
void fsMakeParents (cstr path) throw (runtime_error)
Misc.
bool fsNewerThan (cstr file1, cstr file2) throw (runtime_error)
Returns true if file1 is newer than file2.
bool fsExists (cstr file) throw ()
Returns true if file exists.
string fsReadFile (cstr file) throw (runtime_error)
reads a file into a string
string fsOnlyFilename (cstr path) throw (runtime_error)
string fsCat (cstr path1, cstr path2)
Filenames.
string fsRealpath (cstr s) throw (runtime_error)
string fsDirname (cstr file) throw (runtime_error)
void fsOpenOrException (ifstream &ifs, cstr filename) throw (runtime_error)
Opening.
void fsOpenOrException (ofstream &ofs, cstr filename) throw (runtime_error)
Function Documentation
string RDK2::Filesystem::fsCat (cstr path1, cstr path2)
Filenames.
Concat. two paths.
Definition at line 56 of file filesystem.cpp.
References fsRealpath().
bool RDK2::Filesystem::fsDirContent (const string & directory, vector< string > & dirContent)
Definition at line 116 of file filesystem.cpp.
string RDK2::Filesystem::fsDirname (cstr file) throw (runtime_error)
Returns name of the directory
Definition at line 109 of file filesystem.cpp.
bool RDK2::Filesystem::fsExists (cstr file) throw ()
Returns true if file exists.
Definition at line 95 of file filesystem.cpp.
void RDK2::Filesystem::fsMakeParents (cstr path) throw (runtime_error)
Misc.
Create the parents of path (a la makeparents)
Definition at line 35 of file filesystem.cpp.
bool RDK2::Filesystem::fsNewerThan (cstr file1, cstr file2) throw (runtime_error)
Returns true if file1 is newer than file2.
Definition at line 91 of file filesystem.cpp.
References modificationTime().
string RDK2::Filesystem::fsOnlyFilename (cstr path) throw (runtime_error)
Last part of path
Definition at line 39 of file filesystem.cpp.
void RDK2::Filesystem::fsOpenOrException (ofstream & ofs, cstr filename) throw (runtime_error)
Opens file for writing, or throws an exception.
Definition at line 50 of file filesystem.cpp.
References RDK2::Profiling::ofs, and RDK2::TextUtils::quote().
Referenced by RDK2::Geometry::PGMFile::load().
void RDK2::Filesystem::fsOpenOrException (ifstream & ifs, cstr filename) throw (runtime_error)
Opening.
Opens file for reading, or throws an exception.
Definition at line 44 of file filesystem.cpp.
References RDK2::TextUtils::quote().
Referenced by fsReadFile().
string RDK2::Filesystem::fsReadFile (cstr file) throw (runtime_error)
reads a file into a string
Definition at line 100 of file filesystem.cpp.
References fsOpenOrException().
string RDK2::Filesystem::fsRealpath (cstr s) throw (runtime_error)
Normalizes a filename, runtime_error on problems.
Definition at line 60 of file filesystem.cpp.
References RDK2::TextUtils::quote().
Referenced by fsCat().
double RDK2::Filesystem::modificationTime (cstr file)
Definition at line 72 of file filesystem.cpp.
References RDK2::TextUtils::quote().
Referenced by fsNewerThan().