OpenRDK: nettcptest2.cpp File Reference
nettcptest2.cpp File Reference
#include <rdkcore/network/tcpserversocket.h>
#include <rdkcore/network/tcpsocket.h>
#include <iostream>
#include <signal.h>
Functions
void * sender (TCPSocket *)
void * receiver (TCPSocket *)
int main (int argc, const char **argv)
Variables
TCPSocket * tcpstream = NULL
Function Documentation
int main (int argc, const char ** argv)
Definition at line 33 of file nettcptest2.cpp.
References Network::TCPServerSocket::accept(), Network::NetException::fullwhat(), receiver(), and sender().
void * receiver (TCPSocket * tcpstream)
Definition at line 71 of file nettcptest2.cpp.
References Network::NetException::fullwhat().
Referenced by main().
void * sender (TCPSocket * tcpstream)
Definition at line 59 of file nettcptest2.cpp.
References Network::NetException::fullwhat().
Referenced by RDK2::RNetObjects::RNetMessage::clone(), RDK2::RNetObjects::RNetMessage::getSender(), main(), RDK2::RNetObjects::RNetMessage::operator=(), RDK2::RNetObjects::RNetMessage::read(), and RDK2::RNetObjects::RNetMessage::write().
Variable Documentation
TCPSocket* tcpstream = NULL
Definition at line 31 of file nettcptest2.cpp.