OpenRDK: relay.cpp File Reference
relay.cpp File Reference
#include <rdkcore/network/udpsocket.h>
#include <iostream>
#include <iomanip>
#include <cstring>
#include <cstdlib>
#include <set>
Defines
#define VERSION 1.1
#define BUFFERSIZE 0xFFFF
#define _DEBUG
#define DOUT(a) cout<<setw(4)<<__LINE__<<"|"<<setw(15)<<__func__<<"| "<<a<<endl;
Functions
int main (int argc, char **argv)
Define Documentation
#define _DEBUG
Definition at line 30 of file relay.cpp.
#define BUFFERSIZE 0xFFFF
Definition at line 28 of file relay.cpp.
#define DOUT (a) cout<<setw(4)<<__LINE__<<"|"<<setw(15)<<__func__<<"| "<<a<<endl;
Definition at line 32 of file relay.cpp.
#define VERSION 1.1
Definition at line 27 of file relay.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 39 of file relay.cpp.
References DOUT, Network::NetException::fullwhat(), Network::InetAddress::getIPAddress(), Network::InetAddress::getPort(), Network::UDPSocket::recv(), Network::UDPSocket::send(), sender(), and Network::InetAddress::setPort().