OpenRDK: RDK2::Profiling::Profiler Struct Reference
RDK2::Profiling::Profiler Struct Reference
#include <profiling.h>
Detailed Description
Definition at line 85 of file profiling.h.
Static Public Member Functions
static void open (const char *filename)
static void start (const char *name)
static void end (const char *name)
static void lock (const char *name)
static void unlock (const char *name)
static void addCustomLine (const char *what, const char *name, const char *otherInfo="")
Member Function Documentation
void RDK2::Profiling::Profiler::open (const char * filename) [static]
Apre il file per il profiling
Definition at line 63 of file profiling.cpp.
References RDK2::Profiling::doProfile, RDK2::Profiling::ofs, RDK2::Profiling::startClock, and RDK2::Profiling::startTimestamp.
void RDK2::Profiling::Profiler::start (const char * name) [static]
Scrive un messaggio di tipo START
Definition at line 71 of file profiling.cpp.
References addCustomLine().
Referenced by RDK2::RepositoryNS::Session::profilingStartEvent(), and RDK2::RepositoryNS::Session::start().
void RDK2::Profiling::Profiler::end (const char * name) [static]
Scrive un messaggio di tipo END
Definition at line 76 of file profiling.cpp.
References addCustomLine().
Referenced by RDK2::RepositoryNS::Session::end(), RDK2::RepositoryNS::Session::profilingEndEvent(), and RDK2::RepositoryNS::Session::terminate().
void RDK2::Profiling::Profiler::lock (const char * name) [static]
Scrive un messaggio di tipo LOCK
Definition at line 81 of file profiling.cpp.
References addCustomLine().
Referenced by RDK2::RepositoryNS::Session::createEnum(), RDK2::RepositoryNS::Session::getEnumString(), RDK2::RepositoryNS::Session::getPropertyClassName(), RDK2::RepositoryNS::Session::getPropertyDescription(), RDK2::RepositoryNS::Session::getPropertyEnumItems(), RDK2::RepositoryNS::Session::getPropertyLinkTo(), RDK2::RepositoryNS::Session::getRPropertyDef(), RDK2::RepositoryNS::Session::lock(), RDK2::RepositoryNS::Session::lockAndGetProperty(), RDK2::RepositoryNS::Session::setPropertyOptions(), and RDK2::RepositoryNS::Session::textConfigLineForProperty().
void RDK2::Profiling::Profiler::unlock (const char * name) [static]
Scrive un messaggio di tipo UNLOCK
Definition at line 86 of file profiling.cpp.
References addCustomLine().
Referenced by RDK2::RepositoryNS::Session::createEnum(), RDK2::RepositoryNS::Session::getEnumString(), RDK2::RepositoryNS::Session::getObjectClone(), RDK2::RepositoryNS::Session::getPropertyClassName(), RDK2::RepositoryNS::Session::getPropertyDescription(), RDK2::RepositoryNS::Session::getPropertyEnumItems(), RDK2::RepositoryNS::Session::getPropertyLinkTo(), RDK2::RepositoryNS::Session::getRPropertyDef(), RDK2::RepositoryNS::Session::lockAndGetProperty(), RDK2::RepositoryNS::Session::setPropertyOptions(), RDK2::RepositoryNS::Session::textConfigLineForProperty(), RDK2::RepositoryNS::Session::unlock(), and RDK2::RepositoryNS::Session::unlockProperty().
void RDK2::Profiling::Profiler::addCustomLine (const char * what, const char * name, const char * otherInfo = "") [static]
Scrive un messaggio custom - usato ad esempio per le code
Definition at line 91 of file profiling.cpp.
References RDK2::Profiling::doProfile, RDK2::Profiling::getClock(), RDK2::Profiling::getClockBetter(), RDK2::Profiling::getTimestamp(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::mutex, RDK2::Profiling::ofs, and PosixConstructs::PosixMutex::unlock().
Referenced by end(), lock(), RDK2::RepositoryNS::Session::queueFreeze(), start(), and unlock().
The documentation for this struct was generated from the following files:
profiling.h
profiling.cpp