OpenRDK: RDK2::Geometry::PGMFile Struct Reference
RDK2::Geometry::PGMFile Struct Reference
#include <pgmfile.h>
Detailed Description
Alcune funzioni per caricare e salvare i pgm (sia P2 che P5), cercando di unire il codice ripetuto fra DMatrix e RMapImage. Puo' darsi che questa roba non vada in Geometry (che bello subversion che si possono spostare i file.
Definition at line 37 of file pgmfile.h.
Public Types
enum Type { P2, P5 }
Public Member Functions
PGMFile (const std::string &file) throw (runtime_error)
PGMFile ()
void load (std::istream &is) throw (runtime_error)
void load (const std::string &file) throw (runtime_error)
bool load_ (const std::string &file)
RDK2::Geometry::Viewport getViewport (double meters_per_pixel=0) throw (runtime_error, invalid_argument)
bool readResolution (double &)
Data Fields
enum RDK2::Geometry::PGMFile::Type type
std::string comment
int maxVal
int width
int height
DMatrix< int > buffer
Member Enumeration Documentation
enum RDK2::Geometry::PGMFile::Type
Enumerator:
P2
P5
Definition at line 38 of file pgmfile.h.
Constructor & Destructor Documentation
RDK2::Geometry::PGMFile::PGMFile (const std::string & file) throw (runtime_error) [inline]
Opens a PGM file, throws an exceptions if there are problems.
Definition at line 47 of file pgmfile.h.
References load().
RDK2::Geometry::PGMFile::PGMFile ()
Member Function Documentation
void RDK2::Geometry::PGMFile::load (std::istream & is) throw (runtime_error)
Definition at line 36 of file pgmfile.cpp.
References RDK2::TextUtils::consumeWhitespace(), EXPECT_MAXVAL, RDK2::TextUtils::quote(), RDK_DEBUG_STREAM, RDK_ERROR_STREAM, RDK_TRACE_PRINTF, RDK2::TextUtils::readCommentLines(), and RDK2::TextUtils::toString().
Referenced by load_(), and PGMFile().
void RDK2::Geometry::PGMFile::load (const std::string & file) throw (runtime_error)
Definition at line 30 of file pgmfile.cpp.
References RDK2::Filesystem::fsOpenOrException().
bool RDK2::Geometry::PGMFile::load_ (const std::string & file)
Definition at line 110 of file pgmfile.cpp.
References load(), and RDK_ERROR_STREAM.
Viewport RDK2::Geometry::PGMFile::getViewport (double meters_per_pixel = 0) throw (runtime_error, invalid_argument)
Definition at line 119 of file pgmfile.cpp.
References RDK_DEBUG_STREAM, and RDK2::TextUtils::toString().
bool RDK2::Geometry::PGMFile::readResolution (double & mapResolution)
Definition at line 155 of file pgmfile.cpp.
References comment, RDK_ERROR_STREAM, and RDK2::TextUtils::toString().
Field Documentation
enum RDK2::Geometry::PGMFile::Type RDK2::Geometry::PGMFile::type
std::string RDK2::Geometry::PGMFile::comment
The comment section in the file.
Definition at line 41 of file pgmfile.h.
Referenced by readResolution().
int RDK2::Geometry::PGMFile::maxVal
Definition at line 43 of file pgmfile.h.
int RDK2::Geometry::PGMFile::width
Definition at line 43 of file pgmfile.h.
int RDK2::Geometry::PGMFile::height
Definition at line 43 of file pgmfile.h.
DMatrix<int> RDK2::Geometry::PGMFile::buffer
Definition at line 44 of file pgmfile.h.
The documentation for this struct was generated from the following files:
pgmfile.h
pgmfile.cpp