OpenRDK: RDK2::RGeometry::RPoint2od Struct Reference
RDK2::RGeometry::RPoint2od Struct Reference
#include <rpoint2od.h>
Detailed Description
Definition at line 28 of file rpoint2od.h.
Public Member Functions
RPoint2od (double x=0, double y=0, double theta=0)
RPoint2od (const RDK2::Geometry::Point2od &p)
RDK2::Object * clone () const
void read (RDK2::Reader *r) throw (RDK2::ReadingException)
void write (RDK2::Writer *w) const throw (RDK2::WritingException)
bool hasStringRepresentation () const
Ritorna true se ha una rappresentazione "semplice" come stringa.
std::string getStringRepresentation () const
Ritorna la rappresentazione come stringa.
bool loadFromStringRepresentation (const std::string &)
Inversa della precedente.
bool hasStringForVisualization () const
Returns true if this object has a string that can be visualized.
std::string getStringForVisualization () const
Returns a string to be used to visualize the object.
std::vector< Object * > getTestCases () const
Get a vector of test cases.
bool equals (const Object *p) const
Constructor & Destructor Documentation
RDK2::RGeometry::RPoint2od::RPoint2od (double x = 0, double y = 0, double theta = 0) [inline]
Definition at line 30 of file rpoint2od.h.
Referenced by clone(), and getTestCases().
RDK2::RGeometry::RPoint2od::RPoint2od (const RDK2::Geometry::Point2od & p) [inline]
Definition at line 32 of file rpoint2od.h.
Member Function Documentation
RDK2::Object * RDK2::RGeometry::RPoint2od::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 35 of file rpoint2od.cpp.
References RPoint2od().
void RDK2::RGeometry::RPoint2od::read (RDK2::Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 65 of file rpoint2od.cpp.
References RDK2::Demangle::Reflective::getClassName(), RDK2::Statistics::r, RDK2::Object::readObjectBody(), RDK2::Geometry::Point2< double >::theta(), RDK2::Geometry::Point2< double >::x, and RDK2::Geometry::Point2< double >::y.
void RDK2::RGeometry::RPoint2od::write (RDK2::Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 76 of file rpoint2od.cpp.
References RDK2::Demangle::Reflective::getClassName(), RDK2::Geometry::Point2< double >::theta(), RDK2::Object::writeObjectBody(), RDK2::Geometry::Point2< double >::x, and RDK2::Geometry::Point2< double >::y.
bool RDK2::RGeometry::RPoint2od::hasStringRepresentation () const [inline, virtual]
Ritorna true se ha una rappresentazione "semplice" come stringa.
Reimplemented from RDK2::Object.
Definition at line 38 of file rpoint2od.h.
std::string RDK2::RGeometry::RPoint2od::getStringRepresentation () const [virtual]
Ritorna la rappresentazione come stringa.
Reimplemented from RDK2::Object.
Definition at line 40 of file rpoint2od.cpp.
References RDK2::Geometry::rad2deg(), RDK2::Geometry::Point2< double >::theta(), RDK2::Geometry::Point2< double >::x, and RDK2::Geometry::Point2< double >::y.
bool RDK2::RGeometry::RPoint2od::loadFromStringRepresentation (const std::string &) [virtual]
Inversa della precedente.
Reimplemented from RDK2::Object.
Definition at line 47 of file rpoint2od.cpp.
References RDK2::Geometry::deg2rad(), RDK2::Geometry::Point2< double >::theta(), RDK2::Geometry::Point2< double >::x, and RDK2::Geometry::Point2< double >::y.
bool RDK2::RGeometry::RPoint2od::hasStringForVisualization () const [inline, virtual]
Returns true if this object has a string that can be visualized.
Reimplemented from RDK2::Object.
Definition at line 42 of file rpoint2od.h.
std::string RDK2::RGeometry::RPoint2od::getStringForVisualization () const [virtual]
Returns a string to be used to visualize the object.
Reimplemented from RDK2::Object.
Definition at line 57 of file rpoint2od.cpp.
References RDK2::Geometry::rad2deg(), RDK2::Geometry::Point2< double >::theta(), RDK2::Geometry::Point2< double >::x, and RDK2::Geometry::Point2< double >::y.
std::vector< Object * > RDK2::RGeometry::RPoint2od::getTestCases () const [virtual]
Get a vector of test cases.
Reimplemented from RDK2::Object.
Definition at line 87 of file rpoint2od.cpp.
References RDK_INF64, RDK_NAN, and RPoint2od().
bool RDK2::RGeometry::RPoint2od::equals (const Object *) const [virtual]
Compare this and another object.
Note:
For clarity, we decided not to use operator=.
Returns:
true if they are equivalent
Reimplemented from RDK2::Object.
Definition at line 100 of file rpoint2od.cpp.
References RDK2::Geometry::Point2o< Numeric >::theta, RDK2::Geometry::Point2< double >::theta(), RDK2::Geometry::Point2< Numeric >::x, RDK2::Geometry::Point2< double >::x, RDK2::Geometry::Point2< Numeric >::y, and RDK2::Geometry::Point2< double >::y.
The documentation for this struct was generated from the following files:
rpoint2od.h
rpoint2od.cpp