OpenRDK: RDK2::RMaps::RTopologicalFrontier Struct Reference
RDK2::RMaps::RTopologicalFrontier Struct Reference
#include <rtopologicalfrontier.h>
Detailed Description
This class represents a topological frontier, that is a magic thing used for coordination.
Definition at line 44 of file rtopologicalfrontier.h.
Public Member Functions
RTopologicalFrontier ()
RTopologicalFrontier (double x0, double y0, double x1, double y1)
bool isSimilarTo (const RTopologicalFrontier *topolFront, double frontierSimilarityDist=DEFAULT_FRONTIER_SIMILARITY_DIST) const
bool hasStringForVisualization () const
std::string getStringForVisualization () const
Returns a string to be used to visualize the object.
RDK2_DEFAULT_CLONE (RTopologicalFrontier)
Serialization
void read (Reader *r) throw (ReadingException)
void write (Writer *w) const throw (WritingException)
Data Fields
Point2d point0
Point2d point1
Point2od midpoint
Constructor & Destructor Documentation
RDK2::RMaps::RTopologicalFrontier::RTopologicalFrontier () [inline]
Every class should have a default constructor
Definition at line 53 of file rtopologicalfrontier.h.
RDK2::RMaps::RTopologicalFrontier::RTopologicalFrontier (double x0, double y0, double x1, double y1)
Constructor: takes the coordinates of the segment's end points. Assumes that, going from x0 to y0, the empty, known space is on the left.
Definition at line 35 of file rtopologicalfrontier.cpp.
References midpoint, RDK2::Geometry::Point2o< Numeric >::theta, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Member Function Documentation
bool RDK2::RMaps::RTopologicalFrontier::isSimilarTo (const RTopologicalFrontier * topolFront, double frontierSimilarityDist = DEFAULT_FRONTIER_SIMILARITY_DIST) const [inline]
Definition at line 60 of file rtopologicalfrontier.h.
References RDK2::Geometry::Point2< Numeric >::distTo(), and midpoint.
bool RDK2::RMaps::RTopologicalFrontier::hasStringForVisualization () const [inline, virtual]
Returns true because this object has a string that can be visualized.
Reimplemented from RDK2::Object.
Definition at line 68 of file rtopologicalfrontier.h.
std::string RDK2::RMaps::RTopologicalFrontier::getStringForVisualization () const [virtual]
Returns a string to be used to visualize the object.
Reimplemented from RDK2::Object.
Definition at line 66 of file rtopologicalfrontier.cpp.
References midpoint, point0, point1, RDK2::Geometry::Point2o< Numeric >::toString(), and RDK2::Geometry::Point2< Numeric >::toString().
void RDK2::RMaps::RTopologicalFrontier::read (Reader * r) throw (ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 57 of file rtopologicalfrontier.cpp.
References RDK2::Statistics::r.
void RDK2::RMaps::RTopologicalFrontier::write (Writer *) const throw (WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 48 of file rtopologicalfrontier.cpp.
RDK2::RMaps::RTopologicalFrontier::RDK2_DEFAULT_CLONE (RTopologicalFrontier)
Field Documentation
Point2d RDK2::RMaps::RTopologicalFrontier::point0
Definition at line 45 of file rtopologicalfrontier.h.
Referenced by getStringForVisualization().
Point2d RDK2::RMaps::RTopologicalFrontier::point1
Definition at line 45 of file rtopologicalfrontier.h.
Referenced by getStringForVisualization().
Point2od RDK2::RMaps::RTopologicalFrontier::midpoint
The middle point has also information about the direction where the known empty space is
Definition at line 48 of file rtopologicalfrontier.h.
Referenced by getStringForVisualization(), isSimilarTo(), and RTopologicalFrontier().
The documentation for this struct was generated from the following files:
rtopologicalfrontier.h
rtopologicalfrontier.cpp