OpenRDK: RDK2::Geometry::PolarPoint Struct Reference
RDK2::Geometry::PolarPoint Struct Reference
#include <otherpoints.h>
Detailed Description
Definition at line 32 of file otherpoints.h.
Public Member Functions
PolarPoint (double theta=0, double rho=0)
PolarPoint (const Point2d &p)
Point2d getCartesian () const
bool operator< (const PolarPoint &m) const
PolarPoint operator+ (const PolarPoint &p) const
PolarPoint operator- (const PolarPoint &p) const
bool operator== (const PolarPoint &p)
Data Fields
double theta
double rho
Constructor & Destructor Documentation
RDK2::Geometry::PolarPoint::PolarPoint (double theta = 0, double rho = 0) [inline]
Definition at line 35 of file otherpoints.h.
Referenced by operator+().
RDK2::Geometry::PolarPoint::PolarPoint (const Point2d & p) [inline]
Definition at line 36 of file otherpoints.h.
References RDK2::Geometry::Point2< Numeric >::abs(), rho, RDK2::Geometry::Point2< Numeric >::theta(), and theta.
Member Function Documentation
Point2d RDK2::Geometry::PolarPoint::getCartesian () const [inline]
Definition at line 41 of file otherpoints.h.
References rho, theta, and RDK2::Geometry::Point2< double >::vers().
Referenced by RDK2::Geometry::changeRef(), and RDK2::Geometry::translateTo().
bool RDK2::Geometry::PolarPoint::operator< (const PolarPoint & m) const [inline]
Definition at line 45 of file otherpoints.h.
References theta.
PolarPoint RDK2::Geometry::PolarPoint::operator+ (const PolarPoint & p) const [inline]
Definition at line 49 of file otherpoints.h.
References PolarPoint(), rho, and theta.
PolarPoint RDK2::Geometry::PolarPoint::operator- (const PolarPoint & p) const [inline]
Definition at line 64 of file otherpoints.h.
References theta.
bool RDK2::Geometry::PolarPoint::operator== (const PolarPoint & p) [inline]
Definition at line 71 of file otherpoints.h.
References rho, and theta.
Field Documentation
double RDK2::Geometry::PolarPoint::theta
Definition at line 33 of file otherpoints.h.
Referenced by getCartesian(), RDK2::RMaps::RLandmark::getLogLine(), RDK2::RMaps::RLandmark::loadFromLogLine(), operator+(), operator-(), operator<(), operator==(), and PolarPoint().
double RDK2::Geometry::PolarPoint::rho
Definition at line 33 of file otherpoints.h.
Referenced by getCartesian(), RDK2::RMaps::RLandmark::getLogLine(), RDK2::RMaps::RLandmark::loadFromLogLine(), operator+(), operator==(), and PolarPoint().
The documentation for this struct was generated from the following file:
otherpoints.h