OpenRDK: RDK2::RGraphics::RImageDiffPoints Struct Reference
RDK2::RGraphics::RImageDiffPoints Struct Reference
#include <rimagediffpoints.h>
Detailed Description
Definition at line 34 of file rimagediffpoints.h.
Public Member Functions
RImageDiffPoints ()
RImageDiffPoints (RImage *image, vector< Point2i > points)
virtual ~RImageDiffPoints ()
virtual RDK2::Object * clone () const
virtual void read (RDK2::Reader *r) throw (RDK2::ReadingException)
virtual void write (RDK2::Writer *w) const throw (RDK2::WritingException)
virtual vector< ObjectDiff * > split (size_t maxSize)
Data Fields
RImage * image
vector< Point2i > points
int refImageWidth
int refImageHeight
RImage::Type refImageType
vector< uint32_t > colorsRGB32
vector< uint8_t > colorsC8
Constructor & Destructor Documentation
RDK2::RGraphics::RImageDiffPoints::RImageDiffPoints () [inline]
Definition at line 35 of file rimagediffpoints.h.
Referenced by clone().
RDK2::RGraphics::RImageDiffPoints::RImageDiffPoints (RImage * image, vector< Point2i > points)
Definition at line 29 of file rimagediffpoints.cpp.
References RDK2::RGraphics::RImage::C8, colorsC8, RDK2::RGraphics::RImage::getBuffer(), RDK2::RGraphics::RImage::getType(), RDK2::RGraphics::RImage::getWidth(), and RDK_ERROR_PRINTF.
virtual RDK2::RGraphics::RImageDiffPoints::~RImageDiffPoints () [inline, virtual]
Definition at line 37 of file rimagediffpoints.h.
Member Function Documentation
RDK2::Object * RDK2::RGraphics::RImageDiffPoints::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 45 of file rimagediffpoints.cpp.
References RImageDiffPoints().
Referenced by RDK2::RMaps::RMapImageDiffPoints::clone().
void RDK2::RGraphics::RImageDiffPoints::read (RDK2::Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 50 of file rimagediffpoints.cpp.
References RDK2::Statistics::r.
void RDK2::RGraphics::RImageDiffPoints::write (RDK2::Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 57 of file rimagediffpoints.cpp.
vector< ObjectDiff * > RDK2::RGraphics::RImageDiffPoints::split (size_t maxSize) [virtual]
Implements RDK2::Meta::ObjectDiff.
Definition at line 64 of file rimagediffpoints.cpp.
Referenced by RDK2::RMaps::RMapImageDiffPoints::split().
Field Documentation
RImage* RDK2::RGraphics::RImageDiffPoints::image
Definition at line 46 of file rimagediffpoints.h.
vector<Point2i> RDK2::RGraphics::RImageDiffPoints::points
Definition at line 47 of file rimagediffpoints.h.
Referenced by RDK2::RGraphics::RImage::applyDiff().
int RDK2::RGraphics::RImageDiffPoints::refImageWidth
Definition at line 49 of file rimagediffpoints.h.
int RDK2::RGraphics::RImageDiffPoints::refImageHeight
Definition at line 49 of file rimagediffpoints.h.
RImage::Type RDK2::RGraphics::RImageDiffPoints::refImageType
Definition at line 50 of file rimagediffpoints.h.
vector<uint32_t> RDK2::RGraphics::RImageDiffPoints::colorsRGB32
Definition at line 53 of file rimagediffpoints.h.
vector<uint8_t> RDK2::RGraphics::RImageDiffPoints::colorsC8
Definition at line 54 of file rimagediffpoints.h.
Referenced by RDK2::RGraphics::RImage::applyDiff(), and RImageDiffPoints().
The documentation for this struct was generated from the following files:
rimagediffpoints.h
rimagediffpoints.cpp