OpenRDK: RDK2::RMaps::RMapImageDiffPoints Struct Reference
RDK2::RMaps::RMapImageDiffPoints Struct Reference
#include <rmapimagediffpoints.h>
Detailed Description
Definition at line 35 of file rmapimagediffpoints.h.
Public Member Functions
RMapImageDiffPoints ()
RMapImageDiffPoints (RMapImage *mapImage, const vector< Point2i > &points)
virtual ~RMapImageDiffPoints ()
virtual void read (RDK2::Reader *r) throw (RDK2::ReadingException)
virtual void write (RDK2::Writer *w) const throw (RDK2::WritingException)
virtual std::vector< ObjectDiff * > split (size_t maxSize)
virtual RDK2::Object * clone () const
Data Fields
double refMapImageX
double refMapImageY
double refMapImageTheta
double refMapImageRealWidth
RImageDiffPoints * imageDiffPoints
Constructor & Destructor Documentation
RDK2::RMaps::RMapImageDiffPoints::RMapImageDiffPoints ()
Definition at line 35 of file rmapimagediffpoints.cpp.
Referenced by clone(), and split().
RDK2::RMaps::RMapImageDiffPoints::RMapImageDiffPoints (RMapImage * mapImage, const vector< Point2i > & points)
Definition at line 27 of file rmapimagediffpoints.cpp.
References RDK2::RMaps::RMapImage::image, and imageDiffPoints.
virtual RDK2::RMaps::RMapImageDiffPoints::~RMapImageDiffPoints () [inline, virtual]
Definition at line 38 of file rmapimagediffpoints.h.
References imageDiffPoints.
Member Function Documentation
void RDK2::RMaps::RMapImageDiffPoints::read (RDK2::Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 47 of file rmapimagediffpoints.cpp.
References RDK2::Demangle::Reflective::getClassName(), and RDK2::Statistics::r.
void RDK2::RMaps::RMapImageDiffPoints::write (RDK2::Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 54 of file rmapimagediffpoints.cpp.
References RDK2::Demangle::Reflective::getClassName().
vector< ObjectDiff * > RDK2::RMaps::RMapImageDiffPoints::split (size_t maxSize) [virtual]
Implements RDK2::Meta::ObjectDiff.
Definition at line 61 of file rmapimagediffpoints.cpp.
References imageDiffPoints, RMapImageDiffPoints(), and RDK2::RGraphics::RImageDiffPoints::split().
RDK2::Object * RDK2::RMaps::RMapImageDiffPoints::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 40 of file rmapimagediffpoints.cpp.
References RDK2::RGraphics::RImageDiffPoints::clone(), imageDiffPoints, RDK2::Statistics::r, and RMapImageDiffPoints().
Field Documentation
double RDK2::RMaps::RMapImageDiffPoints::refMapImageX
Definition at line 47 of file rmapimagediffpoints.h.
double RDK2::RMaps::RMapImageDiffPoints::refMapImageY
Definition at line 47 of file rmapimagediffpoints.h.
double RDK2::RMaps::RMapImageDiffPoints::refMapImageTheta
Definition at line 47 of file rmapimagediffpoints.h.
double RDK2::RMaps::RMapImageDiffPoints::refMapImageRealWidth
Definition at line 48 of file rmapimagediffpoints.h.
RImageDiffPoints* RDK2::RMaps::RMapImageDiffPoints::imageDiffPoints
Definition at line 49 of file rmapimagediffpoints.h.
Referenced by RDK2::RMaps::RMapImage::applyDiff(), clone(), RMapImageDiffPoints(), split(), and ~RMapImageDiffPoints().
The documentation for this struct was generated from the following files:
rmapimagediffpoints.h
rmapimagediffpoints.cpp