OpenRDK: RDK2::RPrimitive::RDouble Struct Reference
RDK2::RPrimitive::RDouble Struct Reference
#include <rdouble.h>
Detailed Description
Definition at line 27 of file rdouble.h.
Public Types
enum Unit {
REAL = 0, PERC = 1, M = 3, M_SEC = 4,
M_SEC2 = 5, SEC = 7, RAD = 8, RAD_SEC = 9,
RAD_SEC2 = 10, CELSIUS = 12, PIXELS = 13, OTHER = 99,
MM = 100, MM_SEC = 101, MM_CYCLE = 102, MM_SEC2 = 103,
DEG_CYCLE = 104, DEG = 105, DEG_SEC = 106, MS = 107,
M_CYCLE = 108, RAD_CYCLE = 109, PERC_CYCLE = 110
}
Public Member Functions
RDouble ()
RDouble (double a)
RDouble (double a, Unit u)
const char * myClassName () const
Object * clone () const
std::string getStringForVisualization () const
Returns a string to be used to visualize the object.
std::string getStringRepresentation () const
Ritorna la rappresentazione come stringa.
bool loadFromStringRepresentation (const std::string &s)
Inversa della precedente.
void read (RDK2::Reader *r) throw (RDK2::ReadingException)
void write (RDK2::Writer *w) const throw (RDK2::WritingException)
Static Public Member Functions
static std::string getUnitString (Unit unit)
Data Fields
enum
RDK2::RPrimitive::RDouble::Unit unit
Member Enumeration Documentation
enum RDK2::RPrimitive::RDouble::Unit
Enumerator:
REAL RDK2 Units: USE ONLY THESE!!!
Unitless
PERC Percentual.
M Meters.
M_SEC Meters/second.
M_SEC2 Meters/second^2.
SEC Seconds.
RAD Radians (NOTE: radiants are always saved, loaded and displayed as degrees).
RAD_SEC Radians/second (same as above).
RAD_SEC2 Radians/second^2 (same as above).
CELSIUS Celsius degrees (temperature).
PIXELS Pixels.
OTHER Other (use this ONLY if no other unit fits).
MM DON'T USE THESE!!
Millimiters
MM_SEC Millimiters/second.
MM_CYCLE Millimeters/algorithm cycle.
MM_SEC2 Radians/second^2.
DEG_CYCLE Degrees/cycle.
DEG Degrees.
DEG_SEC Degress/second.
MS Milliseconds.
M_CYCLE Meters/cycle.
RAD_CYCLE Radians/algorithm cycle (same as above).
PERC_CYCLE Percentual/algorithm cycle.
Definition at line 31 of file rdouble.h.
Constructor & Destructor Documentation
RDK2::RPrimitive::RDouble::RDouble () [inline]
Definition at line 28 of file rdouble.h.
Referenced by clone().
RDK2::RPrimitive::RDouble::RDouble (double a) [inline]
Definition at line 29 of file rdouble.h.
RDK2::RPrimitive::RDouble::RDouble (double a, Unit u) [inline]
Definition at line 60 of file rdouble.h.
Member Function Documentation
const char * RDK2::RPrimitive::RDouble::myClassName () const [virtual]
Implements RDK2::RPrimitive::RPrimitive< double >.
Definition at line 39 of file rdouble.cpp.
References RDK2::RPrimitive::d.
Object * RDK2::RPrimitive::RDouble::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 43 of file rdouble.cpp.
References RDK2::RPrimitive::d, RDouble(), unit, and RDK2::RPrimitive::RPrimitive< double >::value.
string RDK2::RPrimitive::RDouble::getStringForVisualization () const [virtual]
Returns a string to be used to visualize the object.
Reimplemented from RDK2::Object.
Definition at line 98 of file rdouble.cpp.
References getUnitString(), M_SEC2, PERC, PERC_CYCLE, RAD, RDK2::Geometry::rad2deg(), RAD_CYCLE, RAD_SEC, RAD_SEC2, SEC, unit, and RDK2::RPrimitive::RPrimitive< double >::value.
string RDK2::RPrimitive::RDouble::getStringRepresentation () const [virtual]
Ritorna la rappresentazione come stringa.
Reimplemented from RDK2::RPrimitive::RPrimitive< double >.
Definition at line 77 of file rdouble.cpp.
References PERC, PERC_CYCLE, RAD, RDK2::Geometry::rad2deg(), RAD_CYCLE, RAD_SEC, RAD_SEC2, SEC, unit, and RDK2::RPrimitive::RPrimitive< double >::value.
bool RDK2::RPrimitive::RDouble::loadFromStringRepresentation (const std::string &) [virtual]
Inversa della precedente.
Reimplemented from RDK2::RPrimitive::RPrimitive< double >.
Definition at line 89 of file rdouble.cpp.
References RDK2::Geometry::deg2rad(), PERC, PERC_CYCLE, RAD, RAD_CYCLE, RAD_SEC, RAD_SEC2, unit, and RDK2::RPrimitive::RPrimitive< double >::value.
string RDK2::RPrimitive::RDouble::getUnitString (Unit unit) [static]
Definition at line 50 of file rdouble.cpp.
References CELSIUS, M, M_CYCLE, M_SEC, M_SEC2, MS, OTHER, PERC, PERC_CYCLE, PIXELS, RAD, RAD_CYCLE, RAD_SEC, RAD_SEC2, REAL, and SEC.
Referenced by getStringForVisualization().
void RDK2::RPrimitive::RDouble::read (RDK2::Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 137 of file rdouble.cpp.
References RDK2::Demangle::Reflective::getClassName(), RDK2::Statistics::r, unit, and RDK2::RPrimitive::RPrimitive< double >::value.
void RDK2::RPrimitive::RDouble::write (RDK2::Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 144 of file rdouble.cpp.
References RDK2::Demangle::Reflective::getClassName(), unit, and RDK2::RPrimitive::RPrimitive< double >::value.
Field Documentation
enum RDK2::RPrimitive::RDouble::Unit RDK2::RPrimitive::RDouble::unit
Referenced by clone(), getStringForVisualization(), getStringRepresentation(), loadFromStringRepresentation(), read(), and write().
The documentation for this struct was generated from the following files:
rdouble.h
rdouble.cpp