OpenRDK: RDK2::Demangle::Reflective Struct Reference
RDK2::Demangle::Reflective Struct Reference
#include <demangle.h>
Detailed Description
Definition at line 31 of file demangle.h.
Public Member Functions
Reflective ()
virtual ~Reflective ()
virtual std::string getClassName () const
Constructor & Destructor Documentation
RDK2::Demangle::Reflective::Reflective () [inline]
Definition at line 32 of file demangle.h.
virtual RDK2::Demangle::Reflective::~Reflective () [inline, virtual]
Definition at line 33 of file demangle.h.
Member Function Documentation
virtual std::string RDK2::Demangle::Reflective::getClassName () const [inline, virtual]
Reimplemented in RDK2::Containers::Vector< RType >, RDK2::Containers::Vector< RDK2::RGeometry::RPoint2d >, RDK2::Containers::Vector< RDK2::RAgent::ModuleConfig >, and RDK2::Containers::Vector< RDK2::RAgent::Pair >.
Definition at line 34 of file demangle.h.
References RDK2::Demangle::demangle().
Referenced by RDK2::Object::clone(), RDK2::Meta::Factory::Factory(), RDK2::RepositoryNS::Session::getObjectAsL(), RDK2::RepositoryNS::Property::getObjectAsL(), RDK2::RepositoryNS::Session::getObjectAsLC(), RDK2::RepositoryNS::Property::getObjectAsLC(), RDK2::RepositoryNS::Session::getObjectCloneAs(), RDK2::Object::getStringRepresentation(), RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage(), RDK2::RepositoryNS::Session::queueLastAs(), RDK2::RPrimitive::RString::read(), RDK2::RepositoryNS::RPropertyUpdate::read(), RDK2::RGeometry::RPoint2od::read(), RDK2::RMaps::RMapImageDiffRect::read(), RDK2::RMaps::RMapImageDiffPoints::read(), RDK2::RMaps::RMapImage::read(), RDK2::RSensorData::RJoystickStatus::read(), RDK2::RGraphics::RImageDiffRect::read(), RDK2::RPrimitive::RDouble::read(), RDK2::Object::read(), RDK2::UnitTest::Object::TestReflection1::runTest(), RDK2::UnitTest::Serialization::SerializationTest2::runTest(), RDK2::RepositoryNS::Property::setObjectL(), RDK2::RPrimitive::RString::write(), RDK2::RepositoryNS::RPropertyUpdate::write(), RDK2::RGeometry::RPoint2od::write(), RDK2::RMaps::RMapImageDiffRect::write(), RDK2::RMaps::RMapImageDiffPoints::write(), RDK2::RMaps::RMapImage::write(), RDK2::RSensorData::RJoystickStatus::write(), RDK2::RGraphics::RImageDiffRect::write(), RDK2::RPrimitive::RDouble::write(), and RDK2::Object::write().
The documentation for this struct was generated from the following file:
demangle.h