OpenRDK: RDK2::RMaps::RLandmark Struct Reference
RDK2::RMaps::RLandmark Struct Reference
#include <rlandmark.h>
Detailed Description
Definition at line 29 of file rlandmark.h.
Public Member Functions
RLandmark (const RDK2::Geometry::Point2d pos=RDK2::Geometry::Point2d(0., 0.), const RDK2::Geometry::PolarPoint per=RDK2::Geometry::PolarPoint(0., 0.))
std::string getLogLine () const
bool loadFromLogLine (cstr line)
void read (Reader *r) throw (ReadingException)
void write (Writer *w) const throw (WritingException)
RDK2_DEFAULT_CLONE (RLandmark)
Data Fields
RDK2::Geometry::PolarPoint percept
Constructor & Destructor Documentation
RDK2::RMaps::RLandmark::RLandmark (const RDK2::Geometry::Point2d pos = RDK2::Geometry::Point2d(0., 0.), const RDK2::Geometry::PolarPoint per = RDK2::Geometry::PolarPoint(0., 0.)) [inline]
Definition at line 35 of file rlandmark.h.
Member Function Documentation
std::string RDK2::RMaps::RLandmark::getLogLine () const [virtual]
Reimplemented from RDK2::SensorData::BaseSensorData.
Definition at line 68 of file rlandmark.cpp.
References RDK2::SensorData::BaseSensorData::estimatedPose, RDK2::Time::Timestamp::getMsFromMidnight(), RDK2::SensorData::BaseSensorData::ipc_hostname, RDK2::SensorData::BaseSensorData::ipc_timestamp, RDK2::SensorData::BaseSensorData::logtag, RDK2::SensorData::BaseSensorData::odometryPose, percept, RDK2::Geometry::PolarPoint::rho, RDK2::Geometry::Point2o< Numeric >::theta, RDK2::Geometry::PolarPoint::theta, RDK2::SensorData::BaseSensorData::timestamp, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
bool RDK2::RMaps::RLandmark::loadFromLogLine (cstr line)
Definition at line 88 of file rlandmark.cpp.
References RDK2::SensorData::BaseSensorData::estimatedPose, RDK2::SensorData::BaseSensorData::ipc_hostname, RDK2::SensorData::BaseSensorData::ipc_timestamp, RDK2::SensorData::BaseSensorData::logtag, RDK2::SensorData::BaseSensorData::odometryPose, percept, RDK_ERROR_STREAM, RDK2::Geometry::PolarPoint::rho, RDK2::Time::Timestamp::setMsFromMidnight(), RDK2::Geometry::Point2o< Numeric >::theta, RDK2::Geometry::PolarPoint::theta, RDK2::SensorData::BaseSensorData::timestamp, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
void RDK2::RMaps::RLandmark::read (Reader * r) throw (ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::RGeometry::RPoint2d.
Definition at line 48 of file rlandmark.cpp.
References RDK2::Statistics::r, and RDK2::Object::readObjectBody().
void RDK2::RMaps::RLandmark::write (Writer *) const throw (WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::RGeometry::RPoint2d.
Definition at line 28 of file rlandmark.cpp.
References RDK2::Object::writeObjectBody().
RDK2::RMaps::RLandmark::RDK2_DEFAULT_CLONE (RLandmark)
Field Documentation
RDK2::Geometry::PolarPoint RDK2::RMaps::RLandmark::percept
Definition at line 33 of file rlandmark.h.
Referenced by getLogLine(), and loadFromLogLine().
The documentation for this struct was generated from the following files:
rlandmark.h
rlandmark.cpp