OpenRDK: RDK2::SensorData::LaserParser Struct Reference
RDK2::SensorData::LaserParser Struct Reference
#include <laserparser.h>
Detailed Description
Definition at line 27 of file laserparser.h.
Public Member Functions
std::string getTag ()
BaseSensorData * parse (const std::string &data, std::string *error)
bool write (const BaseSensorData *input, std::string &data, std::string *error)
void setParam (const std::string &name, const std::string &line)
virtual ~LaserParser ()
Constructor & Destructor Documentation
virtual RDK2::SensorData::LaserParser::~LaserParser () [inline, virtual]
Definition at line 41 of file laserparser.h.
Member Function Documentation
std::string RDK2::SensorData::LaserParser::getTag () [inline, virtual]
Implements RDK2::SensorData::Parser.
Definition at line 28 of file laserparser.h.
Referenced by parse().
BaseSensorData * RDK2::SensorData::LaserParser::parse (const std::string & data, std::string * error) [virtual]
Implements RDK2::SensorData::Parser.
Definition at line 43 of file laserparser.cpp.
References RDK2::SensorData::BaseSensorData::estimatedPose, getTag(), RDK2::SensorData::LaserData::LaserPoint::intensity, RDK2::SensorData::BaseSensorData::ipc_hostname, RDK2::SensorData::BaseSensorData::ipc_timestamp, RDK2::SensorData::LaserData::laserPose, RDK2::SensorData::LaserData::maxReading, RDK2::SensorData::LaserData::maxTheta, RDK2::SensorData::LaserData::minReading, RDK2::SensorData::LaserData::minTheta, RDK2::SensorData::BaseSensorData::odometryPose, RDK2::TextUtils::parse(), RDK2::Geometry::parsePoint(), RDK2::SensorData::LaserData::points, RDK2::SensorData::LaserData::LaserPoint::reading, RDK2::SensorData::BaseSensorData::tag, RDK2::SensorData::LaserData::LaserPoint::theta, RDK2::SensorData::BaseSensorData::timestamp, RDK2::TextUtils::tokenize(), and RDK2::TextUtils::toString().
bool RDK2::SensorData::LaserParser::write (const BaseSensorData * input, std::string & data, std::string * error) [virtual]
Implements RDK2::SensorData::Parser.
Definition at line 122 of file laserparser.cpp.
References RDK2::SensorData::BaseSensorData::estimatedPose, RDK2::Time::Timestamp::getSeconds(), RDK2::SensorData::BaseSensorData::ipc_hostname, RDK2::SensorData::BaseSensorData::ipc_timestamp, RDK2::SensorData::BaseSensorData::odometryPose, RDK2::SensorData::LaserData::points, RDK2::SensorData::BaseSensorData::tag, RDK2::Geometry::Point2o< Numeric >::theta, RDK2::SensorData::BaseSensorData::timestamp, RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
void RDK2::SensorData::LaserParser::setParam (const std::string & name, const std::string & line) [virtual]
Reimplemented from RDK2::SensorData::Parser.
Definition at line 39 of file laserparser.cpp.
The documentation for this struct was generated from the following files:
laserparser.h
laserparser.cpp