OpenRDK: unittest_naninf.cpp File Reference
unittest_naninf.cpp File Reference
#include <iostream>
#include <cppunit/ui/text/TestRunner.h>
#include <cppunit/TestCase.h>
#include <rdkcore/geometry/utils.h>
#include <rdkcore/logging/logging.h>
#include <rdkcore/ns.h>
Defines
#define LOGGING_MODULE "test"
Functions
template<class T>
bool string2val2string (const std::string &s)
template<class T>
bool val2string2val (T v, T epsilon=1e-10)
int main ()
Define Documentation
#define LOGGING_MODULE "test"
Definition at line 27 of file unittest_naninf.cpp.
Function Documentation
int main ()
Definition at line 108 of file unittest_naninf.cpp.
template<class T> bool string2val2string (const std::string & s) [inline]
Definition at line 34 of file unittest_naninf.cpp.
References RDK2::Geometry::float2string(), and RDK2::Geometry::string2float().
template<class T> bool val2string2val (T v, T epsilon = 1e-10) [inline]
Definition at line 50 of file unittest_naninf.cpp.
References RDK2::Geometry::float2string(), RDK2::Geometry::sameFloat(), and RDK2::Geometry::string2float().