OpenRDK: unittest_testcases.cpp File Reference
unittest_testcases.cpp File Reference
#include <rdkcore/serialization_xml/xmlreader.h>
#include <rdkcore/serialization_xml/xmlwriter.h>
#include <rdkcore/serialization_binary/binaryreader.h>
#include <rdkcore/serialization_binary/binarywriter.h>
#include <rdkcore/object/objectmanager.h>
#include <rdkcore/logging/logging.h>
#include <map>
#include <string>
Defines
#define LOGGING_MODULE "test_all"
Functions
int main ()
Define Documentation
#define LOGGING_MODULE "test_all"
Definition at line 27 of file unittest_testcases.cpp.
Function Documentation
int main ()
Definition at line 38 of file unittest_testcases.cpp.
References RDK2::Serialization::Binary::BinaryReader::deserialize(), RDK2::Serialization::Xml::XmlReader::deserialize(), RDK2::Object::equals(), RDK2::Meta::forName(), RDK2::Meta::getClass2prot(), RDK2::Object::getTestCases(), RDK_DEBUG_STREAM, RDK_ERROR_STREAM, RDK_INFO_STREAM, RDK2::Serialization::Binary::BinaryWriter::serialize(), and RDK2::Serialization::Xml::XmlWriter::serialize().