OpenRDK: xmlutils.h File Reference
xmlutils.h File Reference
#include <string>
#include <libxml/xmlreader.h>
Defines
#define XML_CHECK_ERROR(assertion, msg, retonerr)
#define XML_ENCODING "ISO-8859-1"
#define XML_NAMESPACE_PREFIX BAD_CAST "rdk"
#define XML_NAMESPACE_URI_ROOT BAD_CAST "http://sied.dis.uniroma1.it/rdk"
#define XML_NAMESPACE_URI 0
Functions
xmlChar * xmlEncode (const char *s)
xmlChar * xmlDecode (const char *s)
void encode64 (const char *input, size_t n, std::string &output, bool add_crlf)
void decode64 (const std::string &input, std::string &output, size_t &n)
Define Documentation
#define XML_CHECK_ERROR (assertion, msg, retonerr)
Value:
if ((assertion)) { \
        xmlErrorPtr e = xmlGetLastError(); \
        RDK_ERROR_STREAM(string(msg) << (e ? e->message : "")); \
        return retonerr; \
    }
Definition at line 26 of file xmlutils.h.
Referenced by RDK2::Serialization::Xml::XmlReader::deserialize(), and RDK2::Serialization::Xml::XmlWriter::serialize().
#define XML_ENCODING "ISO-8859-1"
Definition at line 33 of file xmlutils.h.
Referenced by RDK2::Serialization::Xml::XmlReader::deserialize(), RDK2::Serialization::Xml::XmlWriter::serialize(), and xmled().
#define XML_NAMESPACE_PREFIX BAD_CAST "rdk"
Definition at line 34 of file xmlutils.h.
Referenced by RDK2::Serialization::Xml::XmlWriter::startWriting().
#define XML_NAMESPACE_URI 0
Definition at line 36 of file xmlutils.h.
Referenced by RDK2::Serialization::Xml::XmlWriter::startWriting().
#define XML_NAMESPACE_URI_ROOT BAD_CAST "http://sied.dis.uniroma1.it/rdk"
Definition at line 35 of file xmlutils.h.
Referenced by RDK2::Serialization::Xml::XmlWriter::startWriting().
Function Documentation
void decode64 (const std::string & input, std::string & output, size_t & n)
Definition at line 95 of file xmlutils.cpp.
References rstr.
Referenced by RDK2::Serialization::Xml::XmlReader::readBytes().
void encode64 (const char * input, size_t n, std::string & output, bool add_crlf)
Definition at line 129 of file xmlutils.cpp.
References bstr.
Referenced by RDK2::Serialization::Xml::XmlWriter::writeBytes().
xmlChar* xmlDecode (const char * s)
Definition at line 80 of file xmlutils.cpp.
References xmled().
Referenced by RDK2::Serialization::Xml::XmlReader::readString().
xmlChar* xmlEncode (const char * s)
Definition at line 75 of file xmlutils.cpp.
References xmled().
Referenced by RDK2::Serialization::Xml::XmlWriter::writeString().