OpenRDK: xmlutils.cpp File Reference
xmlutils.cpp File Reference
#include <string.h>
#include <libxml/encoding.h>
#include "xmlutils.h"
Functions
xmlChar * xmled (const char *in, bool encode)
xmlChar * xmlEncode (const char *in)
xmlChar * xmlDecode (const char *in)
void decode64 (const std::string &input, std::string &output, size_t &n)
void encode64 (const char *input, size_t n, std::string &output, bool add_crlf)
Variables
char rstr []
const char * bstr
Function Documentation
void decode64 (const std::string & input, std::string & output, size_t & n)
Definition at line 95 of file xmlutils.cpp.
References rstr.
Referenced by RDK2::Serialization::Xml::XmlReader::readBytes().
void encode64 (const char * input, size_t n, std::string & output, bool add_crlf)
Definition at line 129 of file xmlutils.cpp.
References bstr.
Referenced by RDK2::Serialization::Xml::XmlWriter::writeBytes().
xmlChar* xmlDecode (const char * in)
Definition at line 80 of file xmlutils.cpp.
References xmled().
Referenced by RDK2::Serialization::Xml::XmlReader::readString().
xmlChar* xmled (const char * in, bool encode)
Definition at line 25 of file xmlutils.cpp.
References XML_ENCODING.
Referenced by xmlDecode(), and xmlEncode().
xmlChar* xmlEncode (const char * in)
Definition at line 75 of file xmlutils.cpp.
References xmled().
Referenced by RDK2::Serialization::Xml::XmlWriter::writeString().
Variable Documentation
const char* bstr
Initial value:
    "ABCDEFGHIJKLMNOPQ"
    "RSTUVWXYZabcdefgh"
    "ijklmnopqrstuvwxy"
    "z0123456789+/"
Definition at line 123 of file xmlutils.cpp.
Referenced by encode64().
char rstr[]
Initial value:
 {
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  62,   0,   0,   0,  63,
    52,  53,  54,  55,  56,  57,  58,  59,  60,  61,   0,   0,   0,   0,   0,   0,
    0,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
    15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,   0,   0,   0,   0,   0,
    0,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
    41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,   0,   0,   0,   0,   0}
Definition at line 85 of file xmlutils.cpp.
Referenced by decode64().