OpenRDK: Network::TCPSocket Class Reference
Network::TCPSocket Class Reference
#include <tcpsocket.h>
Detailed Description
Definition at line 30 of file tcpsocket.h.
Public Member Functions
TCPSocket (std::streamsize buffersize=2048) throw ()
TCPSocket (const std::string &address, unsigned short port, std::streamsize buffersize=2048) throw (TCPException, NetException)
TCPSocket (const InetAddress &address, std::streamsize buffersize=2048) throw (TCPException)
virtual ~TCPSocket ()
int getSocket ()
void disconnect () throw (TCPException)
void connect (const std::string &address, unsigned short port) throw (TCPException, NetException)
void connect (const InetAddress &address) throw (TCPException)
const InetAddress & getAddress () const
InetAddress getPeerAddress () const
Protected Member Functions
virtual int overflow (int c=EOF)
virtual int underflow ()
virtual int sync ()
Friends
class TCPServerSocket
Constructor & Destructor Documentation
Network::TCPSocket::TCPSocket (std::streamsize buffersize = 2048) throw ()
Definition at line 68 of file tcpsocket.cpp.
References DOUT.
Network::TCPSocket::TCPSocket (const std::string & address, unsigned short port, std::streamsize buffersize = 2048) throw (TCPException, NetException)
Definition at line 77 of file tcpsocket.cpp.
References DOUT.
Network::TCPSocket::TCPSocket (const InetAddress & address, std::streamsize buffersize = 2048) throw (TCPException)
Definition at line 88 of file tcpsocket.cpp.
References DOUT.
Network::TCPSocket::~TCPSocket () [virtual]
Definition at line 98 of file tcpsocket.cpp.
References disconnect(), and DOUT.
Member Function Documentation
int Network::TCPSocket::getSocket () [inline]
Definition at line 41 of file tcpsocket.h.
void Network::TCPSocket::disconnect () throw (TCPException)
Definition at line 110 of file tcpsocket.cpp.
References DOUT.
Referenced by connect(), and ~TCPSocket().
void Network::TCPSocket::connect (const std::string & address, unsigned short port) throw (TCPException, NetException)
Definition at line 118 of file tcpsocket.cpp.
References connect(), disconnect(), and DOUT.
Referenced by connect().
void Network::TCPSocket::connect (const InetAddress & address) throw (TCPException)
Definition at line 125 of file tcpsocket.cpp.
References connect(), disconnect(), and DOUT.
const InetAddress& Network::TCPSocket::getAddress () const [inline]
Definition at line 53 of file tcpsocket.h.
InetAddress Network::TCPSocket::getPeerAddress () const
Definition at line 249 of file tcpsocket.cpp.
int Network::TCPSocket::overflow (int c = EOF) [protected, virtual]
Definition at line 160 of file tcpsocket.cpp.
References DOUT, DWRITE, and SNIFFWRITE.
Referenced by sync().
int Network::TCPSocket::underflow () [protected, virtual]
Definition at line 209 of file tcpsocket.cpp.
References DOUT, DWRITE, Network::InetAddress::getIPAddress(), RDOUT, and SNIFFWRITE.
int Network::TCPSocket::sync () [protected, virtual]
Definition at line 243 of file tcpsocket.cpp.
References DOUT, and overflow().
Friends And Related Function Documentation
friend class TCPServerSocket [friend]
Definition at line 57 of file tcpsocket.h.
The documentation for this class was generated from the following files:
tcpsocket.h
tcpsocket.cpp