OpenRDK: RDK2::UnitTest::Serialization::SerializationTest2 Class Reference
RDK2::UnitTest::Serialization::SerializationTest2 Class Reference
#include <test2.h>
Detailed Description
Serialize instance
Compare to file (create if not exists)
Create another instance with forName()
Deserialize, serialize again
Definition at line 43 of file test2.h.
Public Member Functions
SerializationTest2 (std::string name, RDK2::Object *o, Writer *w, Reader *r, cstr file)
void runTest ()
Data Fields
RDK2::Object * o
Writer * w
Reader * r
string file
Constructor & Destructor Documentation
RDK2::UnitTest::Serialization::SerializationTest2::SerializationTest2 (std::string name, RDK2::Object * o, Writer * w, Reader * r, cstr file) [inline]
Definition at line 49 of file test2.h.
Member Function Documentation
void RDK2::UnitTest::Serialization::SerializationTest2::runTest () [inline]
Definition at line 54 of file test2.h.
References compareToFile(), RDK2::Serialization::Reader::deserialize(), file, RDK2::Demangle::Reflective::getClassName(), o, r, RDK2::Serialization::Writer::serialize(), and w.
Field Documentation
RDK2::Object* RDK2::UnitTest::Serialization::SerializationTest2::o
Definition at line 45 of file test2.h.
Referenced by runTest().
Writer* RDK2::UnitTest::Serialization::SerializationTest2::w
Definition at line 46 of file test2.h.
Referenced by runTest().
Reader* RDK2::UnitTest::Serialization::SerializationTest2::r
Definition at line 47 of file test2.h.
Referenced by runTest().
string RDK2::UnitTest::Serialization::SerializationTest2::file
Definition at line 47 of file test2.h.
Referenced by runTest().
The documentation for this class was generated from the following file:
test2.h