OpenRDK: RDK2::Time::TimerT Class Reference
RDK2::Time::TimerT Class Reference
#include <time.h>
Detailed Description
This measures the thread time.
Definition at line 106 of file time.h.
Public Member Functions
TimerT ()
void start ()
double getMs ()
double getSeconds ()
Constructor & Destructor Documentation
RDK2::Time::TimerT::TimerT () [inline]
Definition at line 108 of file time.h.
References start().
Member Function Documentation
void RDK2::Time::TimerT::start () [inline]
Definition at line 109 of file time.h.
Referenced by RDK2::RepositoryNS::Session::start(), and TimerT().
double RDK2::Time::TimerT::getMs () [inline]
Definition at line 110 of file time.h.
Referenced by getSeconds().
double RDK2::Time::TimerT::getSeconds () [inline]
Definition at line 111 of file time.h.
References getMs().
Referenced by RDK2::RepositoryNS::Session::end(), and RDK2::RepositoryNS::Session::terminate().
The documentation for this class was generated from the following file:
time.h