OpenRDK: PosixQueues::PipeQueueConsumer< T > Class Template Reference
PosixQueues::PipeQueueConsumer< T > Class Template Reference
#include <pipequeue.h>
Detailed Description
template<class T>
class PosixQueues::PipeQueueConsumer< T >
All functions must be called from the same thread.
Definition at line 52 of file pipequeue.h.
Public Member Functions
PipeQueueConsumer (int fd_in, int fd_out, const std::string &name)
~PipeQueueConsumer ()
vector< const T * > freeze ()
vector< const T * > content ()
const T * last ()
void keep (const T *t)
Data Fields
vector< const T * > toKeep
Constructor & Destructor Documentation
template<class T> PosixQueues::PipeQueueConsumer< T >::PipeQueueConsumer (int fd_in, int fd_out, const std::string & name) [inline]
Definition at line 54 of file pipequeue.h.
template<class T> PosixQueues::PipeQueueConsumer< T >::~PipeQueueConsumer () [inline]
Definition at line 56 of file pipequeue.h.
Member Function Documentation
template<class T> vector< const T * > PosixQueues::PipeQueueConsumer< T >::freeze () [inline]
Definition at line 205 of file pipequeue.h.
Referenced by main(), RDK2::RepositoryNS::Session::queueFreeze(), and thread().
template<class T> vector< const T * > PosixQueues::PipeQueueConsumer< T >::content () [inline]
Definition at line 267 of file pipequeue.h.
Referenced by RDK2::RepositoryNS::Session::queueKeep().
template<class T> const T * PosixQueues::PipeQueueConsumer< T >::last () [inline]
Definition at line 271 of file pipequeue.h.
template<class T> void PosixQueues::PipeQueueConsumer< T >::keep (const T * t) [inline]
Definition at line 186 of file pipequeue.h.
Referenced by RDK2::RepositoryNS::Session::queueKeep().
Field Documentation
template<class T> vector<const T*> PosixQueues::PipeQueueConsumer< T >::toKeep
Definition at line 63 of file pipequeue.h.
The documentation for this class was generated from the following file:
pipequeue.h