OpenRDK: RDK2::Serialization::Binary::BinaryWriter Class Reference
RDK2::Serialization::Binary::BinaryWriter Class Reference
#include <binarywriter.h>
Detailed Description
A binary writer
Definition at line 32 of file binarywriter.h.
Public Member Functions
BinaryWriter (bool writeNames)
virtual ~BinaryWriter ()
std::string serialize (bool withClassName, const Writable *w)
void startWriting (cstr myClassName, unsigned char version) throw (WritingException)
void write_u8 (uint8_t, cstr name) throw (WritingException)
void write_i8 (int8_t, cstr name) throw (WritingException)
void write_i16 (int16_t, cstr name) throw (WritingException)
void write_i32 (int32_t, cstr name) throw (WritingException)
void write_f32 (float32_t, cstr name) throw (WritingException)
void write_f64 (float64_t, cstr name) throw (WritingException)
void write_u8 (const uint8_t *, size_t n, cstr name) throw (WritingException)
void write_i8 (const int8_t *, size_t n, cstr name) throw (WritingException)
void write_i16 (const int16_t *, size_t n, cstr name) throw (WritingException)
void write_i32 (const int32_t *, size_t n, cstr name) throw (WritingException)
void write_f32 (const float32_t *, size_t n, cstr name) throw (WritingException)
void write_f64 (const float64_t *, size_t n, cstr name) throw (WritingException)
void writeString (cstr s, cstr name) throw (WritingException)
void writeBytes (const void *i, size_t n, cstr name) throw (WritingException)
Scrittura di buffer.
void writeObject (bool needClassName, const Writable *w, cstr name="") throw (WritingException)
Scrittura di oggetti.
void doneWriting () throw (WritingException)
Data Structures
struct Context
Constructor & Destructor Documentation
RDK2::Serialization::Binary::BinaryWriter::BinaryWriter (bool writeNames) [inline]
Public interface
Definition at line 38 of file binarywriter.h.
RDK2::Serialization::Binary::BinaryWriter::~BinaryWriter () [virtual]
Definition at line 26 of file binarywriter.cpp.
Member Function Documentation
Buffer RDK2::Serialization::Binary::BinaryWriter::serialize (bool withClassName, const Writable * w) [virtual]
Serializes the object to a string.
Implements RDK2::Serialization::Writer.
Definition at line 82 of file binarywriter_recursion.cpp.
References writeObject().
Referenced by main().
void RDK2::Serialization::Binary::BinaryWriter::startWriting (cstr myClassName, unsigned char version) throw (WritingException) [virtual]
Writer interface
Implements RDK2::Serialization::Writer.
Definition at line 30 of file binarywriter_recursion.cpp.
void RDK2::Serialization::Binary::BinaryWriter::write_u8 (uint8_t , cstr name) throw (WritingException) [virtual]
Occhio alle conversioni automatiche quando chiamate una di queste due
Implements RDK2::Serialization::Writer.
Definition at line 39 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_u8().
void RDK2::Serialization::Binary::BinaryWriter::write_i8 (int8_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 42 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_i8().
void RDK2::Serialization::Binary::BinaryWriter::write_i16 (int16_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 45 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_i16().
void RDK2::Serialization::Binary::BinaryWriter::write_i32 (int32_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 48 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_i32().
void RDK2::Serialization::Binary::BinaryWriter::write_f32 (float32_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 51 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_f32().
void RDK2::Serialization::Binary::BinaryWriter::write_f64 (float64_t v, cstr name) throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 54 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_f64().
void RDK2::Serialization::Binary::BinaryWriter::write_u8 (const uint8_t * v, size_t n, cstr name = "") throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 61 of file binarywriter.cpp.
References writeBytes().
void RDK2::Serialization::Binary::BinaryWriter::write_i8 (const int8_t * v, size_t n, cstr name = "") throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 64 of file binarywriter.cpp.
References writeBytes().
void RDK2::Serialization::Binary::BinaryWriter::write_i16 (const int16_t * v, size_t n, cstr name = "") throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 67 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_i16().
void RDK2::Serialization::Binary::BinaryWriter::write_i32 (const int32_t * v, size_t n, cstr name = "") throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 70 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_i32().
void RDK2::Serialization::Binary::BinaryWriter::write_f32 (const float32_t * v, size_t n, cstr name = "") throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 73 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_f32().
void RDK2::Serialization::Binary::BinaryWriter::write_f64 (const float64_t * v, size_t n, cstr name = "") throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 76 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_f64().
void RDK2::Serialization::Binary::BinaryWriter::writeString (cstr s, cstr name) throw (WritingException) [virtual]
stringa tranquilla:
Implements RDK2::Serialization::Writer.
Definition at line 80 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_string().
void RDK2::Serialization::Binary::BinaryWriter::writeBytes (const void * , size_t n, cstr name) throw (WritingException) [virtual]
Scrittura di buffer.
Implements RDK2::Serialization::Writer.
Definition at line 58 of file binarywriter.cpp.
References RDK2::Serialization::Binary::packet_bytes().
Referenced by write_i8(), and write_u8().
void RDK2::Serialization::Binary::BinaryWriter::writeObject (bool needClassName, const Writable * w, cstr name = "") throw (WritingException) [virtual]
Scrittura di oggetti.
Implements RDK2::Serialization::Writer.
Definition at line 65 of file binarywriter_recursion.cpp.
References RDK2::Serialization::Binary::packet_objectWithClass(), and RDK2::Serialization::Binary::packet_objectWithoutClass().
Referenced by serialize().
void RDK2::Serialization::Binary::BinaryWriter::doneWriting () throw (WritingException) [virtual]
Implements RDK2::Serialization::Writer.
Definition at line 38 of file binarywriter_recursion.cpp.
The documentation for this class was generated from the following files:
binarywriter.h
binarywriter.cpp
binarywriter_recursion.cpp