OpenRDK: RDK2::RepositoryNS::RemoteSubscriptionRegister Class Reference
RDK2::RepositoryNS::RemoteSubscriptionRegister Class Reference
#include <remotesubscriptionregister.h>
Detailed Description
Definition at line 34 of file remotesubscriptionregister.h.
Public Member Functions
RemoteSubscriptionRegister (Repository *repository)
~RemoteSubscriptionRegister ()
vector< RRemoteSubscription > queryForPropertiesToSend (Url completeUrl, string askingHost, Network::NetProtocol, RRemoteSubscription::What, RRemoteSubscription::When)
Query for reading the register.
vector< RRemoteSubscription > queryForPropertiesToReceive (Url completeUrl, string askingHost, Network::NetProtocol, RRemoteSubscription::What, RRemoteSubscription::When)
void deleteSubscriptionToSend (uint id)
bool addPropertyToSendSubscription (RRemoteSubscription *sub)
void addPropertyToReceiveSubscription (Session *askingSession, RRemoteSubscription *sub)
void completePropertyToReceiveSubscription (RRemoteSubscription *sub)
void deleteAllSubscriptionsOfSession (Session *session)
void refreshLastSendingTimestamp (uint id)
Constructor & Destructor Documentation
RDK2::RepositoryNS::RemoteSubscriptionRegister::RemoteSubscriptionRegister (Repository * repository) [inline]
Definition at line 36 of file remotesubscriptionregister.h.
RDK2::RepositoryNS::RemoteSubscriptionRegister::~RemoteSubscriptionRegister () [inline]
Definition at line 37 of file remotesubscriptionregister.h.
Member Function Documentation
vector< RRemoteSubscription > RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToSend (Url completeUrl, string askingHost, Network::NetProtocol socketType, RRemoteSubscription::What what, RRemoteSubscription::When when)
Query for reading the register.
Definition at line 249 of file remotesubscriptionregister.cpp.
References RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::completeUrl, Network::NETPROTOCOL_ANY, RDK2::RepositoryNS::RRemoteSubscription::socketType, RDK2::RepositoryNS::RRemoteSubscription::what, RDK2::RepositoryNS::RRemoteSubscription::WHAT_ANY, RDK2::RepositoryNS::RRemoteSubscription::when, and RDK2::RepositoryNS::RRemoteSubscription::WHEN_ANY.
Referenced by addPropertyToSendSubscription(), RDK2::RepositoryNS::RemotePropertyManager::periodicSender(), RDK2::RepositoryNS::Repository::sendObjectsToRemoteQueueSubscribers(), RDK2::RepositoryNS::Repository::sendStorageValuesToRemoteValueSubscribers(), and RDK2::RepositoryNS::Repository::valueChanged().
vector< RRemoteSubscription > RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToReceive (Url completeUrl, string askingHost, Network::NetProtocol socketType, RRemoteSubscription::What what, RRemoteSubscription::When when)
Definition at line 268 of file remotesubscriptionregister.cpp.
References RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::completeUrl, DOUT, RDK2::RepositoryNS::RRemoteSubscription::getStringForVisualization(), Network::NETPROTOCOL_ANY, RDK2::RepositoryNS::RRemoteSubscription::socketType, RDK2::RepositoryNS::RRemoteSubscription::what, RDK2::RepositoryNS::RRemoteSubscription::WHAT_ANY, RDK2::RepositoryNS::RRemoteSubscription::when, and RDK2::RepositoryNS::RRemoteSubscription::WHEN_ANY.
Referenced by addPropertyToReceiveSubscription(), RDK2::RepositoryNS::Repository::getRemoteProperty(), and RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal().
void RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteSubscriptionToSend (uint id)
Deletes a subscription for a property to send
Parameters:
id the id of the subscription to delete
Definition at line 235 of file remotesubscriptionregister.cpp.
References HERE, PosixConstructs::PosixMutex::lock(), and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::RemotePropertyManager::periodicSender().
bool RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription (RRemoteSubscription * sub)
Note:
register now owns the subscription object
Definition at line 99 of file remotesubscriptionregister.cpp.
References RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::clone(), RDK2::RepositoryNS::RRemoteSubscription::completeUrl, DOUT, RDK2::RepositoryNS::Repository::getRepositoryName(), RDK2::RepositoryNS::RRemoteSubscription::getStringForVisualization(), HERE, RDK2::RepositoryNS::RRemoteSubscription::id, RDK2::RepositoryNS::Url::isComplete(), PosixConstructs::PosixMutex::lock(), PROPERTY_OUTBOX, RDK2::RNetObjects::RNetMessage::PROPERTY_SUBSCRIPTION, queryForPropertiesToSend(), RDK2::RepositoryNS::Repository::queuePush(), RDK_ERROR_PRINTF, RDK2::RepositoryNS::RRemoteSubscription::socketType, RDK2::RepositoryNS::RRemoteSubscription::timestamp, Network::UDP_IP, PosixConstructs::PosixMutex::unlock(), RDK2::RepositoryNS::RRemoteSubscription::what, and RDK2::RepositoryNS::RRemoteSubscription::when.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageSubscriptionMessage().
void RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription (Session * askingSession, RRemoteSubscription * sub)
Definition at line 187 of file remotesubscriptionregister.cpp.
References RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::completeUrl, DOUT, RDK2::RepositoryNS::Session::getSessionName(), RDK2::RepositoryNS::RRemoteSubscription::getStringForVisualization(), HERE, RDK2::RepositoryNS::RRemoteSubscription::id, RDK2::RepositoryNS::Url::isComplete(), PosixConstructs::PosixMutex::lock(), queryForPropertiesToReceive(), RDK_DEBUG_PRINTF, RDK_ERROR_PRINTF, RDK2::RepositoryNS::RRemoteSubscription::socketType, PosixConstructs::PosixMutex::unlock(), RDK2::RepositoryNS::RRemoteSubscription::what, and RDK2::RepositoryNS::RRemoteSubscription::when.
Referenced by RDK2::RepositoryNS::Repository::getRemoteProperty(), and RDK2::RepositoryNS::Repository::remotePropertyOptions().
void RDK2::RepositoryNS::RemoteSubscriptionRegister::completePropertyToReceiveSubscription (RRemoteSubscription * sub)
Definition at line 144 of file remotesubscriptionregister.cpp.
References RDK2::RepositoryNS::RRemoteSubscription::completeUrl, DOUT, RDK2::RepositoryNS::RRemoteSubscription::getStringForVisualization(), HERE, RDK2::RepositoryNS::RRemoteSubscription::id, RDK2::RepositoryNS::Url::isComplete(), PosixConstructs::PosixMutex::lock(), RDK_ERROR_PRINTF, and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::RemotePropertyManager::manageSubscriptionMessage().
void RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteAllSubscriptionsOfSession (Session * session)
Deletes all subscription asked by the session
Parameters:
session the session whose subscriptions have to be deleted
Definition at line 214 of file remotesubscriptionregister.cpp.
References DOUT, HERE, PosixConstructs::PosixMutex::lock(), and PosixConstructs::PosixMutex::unlock().
Referenced by RDK2::RepositoryNS::Session::~Session().
void RDK2::RepositoryNS::RemoteSubscriptionRegister::refreshLastSendingTimestamp (uint id)
Definition at line 177 of file remotesubscriptionregister.cpp.
Referenced by RDK2::RepositoryNS::Repository::sendStorageValuesToRemoteValueSubscribers().
The documentation for this class was generated from the following files:
remotesubscriptionregister.h
remotesubscriptionregister.cpp