OpenRDK: RDK2::RepositoryNS::RemotePropertyManager Class Reference
RDK2::RepositoryNS::RemotePropertyManager Class Reference
#include <remotepropertymanager.h>
Detailed Description
Definition at line 32 of file remotepropertymanager.h.
Public Member Functions
RemotePropertyManager (Repository *repository)
~RemotePropertyManager ()
bool init ()
bool start ()
Protected Member Functions
void receiver ()
void periodicSender ()
void periodicUdpRenewal ()
void manageUpdateMessage (const RNetMessage *msg) throw (SessionException)
void manageSubscriptionMessage (const RNetMessage *msg) throw (SessionException)
Static Protected Member Functions
static void * receiverThreadFn (RemotePropertyManager *me)
static void * periodicSenderThreadFn (RemotePropertyManager *me)
static void * periodicUdpRenewalThreadFn (RemotePropertyManager *me)
Protected Attributes
Repository *const repository
volatile bool exiting
pthread_t receiverThreadId
Session * receiverSession
pthread_t periodicSenderThreadId
Session * periodicSenderSession
pthread_t periodicUdpRenewalThreadId
Session * periodicUdpRenewalSession
Data Structures
class RemotePropertyManagerInterests
Constructor & Destructor Documentation
RDK2::RepositoryNS::RemotePropertyManager::RemotePropertyManager (Repository * repository)
Definition at line 51 of file remotepropertymanager.cpp.
RDK2::RepositoryNS::RemotePropertyManager::~RemotePropertyManager ()
Definition at line 315 of file remotepropertymanager.cpp.
References exiting, periodicSenderSession, periodicSenderThreadId, periodicUdpRenewalSession, periodicUdpRenewalThreadId, RDK_INFO_PRINTF, receiverSession, receiverThreadId, and RDK2::RepositoryNS::Session::wakeUp().
Member Function Documentation
bool RDK2::RepositoryNS::RemotePropertyManager::init ()
Definition at line 54 of file remotepropertymanager.cpp.
Referenced by RDK2::RepositoryNS::Repository::startRepositoryThreads().
bool RDK2::RepositoryNS::RemotePropertyManager::start ()
Definition at line 59 of file remotepropertymanager.cpp.
References RDK2::Common::createThread(), periodicSenderThreadFn(), periodicSenderThreadId, periodicUdpRenewalThreadFn(), periodicUdpRenewalThreadId, receiverThreadFn(), and receiverThreadId.
Referenced by RDK2::RepositoryNS::Repository::startRepositoryThreads().
static void* RDK2::RepositoryNS::RemotePropertyManager::receiverThreadFn (RemotePropertyManager * me) [inline, static, protected]
Definition at line 45 of file remotepropertymanager.h.
References receiver().
Referenced by start().
void RDK2::RepositoryNS::RemotePropertyManager::receiver () [protected]
Definition at line 70 of file remotepropertymanager.cpp.
References RDK2::RepositoryNS::Repository::createSession(), DOUT, RDK2::RepositoryNS::Session::end(), exiting, RDK2::RNetObjects::RNetMessage::getType(), RDK2::RepositoryNS::Session::listen(), manageSubscriptionMessage(), manageUpdateMessage(), PROPERTY_INBOX, RDK2::RNetObjects::RNetMessage::PROPERTY_SUBSCRIPTION, RDK2::RNetObjects::RNetMessage::PROPERTY_UPDATE, RDK2::RepositoryNS::Session::queueFreeze(), RDK2::RepositoryNS::Session::queueSetInterests(), RDK2::RepositoryNS::Session::queueSubscribe(), RDK2::RepositoryNS::Session::queueUnsubscribe(), RDK_ERROR_PRINTF, RDK_ERROR_STREAM, RDK_INFO_PRINTF, receiverSession, repository, SESSION_END_CATCH_TERMINATE, SESSION_TRY_START, RDK2::RepositoryNS::Session::start(), RDK2::RepositoryNS::Session::terminate(), and RDK2::RepositoryNS::Session::wait().
Referenced by receiverThreadFn().
static void* RDK2::RepositoryNS::RemotePropertyManager::periodicSenderThreadFn (RemotePropertyManager * me) [inline, static, protected]
Definition at line 50 of file remotepropertymanager.h.
References periodicSender().
Referenced by start().
void RDK2::RepositoryNS::RemotePropertyManager::periodicSender () [protected]
Definition at line 238 of file remotepropertymanager.cpp.
References RDK2::RepositoryNS::Repository::createSession(), RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteSubscriptionToSend(), DOUT, exiting, RDK2::RepositoryNS::Session::getDouble(), Network::NETPROTOCOL_ANY, RDK2::RepositoryNS::RRemoteSubscription::PERIODIC, periodicSenderSession, PROPERTY_UDP_RENEWAL_TIMEOUT, RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToSend(), RDK_INFO_PRINTF, RDK2::RepositoryNS::Repository::remoteSubscriptionRegister, repository, RDK2::RepositoryNS::Repository::sendStorageValuesToRemoteValueSubscribers(), SESSION_END_CATCH_TERMINATE, SESSION_TRY_START, RDK2::RepositoryNS::RRemoteSubscription::STORAGE_DIFFS, RDK2::RepositoryNS::RRemoteSubscription::STORAGE_VALUE, Network::UDP_IP, RDK2::RepositoryNS::RRemoteSubscription::WHAT_ANY, and RDK2::RepositoryNS::RRemoteSubscription::WHEN_ANY.
Referenced by periodicSenderThreadFn().
static void* RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewalThreadFn (RemotePropertyManager * me) [inline, static, protected]
Definition at line 55 of file remotepropertymanager.h.
References periodicUdpRenewal().
Referenced by start().
void RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal () [protected]
Definition at line 286 of file remotepropertymanager.cpp.
References RDK2::RepositoryNS::Repository::createSession(), DOUT, exiting, RDK2::RepositoryNS::Session::getDouble(), RDK2::RepositoryNS::Session::getRepositoryName(), periodicUdpRenewalSession, PROPERTY_OUTBOX, RDK2::RNetObjects::RNetMessage::PROPERTY_SUBSCRIPTION, PROPERTY_UDP_RENEWAL_INTERVAL, RDK2::RepositoryNS::RemoteSubscriptionRegister::queryForPropertiesToReceive(), RDK2::RepositoryNS::Session::queuePush(), RDK_INFO_PRINTF, RDK2::RepositoryNS::Repository::remoteSubscriptionRegister, repository, SESSION_END_CATCH_TERMINATE, SESSION_TRY_START, Network::UDP_IP, RDK2::RepositoryNS::RRemoteSubscription::WHAT_ANY, and RDK2::RepositoryNS::RRemoteSubscription::WHEN_ANY.
Referenced by periodicUdpRenewalThreadFn().
void RDK2::RepositoryNS::RemotePropertyManager::manageUpdateMessage (const RNetMessage * msg) throw (SessionException) [protected]
Definition at line 124 of file remotepropertymanager.cpp.
References RDK2::Object::applyDiff(), RDK2::Object::clone(), RDK2::RepositoryNS::RPropertyUpdate::completeUrl, RDK2::Geometry::diff(), RDK2::RepositoryNS::RPropertyUpdate::DIFF, DOUT, RDK2::RepositoryNS::RPropertyUpdate::ENQUEUE, RDK2::Demangle::Reflective::getClassName(), RDK2::RepositoryNS::Property::getObjectClassName(), RDK2::RepositoryNS::Repository::getObjectOrCreateItL(), RDK2::RepositoryNS::Repository::getRemoteProperty(), HERE, RDK2::RepositoryNS::Url::isComplete(), RDK2::RepositoryNS::Repository::lock(), RDK2::RepositoryNS::RPropertyUpdate::object, RDK2::Meta::ObjectDiff::objectClassName, RDK2::RepositoryNS::Repository::pushDiffInDiffQueue(), RDK2::RepositoryNS::Repository::queuePush(), RDK_ERROR_PRINTF, repository, RDK2::RepositoryNS::Repository::setObject(), RDK2::RepositoryNS::Property::setObjectClassName(), RDK2::RepositoryNS::RPropertyUpdate::type, RDK2::RepositoryNS::Repository::unlock(), RDK2::RepositoryNS::RPropertyUpdate::VALUE, and RDK2::RepositoryNS::Repository::wakeUpListeningSessions().
Referenced by receiver().
void RDK2::RepositoryNS::RemotePropertyManager::manageSubscriptionMessage (const RNetMessage * msg) throw (SessionException) [protected]
Definition at line 183 of file remotepropertymanager.cpp.
References RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription(), RDK2::RepositoryNS::RRemoteSubscription::askingHost, RDK2::RepositoryNS::RRemoteSubscription::clone(), RDK2::RepositoryNS::RemoteSubscriptionRegister::completePropertyToReceiveSubscription(), RDK2::RepositoryNS::RRemoteSubscription::completeUrl, DOUT, RDK2::RepositoryNS::Url::getHost(), RDK2::RepositoryNS::RRemoteSubscription::ON_CHANGE, RDK_ERROR_PRINTF, RDK2::RepositoryNS::Repository::remoteSubscriptionRegister, repository, RDK2::RepositoryNS::Repository::sendStorageValueToHost(), RDK2::RepositoryNS::RRemoteSubscription::socketType, and RDK2::RepositoryNS::RRemoteSubscription::when.
Referenced by receiver().
Field Documentation
Repository* const RDK2::RepositoryNS::RemotePropertyManager::repository [protected]
Definition at line 41 of file remotepropertymanager.h.
Referenced by manageSubscriptionMessage(), manageUpdateMessage(), periodicSender(), periodicUdpRenewal(), and receiver().
volatile bool RDK2::RepositoryNS::RemotePropertyManager::exiting [protected]
Definition at line 43 of file remotepropertymanager.h.
Referenced by periodicSender(), periodicUdpRenewal(), receiver(), and ~RemotePropertyManager().
pthread_t RDK2::RepositoryNS::RemotePropertyManager::receiverThreadId [protected]
Definition at line 47 of file remotepropertymanager.h.
Referenced by start(), and ~RemotePropertyManager().
Session* RDK2::RepositoryNS::RemotePropertyManager::receiverSession [protected]
Definition at line 48 of file remotepropertymanager.h.
Referenced by receiver(), and ~RemotePropertyManager().
pthread_t RDK2::RepositoryNS::RemotePropertyManager::periodicSenderThreadId [protected]
Definition at line 52 of file remotepropertymanager.h.
Referenced by start(), and ~RemotePropertyManager().
Session* RDK2::RepositoryNS::RemotePropertyManager::periodicSenderSession [protected]
Definition at line 53 of file remotepropertymanager.h.
Referenced by periodicSender(), and ~RemotePropertyManager().
pthread_t RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewalThreadId [protected]
Definition at line 57 of file remotepropertymanager.h.
Referenced by start(), and ~RemotePropertyManager().
Session* RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewalSession [protected]
Definition at line 58 of file remotepropertymanager.h.
Referenced by periodicUdpRenewal(), and ~RemotePropertyManager().
The documentation for this class was generated from the following files:
remotepropertymanager.h
remotepropertymanager.cpp