OpenRDK: RDK2::Geometry::QuadWalk Class Reference
RDK2::Geometry::QuadWalk Class Reference
#include <walk_quad.h>
Detailed Description
Definition at line 33 of file walk_quad.h.
Public Member Functions
QuadWalk (Point2i p1, Point2i p2, Point2i p3, Point2i p4)
bool next ()
Point2i getPoint () const
void rewind ()
Constructor & Destructor Documentation
RDK2::Geometry::QuadWalk::QuadWalk (Point2i p1, Point2i p2, Point2i p3, Point2i p4)
Definition at line 79 of file walk_quad.cpp.
References RDK2::Geometry::max(), RDK2::Geometry::min(), rewind(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Member Function Documentation
bool RDK2::Geometry::QuadWalk::next ()
Definition at line 262 of file walk_quad.cpp.
References RDK2::Geometry::LineWalk::next().
Referenced by rewind().
Point2i RDK2::Geometry::QuadWalk::getPoint () const
Definition at line 300 of file walk_quad.cpp.
References RDK2::Geometry::LineWalk::getPoint().
void RDK2::Geometry::QuadWalk::rewind ()
Definition at line 284 of file walk_quad.cpp.
References next(), and RDK2::Geometry::LineWalk::rewind().
Referenced by QuadWalk().
The documentation for this class was generated from the following files:
walk_quad.h
walk_quad.cpp