OpenRDK: RDK2::RGraphics::RImageDiffRect Class Reference
RDK2::RGraphics::RImageDiffRect Class Reference
#include <rimagediffrect.h>
Detailed Description
Definition at line 32 of file rimagediffrect.h.
Public Member Functions
RImageDiffRect ()
RImageDiffRect (RImage *image, int left, int top, int width, int height)
RImageDiffRect (RImageDiffRect *imagediffRect, int left, int top, int width, int height)
virtual ~RImageDiffRect ()
void read (RDK2::Reader *r) throw (RDK2::ReadingException)
void write (RDK2::Writer *w) const throw (RDK2::WritingException)
RDK2::Object * clone () const
virtual vector< ObjectDiff * > split (size_t maxBufferSize)
uint8_t ** getPixels ()
uint8_t * getBuffer ()
size_t getCBufSize ()
Data Fields
int rectLeft
int rectTop
int rectWidth
int rectHeight
int refImageWidth
int refImageHeight
RImage::Type refImageType
Friends
class RImage
Constructor & Destructor Documentation
RDK2::RGraphics::RImageDiffRect::RImageDiffRect ()
Definition at line 68 of file rimagediffrect.cpp.
Referenced by clone(), and split().
RDK2::RGraphics::RImageDiffRect::RImageDiffRect (RImage * image, int left, int top, int width, int height)
Definition at line 30 of file rimagediffrect.cpp.
References RDK2::RGraphics::RImage::getBuffer(), RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getType(), RDK2::RGraphics::RImage::getWidth(), rectHeight, and rectWidth.
RDK2::RGraphics::RImageDiffRect::RImageDiffRect (RImageDiffRect * imagediffRect, int left, int top, int width, int height)
Definition at line 48 of file rimagediffrect.cpp.
References buffer, rectHeight, rectWidth, and refImageType.
RDK2::RGraphics::RImageDiffRect::~RImageDiffRect () [virtual]
Definition at line 168 of file rimagediffrect.cpp.
Member Function Documentation
void RDK2::RGraphics::RImageDiffRect::read (RDK2::Reader * r) throw (RDK2::ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 97 of file rimagediffrect.cpp.
References RDK2::Demangle::Reflective::getClassName(), RDK2::Meta::ObjectDiff::objectClassName, RDK2::Statistics::r, rectHeight, rectLeft, rectTop, rectWidth, refImageHeight, refImageType, refImageWidth, and RDK2::RGraphics::uncompressImgDiffCBuf().
void RDK2::RGraphics::RImageDiffRect::write (RDK2::Writer *) const throw (RDK2::WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 117 of file rimagediffrect.cpp.
References RDK2::RGraphics::compressImgLine(), RDK2::Demangle::Reflective::getClassName(), RDK2::Meta::ObjectDiff::objectClassName, RDK_DEBUG_PRINTF, rectHeight, rectLeft, rectTop, rectWidth, refImageHeight, refImageType, and refImageWidth.
RDK2::Object * RDK2::RGraphics::RImageDiffRect::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 86 of file rimagediffrect.cpp.
References buffer, copyRect(), initBuffer(), rectHeight, rectWidth, refImageType, RImageDiffRect(), and rows.
Referenced by RDK2::RMaps::RMapImageDiffRect::clone().
vector< ObjectDiff * > RDK2::RGraphics::RImageDiffRect::split (size_t maxBufferSize) [virtual]
Implements RDK2::Meta::ObjectDiff.
Definition at line 142 of file rimagediffrect.cpp.
References cBuf, RDK2::RGraphics::compressImgLine(), rectHeight, rectWidth, refImageType, and RImageDiffRect().
Referenced by RDK2::RMaps::RMapImageDiffRect::split(), and RDK2::RGraphics::RImage::splitInDiffs().
uint8_t ** RDK2::RGraphics::RImageDiffRect::getPixels ()
Definition at line 74 of file rimagediffrect.cpp.
Referenced by RDK2::RGraphics::uncompressImgDiffCBuf().
uint8_t * RDK2::RGraphics::RImageDiffRect::getBuffer ()
Definition at line 80 of file rimagediffrect.cpp.
size_t RDK2::RGraphics::RImageDiffRect::getCBufSize () [inline]
Definition at line 53 of file rimagediffrect.h.
Friends And Related Function Documentation
friend class RImage [friend]
Definition at line 63 of file rimagediffrect.h.
Field Documentation
int RDK2::RGraphics::RImageDiffRect::rectLeft
Definition at line 46 of file rimagediffrect.h.
Referenced by read(), and write().
int RDK2::RGraphics::RImageDiffRect::rectTop
Definition at line 46 of file rimagediffrect.h.
Referenced by read(), and write().
int RDK2::RGraphics::RImageDiffRect::rectWidth
Definition at line 46 of file rimagediffrect.h.
Referenced by clone(), read(), RImageDiffRect(), split(), RDK2::RGraphics::uncompressImgDiffCBuf(), and write().
int RDK2::RGraphics::RImageDiffRect::rectHeight
Definition at line 46 of file rimagediffrect.h.
Referenced by clone(), read(), RImageDiffRect(), split(), RDK2::RGraphics::uncompressImgDiffCBuf(), and write().
int RDK2::RGraphics::RImageDiffRect::refImageWidth
Definition at line 47 of file rimagediffrect.h.
Referenced by RDK2::RGraphics::RImage::applyDiff(), read(), and write().
int RDK2::RGraphics::RImageDiffRect::refImageHeight
Definition at line 47 of file rimagediffrect.h.
Referenced by RDK2::RGraphics::RImage::applyDiff(), read(), and write().
RImage::Type RDK2::RGraphics::RImageDiffRect::refImageType
Definition at line 48 of file rimagediffrect.h.
Referenced by RDK2::RGraphics::RImage::applyDiff(), clone(), read(), RImageDiffRect(), split(), RDK2::RGraphics::uncompressImgDiffCBuf(), and write().
The documentation for this class was generated from the following files:
rimagediffrect.h
rimagediffrect.cpp