OpenRDK: PosixConstructs::PosixMutex Class Reference
PosixConstructs::PosixMutex Class Reference
#include <posixmutex.h>
Detailed Description
Note: a mutex locked by a thread MUST be unlocked by the same thread
Definition at line 30 of file posixmutex.h.
Public Member Functions
PosixMutex (bool initMutexOnDemand=true)
PosixMutex (const PosixMutex &)
const PosixMutex & operator= (const PosixMutex &rhs)
~PosixMutex ()
void lock (const char *why, const char *file, int line) const
void lock (Stack) const
void unlock () const
Constructor & Destructor Documentation
PosixConstructs::PosixMutex::PosixMutex (bool initMutexOnDemand = true)
Definition at line 31 of file posixmutex.cpp.
PosixConstructs::PosixMutex::PosixMutex (const PosixMutex &)
Definition at line 141 of file posixmutex.cpp.
PosixConstructs::PosixMutex::~PosixMutex ()
Definition at line 135 of file posixmutex.cpp.
Member Function Documentation
const PosixMutex & PosixConstructs::PosixMutex::operator= (const PosixMutex & rhs)
Definition at line 145 of file posixmutex.cpp.
void PosixConstructs::PosixMutex::lock (const char * why, const char * file, int line) const
Definition at line 122 of file posixmutex.cpp.
Referenced by RDK2::Profiling::Profiler::addCustomLine(), RDK2::RepositoryNS::Repository::addGenericProperty(), RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription(), RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription(), RDK2::RAgent::ModuleManager::cleanupAllModules(), RDK2::RepositoryNS::RemoteSubscriptionRegister::completePropertyToReceiveSubscription(), RDK2::RepositoryNS::Session::createEnum(), RDK2::RepositoryNS::Session::createStorage(), RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteAllSubscriptionsOfSession(), RDK2::RepositoryNS::Session::deleteProperty(), RDK2::RepositoryNS::Repository::deleteProperty(), RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteSubscriptionToSend(), RDK2::RAgent::ModuleManager::endAllModules(), RDK2::RepositoryNS::Session::getEnumString(), RDK2::RepositoryNS::Repository::getLocalPropertiesStartingWith(), RDK2::RepositoryNS::Repository::getLocalPropertyNames(), RDK2::RAgent::ModuleManager::getModuleConfigs(), RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Repository::getProperty(), RDK2::RepositoryNS::Session::getPropertyClassName(), RDK2::RepositoryNS::Session::getPropertyDescription(), RDK2::RepositoryNS::Session::getPropertyEnumItems(), RDK2::RepositoryNS::Session::getPropertyLinkTo(), RDK2::RepositoryNS::Session::getPropertyNamesStartingWith(), RDK2::RepositoryNS::Repository::getRemoteProperty(), RDK2::RepositoryNS::Repository::getRemotePropertyNames(), RDK2::RepositoryNS::Session::getRPropertyDef(), RDK2::RepositoryNS::Session::getValue(), RDK2::RAgent::ModuleManager::initAllModules(), RDK2::RepositoryNS::Repository::lock(), RDK2::RepositoryNS::Session::lockAndGetProperty(), RDK2::RepositoryNS::Repository::queuePush(), RDK2::RepositoryNS::Repository::saveAllDefaultPropertyDefs(), RDK2::RepositoryNS::Property::setObject(), RDK2::RepositoryNS::Property::setPersistent(), RDK2::RepositoryNS::Session::setPropertyOptions(), RDK2::RepositoryNS::Property::setReadonly(), RDK2::RepositoryNS::Repository::setRemotePropertyDef(), RDK2::RAgent::ModuleManager::startAllModules(), RDK2::RepositoryNS::Repository::timerThread(), RDK2::RepositoryNS::Repository::~Repository(), and RDK2::RepositoryNS::Session::~Session().
void PosixConstructs::PosixMutex::lock (Stack nextStack) const
Definition at line 95 of file posixmutex.cpp.
References RDK_ERROR_STREAM, and PosixConstructs::Stack::toString().
void PosixConstructs::PosixMutex::unlock () const
Definition at line 126 of file posixmutex.cpp.
References RDK_ERROR_STREAM.
Referenced by RDK2::Profiling::Profiler::addCustomLine(), RDK2::RepositoryNS::Repository::addGenericProperty(), RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription(), RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToSendSubscription(), RDK2::RAgent::ModuleManager::cleanupAllModules(), RDK2::RepositoryNS::RemoteSubscriptionRegister::completePropertyToReceiveSubscription(), RDK2::RepositoryNS::Session::createEnum(), RDK2::RepositoryNS::Session::createStorage(), RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteAllSubscriptionsOfSession(), RDK2::RepositoryNS::Session::deleteProperty(), RDK2::RepositoryNS::Repository::deleteProperty(), RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteSubscriptionToSend(), RDK2::RAgent::ModuleManager::endAllModules(), RDK2::RepositoryNS::Session::getEnumString(), RDK2::RepositoryNS::Repository::getLocalPropertiesStartingWith(), RDK2::RepositoryNS::Repository::getLocalPropertyNames(), RDK2::RAgent::ModuleManager::getModuleConfigs(), RDK2::RepositoryNS::Session::getProperty(), RDK2::RepositoryNS::Repository::getProperty(), RDK2::RepositoryNS::Session::getPropertyClassName(), RDK2::RepositoryNS::Session::getPropertyDescription(), RDK2::RepositoryNS::Session::getPropertyEnumItems(), RDK2::RepositoryNS::Session::getPropertyLinkTo(), RDK2::RepositoryNS::Session::getPropertyNamesStartingWith(), RDK2::RepositoryNS::Repository::getRemotePropertyNames(), RDK2::RepositoryNS::Session::getRPropertyDef(), RDK2::RepositoryNS::Session::getValue(), RDK2::RAgent::ModuleManager::initAllModules(), RDK2::RepositoryNS::Session::lockAndGetProperty(), RDK2::RepositoryNS::Repository::queuePush(), RDK2::RepositoryNS::Repository::saveAllDefaultPropertyDefs(), RDK2::RepositoryNS::Property::setObject(), RDK2::RepositoryNS::Property::setPersistent(), RDK2::RepositoryNS::Session::setPropertyOptions(), RDK2::RepositoryNS::Property::setReadonly(), RDK2::RepositoryNS::Repository::setRemotePropertyDef(), RDK2::RAgent::ModuleManager::startAllModules(), RDK2::RepositoryNS::Repository::timerThread(), RDK2::RepositoryNS::Repository::unlock(), RDK2::RepositoryNS::Session::unlockProperty(), RDK2::RepositoryNS::Repository::~Repository(), and RDK2::RepositoryNS::Session::~Session().
The documentation for this class was generated from the following files:
posixmutex.h
posixmutex.cpp