OpenRDK: RDK2::UnitTest::Serialization::SerializationTest1< X > Class Template Reference
RDK2::UnitTest::Serialization::SerializationTest1< X > Class Template Reference
#include <test1.h>
Detailed Description
template<class X>
class RDK2::UnitTest::Serialization::SerializationTest1< X >
Serialize
Compare to file (create if not exists)
Create another instance, deserialize, serialize, compare X should have empty constructor
Definition at line 44 of file test1.h.
Public Member Functions
SerializationTest1 (std::string name, X *x, Writer *w, Reader *r, cstr file)
void runTest ()
Data Fields
X * x
Writer * w
Reader * r
string file
Constructor & Destructor Documentation
template<class X> RDK2::UnitTest::Serialization::SerializationTest1< X >::SerializationTest1 (std::string name, X * x, Writer * w, Reader * r, cstr file) [inline]
Definition at line 48 of file test1.h.
Member Function Documentation
template<class X> void RDK2::UnitTest::Serialization::SerializationTest1< X >::runTest () [inline]
Definition at line 52 of file test1.h.
References compareToFile(), RDK2::Serialization::Reader::deserialize(), RDK2::UnitTest::Serialization::SerializationTest1< X >::file, RDK2::UnitTest::Serialization::SerializationTest1< X >::r, RDK2::Serialization::Writer::serialize(), RDK2::UnitTest::Serialization::SerializationTest1< X >::w, and RDK2::UnitTest::Serialization::SerializationTest1< X >::x.
Field Documentation
template<class X> X* RDK2::UnitTest::Serialization::SerializationTest1< X >::x
Definition at line 46 of file test1.h.
Referenced by RDK2::UnitTest::Serialization::SerializationTest1< X >::runTest().
template<class X> Writer* RDK2::UnitTest::Serialization::SerializationTest1< X >::w
Definition at line 46 of file test1.h.
Referenced by RDK2::UnitTest::Serialization::SerializationTest1< X >::runTest().
template<class X> Reader* RDK2::UnitTest::Serialization::SerializationTest1< X >::r
Definition at line 46 of file test1.h.
Referenced by RDK2::UnitTest::Serialization::SerializationTest1< X >::runTest().
template<class X> string RDK2::UnitTest::Serialization::SerializationTest1< X >::file
Definition at line 46 of file test1.h.
Referenced by RDK2::UnitTest::Serialization::SerializationTest1< X >::runTest().
The documentation for this class was generated from the following file:
test1.h