OpenRDK: RDK2::SensorData::LogReader Class Reference
RDK2::SensorData::LogReader Class Reference
#include <logreader.h>
Detailed Description
Definition at line 52 of file logreader.h.
Public Member Functions
LogReader (std::istream *is, std::ostream *os=NULL)
void addParser (Parser *p)
BaseSensorData * parse (const std::string &s, std::string *error=NULL)
bool write (const BaseSensorData *sd, std::string &line, std::string *error=NULL)
bool write (const BaseSensorData *sd)
template<class X>
bool getNext (X &c)
template<class X>
void getAll (std::vector< X > &v)
Constructor & Destructor Documentation
RDK2::SensorData::LogReader::LogReader (std::istream * is, std::ostream * os = NULL)
Definition at line 30 of file logreader.cpp.
References addParser().
Member Function Documentation
void RDK2::SensorData::LogReader::addParser (Parser * p) [inline]
Definition at line 57 of file logreader.h.
References RDK2::SensorData::Parser::getTag().
Referenced by LogReader().
BaseSensorData * RDK2::SensorData::LogReader::parse (const std::string & s, std::string * error = NULL)
Parses a line of log. Returns 0 if ignored.
Definition at line 35 of file logreader.cpp.
References RDK2::SensorData::Unknown::line, and RDK2::SensorData::BaseSensorData::tag.
Referenced by getNext().
bool RDK2::SensorData::LogReader::write (const BaseSensorData * sd, std::string & line, std::string * error = NULL)
Definition at line 53 of file logreader.cpp.
References RDK2::SensorData::Unknown::line, and RDK2::SensorData::BaseSensorData::tag.
Referenced by getNext(), and write().
bool RDK2::SensorData::LogReader::write (const BaseSensorData * sd) [inline]
Definition at line 64 of file logreader.h.
References RDK2::SensorData::BaseSensorData::tag, and write().
template<class X> bool RDK2::SensorData::LogReader::getNext (X & c) [inline]
Definition at line 79 of file logreader.h.
References RDK2::TextUtils::LineStream::getLine(), parse(), RDK2::TextUtils::LineStream::readLine(), RDK2::SensorData::BaseSensorData::tag, and write().
Referenced by getAll().
template<class X> void RDK2::SensorData::LogReader::getAll (std::vector< X > & v) [inline]
Definition at line 108 of file logreader.h.
References getNext().
The documentation for this class was generated from the following files:
logreader.h
logreader.cpp