OpenRDK: RDK2::Geometry::Point3< Numeric > Class Template Reference
RDK2::Geometry::Point3< Numeric > Class Template Reference
#include <point3.h>
Detailed Description
template<typename Numeric>
class RDK2::Geometry::Point3< Numeric >
Definition at line 28 of file point3.h.
Public Member Functions
Point3 ()
Point3 (Numeric x, Numeric y, Numeric z)
Point3 (const Point3< Numeric > &p)
Point3 operator- (const Point3< Numeric > &p) const
Point3 operator+ (const Point3< Numeric > &p) const
Point3 operator* (const Numeric &n) const
Numeric operator* (const Point3 &p) const
bool operator== (const Point3 &p) const
bool operator!= (const Point3 &p) const
Point3< Numeric > cross (const Point3< Numeric > &p) const
Numeric mod () const
Numeric mod2 () const
Numeric distTo (const Point3< Numeric > &p) const
std::string toString () const
Data Fields
Numeric z
Constructor & Destructor Documentation
template<typename Numeric> RDK2::Geometry::Point3< Numeric >::Point3 () [inline]
Definition at line 32 of file point3.h.
Referenced by RDK2::Geometry::Point3< double >::operator*(), RDK2::Geometry::Point3< double >::operator+(), and RDK2::Geometry::Point3< double >::operator-().
template<typename Numeric> RDK2::Geometry::Point3< Numeric >::Point3 (Numeric x, Numeric y, Numeric z) [inline]
Definition at line 33 of file point3.h.
template<typename Numeric> RDK2::Geometry::Point3< Numeric >::Point3 (const Point3< Numeric > & p) [inline]
Definition at line 34 of file point3.h.
Member Function Documentation
template<typename Numeric> Point3 RDK2::Geometry::Point3< Numeric >::operator- (const Point3< Numeric > & p) const [inline]
Definition at line 36 of file point3.h.
template<typename Numeric> Point3 RDK2::Geometry::Point3< Numeric >::operator+ (const Point3< Numeric > & p) const [inline]
Definition at line 38 of file point3.h.
template<typename Numeric> Point3 RDK2::Geometry::Point3< Numeric >::operator* (const Numeric & n) const [inline]
Multiplies components by n.
Reimplemented from RDK2::Geometry::Point2< Numeric >.
Definition at line 41 of file point3.h.
template<typename Numeric> Numeric RDK2::Geometry::Point3< Numeric >::operator* (const Point3< Numeric > & p) const [inline]
Definition at line 43 of file point3.h.
template<typename Numeric> bool RDK2::Geometry::Point3< Numeric >::operator== (const Point3< Numeric > & p) const [inline]
Definition at line 44 of file point3.h.
template<typename Numeric> bool RDK2::Geometry::Point3< Numeric >::operator!= (const Point3< Numeric > & p) const [inline]
Definition at line 45 of file point3.h.
template<typename Numeric> Point3<Numeric> RDK2::Geometry::Point3< Numeric >::cross (const Point3< Numeric > & p) const [inline]
Returns vector product
Definition at line 48 of file point3.h.
template<typename Numeric> Numeric RDK2::Geometry::Point3< Numeric >::mod () const [inline]
Returns L2-norm of vector.
Reimplemented from RDK2::Geometry::Point2< Numeric >.
Definition at line 53 of file point3.h.
Referenced by RDK2::Geometry::Quaternion< double >::rotate().
template<typename Numeric> Numeric RDK2::Geometry::Point3< Numeric >::mod2 () const [inline]
Returns L2-norm of vector, squared.
Reimplemented from RDK2::Geometry::Point2< Numeric >.
Definition at line 56 of file point3.h.
Referenced by RDK2::Geometry::Point3< double >::mod().
template<typename Numeric> Numeric RDK2::Geometry::Point3< Numeric >::distTo (const Point3< Numeric > & p) const [inline]
Definition at line 58 of file point3.h.
template<typename Numeric> std::string RDK2::Geometry::Point3< Numeric >::toString () const [inline]
A string representation. Example: "(1,2)".
Reimplemented from RDK2::Geometry::Point2< Numeric >.
Definition at line 60 of file point3.h.
Field Documentation
template<typename Numeric> Numeric RDK2::Geometry::Point3< Numeric >::z
Definition at line 30 of file point3.h.
Referenced by RDK2::Geometry::Point3< double >::cross(), RDK2::Geometry::Point3< double >::mod2(), RDK2::Geometry::Point3< double >::operator*(), RDK2::Geometry::operator*(), RDK2::Geometry::Point3< double >::operator+(), RDK2::Geometry::Point3< double >::operator-(), RDK2::Geometry::Point3< double >::operator==(), and RDK2::Geometry::Trans3d().
The documentation for this class was generated from the following file:
point3.h