OpenRDK: RDK2::RNetObjects::RYellowPages Class Reference
RDK2::RNetObjects::RYellowPages Class Reference
#include <ryellowpages.h>
Detailed Description
Contains known hosts.
For compatibility for ALL socket type, all the data pass as sockadrr. This class can be copied without problems, since there aren't pointer by now
/author Alberto Ingenito (alberto.ing@gmail.com)
Definition at line 41 of file ryellowpages.h.
Public Types
typedef std::map
< Network::NetProtocol,
std::map< std::string,
Network::SocketAddress > > YPHostMap
Public Member Functions
RDK2_DEFAULT_CLONE (RYellowPages)
bool newHost (Network::NetProtocol socket, const std::string &name, const Network::SocketAddress &address)
Insert a new host (True if the host is really inserted).
bool eraseHost (Network::NetProtocol socket, const std::string &name)
Delete a host address (True if the host is really deleted).
bool loadFromFile (const std::string &fileName)
Load the host list from file.
bool getSocketAddress (Network::NetProtocol socket, const std::string &name, Network::SocketAddress &address) const
Get host address trought given socket e name (logaritmic time implementation).
const std::map
< Network::NetProtocol,
std::map< std::string,
Network::SocketAddress > > & getMap () const
Take the complete host list.
Member Typedef Documentation
typedef std::map<Network::NetProtocol, std::map< std::string, Network::SocketAddress > > RDK2::RNetObjects::RYellowPages::YPHostMap
Definition at line 51 of file ryellowpages.h.
Member Function Documentation
RDK2::RNetObjects::RYellowPages::RDK2_DEFAULT_CLONE (RYellowPages)
bool RDK2::RNetObjects::RYellowPages::newHost (Network::NetProtocol socket, const std::string & name, const Network::SocketAddress & address)
Insert a new host (True if the host is really inserted).
Definition at line 35 of file ryellowpages.cpp.
bool RDK2::RNetObjects::RYellowPages::eraseHost (Network::NetProtocol socket, const std::string & name)
Delete a host address (True if the host is really deleted).
Definition at line 43 of file ryellowpages.cpp.
bool RDK2::RNetObjects::RYellowPages::loadFromFile (const std::string & fileName)
Load the host list from file.
Definition at line 47 of file ryellowpages.cpp.
References Network::NetException::fullwhat(), RDK_ERROR_STREAM, RDK_INFO_STREAM, and Network::stringToNetProtocol().
Referenced by RDK2::RepositoryNS::Repository::loadYellowPages().
bool RDK2::RNetObjects::RYellowPages::getSocketAddress (Network::NetProtocol socket, const std::string & name, Network::SocketAddress & address) const
Get host address trought given socket e name (logaritmic time implementation).
Definition at line 95 of file ryellowpages.cpp.
Referenced by RDK2::RepositoryNS::Session::getInetAddressOf(), RDK2::RepositoryNS::UdpManager::init(), and RDK2::RepositoryNS::TcpManager::init().
const std::map< Network::NetProtocol, std::map< std::string, Network::SocketAddress > > & RDK2::RNetObjects::RYellowPages::getMap () const
Take the complete host list.
Definition at line 110 of file ryellowpages.cpp.
The documentation for this class was generated from the following files:
ryellowpages.h
ryellowpages.cpp