OpenRDK: RDK2::RepositoryNS::Session Class Reference
RDK2::RepositoryNS::Session Class Reference
#include <session.h>
Detailed Description
The Session is The Way you have to access the repository.
Depending on the type of data you want to access, you will need to call different methods of this class.
Note that all methods ending with "L" need the property to be locked in advance.
Definition at line 92 of file session.h.
Text config file utilities
bool threadIdInitialized
pthread_t threadId
TimerT sessionActivityTimer
TimerR sessionScheduleTimer
double sessionCurrentScheduleInterval
vector< double > sessionActivityCache
vector< double > sessionScheduleCache
Url urlContext
Repository *const repository
string sessionName
string description
bool started
PosixConstructs::PosixSemaphore sessionSemaphore
PosixQueues::PipeQueue< Event > * eventQueue
PosixQueues::PipeQueueConsumer
< Event > * consumerEventQueue
vector< const Event * > currentEvents
map< Url, vector< ObjectDiff * > > pendingDiffs
set< string > lockedProperties
PosixConstructs::PosixMutex ownedPropertiesMutex
set< Url > ownedProperties
PosixConstructs::PosixMutex queueSubscriptionsMutex
map< Url, QueueSubscription > queueSubscriptions
map< Url, QueueSubscription > diffsSubscriptions
volatile bool exiting
class Repository
void checkStarted () throw (InvalidOperation)
Property * getProperty (cstr url, bool followLinks=true) throw (NoSuchProperty, InvalidOperation)
map< Url, QueueSubscription >
::iterator queueGetSubscription (CUrl url, bool alsoCreate, QueueSubscriptionMode qsm=QUEUE_ALL) throw (NoSuchProperty, InvalidOperation)
RConsumerObjectPipeQueue * getDiffsConsumerQueue (cstr url)
void listenToQueue (CUrl url) throw (NoSuchProperty, InvalidOperation)
void unlistenToQueue (CUrl url) throw (NoSuchProperty, InvalidOperation)
string textConfigLineForProperty (CUrl relativeUrl)
vector< Url > getPropertyNamesStartingWith (cstr prefix) throw ()
Public Member Functions
~Session ()
Repository * getRepository ()
Url getAbsoluteUrl (CUrl url)
Get absolute url from (possibly relative).
bool isLocalProperty (CUrl url) const throw ()
template<typename T>
const T * getObjectAsLC (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType)
template<typename T>
T * getObjectAsL (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType)
template<typename T>
T * getObjectCloneAs (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType)
template<typename T>
vector< const T * > queueFreezeAs (CUrl url) throw (NoSuchProperty, InvalidOperation)
template<typename T>
vector< const T * > queueContentAs (CUrl url) throw (NoSuchProperty, InvalidOperation)
template<typename T>
const T * queueLastAs (CUrl url) throw (NoSuchProperty, InvalidOperation, WrongType)
template<typename SimpleType, typename RType>
SimpleType getValue (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Management
void start () throw (InvalidOperation)
Start the session.
void end () throw (InvalidOperation)
End the session and complain for forgot locks.
void terminate () throw ()
End the session not complaining for forgot locks.
void setUrlContext (const string &url)
Url getUrlContext () const
string getRepositoryName () const
string getSessionName () const
string getDescription () const
Links
void linkCreate (cstr first, cstr second) throw (NoSuchProperty, InvalidOperation)
void linkRemove (cstr first) throw (NoSuchProperty, InvalidOperation)
Storage creation
void createStorage (cstr className, cstr relativecstr, cstr description, RDK2::Object *defaultValue=0) throw (InvalidOperation)
Create a property with "special" type.
void setReadonly (cstr url, bool readonly) throw (NoSuchProperty, InvalidOperation)
Set the "read only" attribute on properties.
bool isReadonly (cstr url) throw (NoSuchProperty, InvalidOperation)
Set the "persistent" attribute on properties.
bool isPersistent (cstr url) throw (NoSuchProperty, InvalidOperation)
Property deletion
void deleteProperty (cstr url) throw (NoSuchProperty, InvalidOperation)
Storage locking
void lock (cstr, Stack w) throw (NoSuchProperty, InvalidOperation)
Lock the selected property.
void unlock (cstr) throw (NoSuchProperty, InvalidOperation)
Unlock the selected property.
Storage values
const RDK2::Object * getObjectLC (cstr) throw (NoSuchProperty, InvalidOperation)
RDK2::Object * getObjectL (cstr) throw (NoSuchProperty, InvalidOperation)
template<typename T>
const T * getObjectAsLC (cstr url) throw (NoSuchProperty, InvalidOperation, WrongType, ValueNotSet)
template<typename T>
T * getObjectAsL (cstr url) throw (NoSuchProperty, InvalidOperation, WrongType, ValueNotSet)
RDK2::Object * getObjectOrCreateItL (cstr url) throw (NoSuchProperty, InvalidOperation)
RDK2::Object * getObjectClone (cstr) throw (NoSuchProperty, InvalidOperation)
template<typename T>
T * getObjectCloneAs (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType)
bool haveSameObject (cstr, cstr) throw (NoSuchProperty, InvalidOperation)
bool isSet (cstr) throw (NoSuchProperty, InvalidOperation)
Properties' properties ;-)
bool propertyExists (cstr) throw (InvalidOperation)
string getPropertyClassName (cstr) throw (NoSuchProperty, InvalidOperation)
string getPropertyDescription (cstr) throw (NoSuchProperty, InvalidOperation)
string getPropertyLinkTo (cstr) throw (NoSuchProperty, InvalidOperation)
vector< PropertyEnumItem > getPropertyEnumItems (cstr) throw (NoSuchProperty, InvalidOperation)
RPropertyDef * getRPropertyDef (cstr) throw (NoSuchProperty, InvalidOperation)
void setPropertyOptions (cstr url, PropertyOptions options) throw (NoSuchProperty, InvalidOperation)
PropertyDef getPropertyDef (cstr) throw (NoSuchProperty, InvalidOperation)
PropertyDef getDefaultPropertyDef (cstr) throw (NoSuchProperty, InvalidOperation)
void setPersistent (CUrl url) throw (NoSuchProperty, InvalidOperation)
void setVolatile (CUrl url) throw (NoSuchProperty, InvalidOperation)
void setKeepThis (CUrl url) throw (NoSuchProperty, InvalidOperation)
void setEditable (CUrl url) throw (NoSuchProperty, InvalidOperation)
void setNotEditable (CUrl url) throw (NoSuchProperty, InvalidOperation)
void setExternalFileName (CUrl url, cstr fileName) throw (NoSuchProperty, InvalidOperation)
void setExternalFileBinary (CUrl url) throw (NoSuchProperty, InvalidOperation)
void setExternalFileXml (CUrl url) throw (NoSuchProperty, InvalidOperation)
Storage modifying
void setObject (cstr, RDK2::Object *value) throw (NoSuchProperty, InvalidOperation, WrongType)
void declareDiffL (cstr, ObjectDiff *diff) throw (NoSuchProperty, InvalidOperation)
const std::vector< const
RDK2::Object * > diffsFreeze (cstr) throw (NoSuchProperty, InvalidOperation)
Storage subscription
void storageSubscribeValue (cstr) throw (NoSuchProperty, InvalidOperation)
void storageUnsubscribeValue (cstr) throw (NoSuchProperty, InvalidOperation)
void storageSubscribeDiffs (cstr) throw (NoSuchProperty, InvalidOperation)
void storageUnsubscribeDiffs (cstr) throw (NoSuchProperty, InvalidOperation)
Remote property options
void remotePropertyOptions (cstr url, Network::NetProtocol socketType=Network::TCP_IP, RRemoteSubscription::What what=RRemoteSubscription::STORAGE_DIFFS, RRemoteSubscription::When when=RRemoteSubscription::PERIODIC, double period=500.) throw (NoSuchProperty, InvalidOperation)
Queues
void queueCreate (CUrl url, cstr description) throw (NoSuchProperty, InvalidOperation)
void createQueue (CUrl url, cstr description) throw (NoSuchProperty, InvalidOperation)
void queueSubscribe (CUrl url, QueueSubscriptionMode qs=QUEUE_ALL) throw (NoSuchProperty, InvalidOperation)
void queueUnsubscribe (CUrl url) throw (NoSuchProperty, InvalidOperation)
void queueSetInterests (CUrl url, PosixQueues::MyInterests< RDK2::Object > *i) throw (NoSuchProperty, InvalidOperation)
vector< const RDK2::Object * > queueFreeze (CUrl url) throw (NoSuchProperty, InvalidOperation)
template<typename T>
vector< const T * > queueFreezeAs (CUrl url) throw (NoSuchProperty, InvalidOperation)
vector< const RDK2::Object * > queueContent (CUrl url) throw (NoSuchProperty, InvalidOperation)
template<typename T>
vector< const T * > queueContentAs (CUrl url) throw (NoSuchProperty, InvalidOperation)
void queueKeep (CUrl url, const RDK2::Object *obj) throw (NoSuchProperty, InvalidOperation)
const RDK2::Object * queueLast (CUrl url) throw (NoSuchProperty, InvalidOperation)
template<typename T>
const T * queueLastAs (CUrl url) throw (NoSuchProperty, InvalidOperation, WrongType)
bool queuePush (CUrl url, RDK2::Object *obj) throw (NoSuchProperty, InvalidOperation)
size_t queueSize (CUrl url) throw (NoSuchProperty, InvalidOperation)
Events
void valueChanged (CUrl url) throw (NoSuchProperty, InvalidOperation)
void listen (CUrl url) throw (NoSuchProperty, InvalidOperation)
NOTE: listen implies subscribe.
void unlisten (CUrl url) throw (NoSuchProperty, InvalidOperation)
void listenToTreeChanges (cstr prefix) throw (InvalidOperation)
void listenToTimer (double ms) throw (InvalidOperation)
void wait () throw ()
void dontWait () throw ()
you need to call this function if you don't wait()
void pushEvent (Event *event) throw ()
you can safely call this function from another thread
vector< const Event * > events () throw (InvalidOperation)
void wakeUp (int times=1) throw ()
you can safely call this function from another thread
bool wokenByEvent (cstr eventName) throw (InvalidOperation)
PosixConstructs::PosixSemaphore * getMySemaphore ()
Profiling
void profilingStartEvent (cstr name) throw (InvalidOperation)
void profilingEndEvent (cstr name) throw (InvalidOperation)
Bools
void createBool (CUrl url, cstr description, PropertyOptions options=NORMAL) throw (InvalidOperation)
void createBool (CUrl url, cstr description, bool defaultValue, PropertyOptions options=NORMAL) throw (InvalidOperation)
void setBool (CUrl url, bool i) throw (InvalidOperation, NoSuchProperty, WrongType)
bool getBool (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getBoolB (CUrl url, bool &b)
bool setBoolB (CUrl url, bool b)
Ints
void createInt (CUrl url, cstr description, PropertyOptions options=NORMAL) throw (InvalidOperation)
void createInt (CUrl url, cstr description, int defaultValue, PropertyOptions options=NORMAL) throw (InvalidOperation)
void setInt (CUrl url, int i) throw (InvalidOperation, NoSuchProperty, WrongType)
int getInt (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getIntB (CUrl url, int &i)
bool setIntB (CUrl url, int i)
Strings
void createString (CUrl url, cstr description, PropertyOptions options=NORMAL) throw (InvalidOperation)
void createString (CUrl url, cstr description, cstr defaultValue, PropertyOptions options=NORMAL) throw (InvalidOperation)
void setString (CUrl url, const string &s) throw (InvalidOperation, NoSuchProperty, WrongType)
string getString (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getStringB (CUrl url, string &s)
bool setStringB (CUrl url, const string &s)
Doubles
void createDouble (CUrl url, cstr desc, RDouble::Unit unit, PropertyOptions options=NORMAL) throw (InvalidOperation)
void createDouble (CUrl url, cstr desc, RDouble::Unit unit, double defValue, PropertyOptions options=NORMAL) throw (InvalidOperation)
void setDouble (CUrl url, double d) throw (InvalidOperation, NoSuchProperty, WrongType)
double getDouble (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getDoubleB (CUrl url, double &d)
bool setDoubleB (CUrl url, double d)
Enums
void createEnum (CUrl url, cstr desc, const vector< PropertyEnumItem > &entries, uint defVal, PropertyOptions options=NORMAL) throw (InvalidOperation)
void setEnum (CUrl url, uint v) throw (InvalidOperation, NoSuchProperty, WrongType)
int getEnum (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
string getEnumString (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getEnumB (CUrl url, uint &d)
bool setEnumB (CUrl url, uint d)
bool isEnum (CUrl url) throw (InvalidOperation, NoSuchProperty)
(2D) Poses
void createPose (CUrl url, cstr description) throw (InvalidOperation)
void createPose (CUrl url, cstr description, const Point2od &defaultValue) throw (InvalidOperation)
void setPose (CUrl url, const Point2od &p) throw (InvalidOperation, NoSuchProperty, WrongType)
Point2od getPose (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getPoseB (CUrl url, Point2od &p)
bool setPoseB (CUrl url, const Point2od &p)
(2D) Point
void createPoint (CUrl url, cstr description) throw (InvalidOperation)
void createPoint (CUrl url, cstr description, const Point2d &defaultValue) throw (InvalidOperation)
void setPoint (CUrl url, const Point2d &p) throw (InvalidOperation, NoSuchProperty, WrongType)
Point2d getPoint (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getPointB (CUrl url, Point2d &p)
bool setPointB (CUrl url, const Point2d &p)
3D Poses
void createPose3 (CUrl url, cstr description) throw (InvalidOperation)
void createPose3 (CUrl url, cstr description, const Point3od &defaultValue) throw (InvalidOperation)
void setPose3 (CUrl url, const Point3od &p) throw (InvalidOperation, NoSuchProperty, WrongType)
Point3od getPose3 (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getPose3B (CUrl url, Point3od &p)
bool setPose3B (CUrl url, const Point3od &p)
3D Point
void createPoint3 (CUrl url, cstr description) throw (InvalidOperation)
void createPoint3 (CUrl url, cstr description, const Point3d &defaultValue) throw (InvalidOperation)
void setPoint3 (CUrl url, const Point3d &p) throw (InvalidOperation, NoSuchProperty, WrongType)
Point3d getPoint3 (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
bool getPoint3B (CUrl url, Point3d &p)
bool setPoint3B (CUrl url, const Point3d &p)
BigObjects
void createImage (CUrl url, cstr description, int width, int height, RImage::Type type) throw (InvalidOperation, WrongType)
void createEmptyImage (CUrl url, cstr description) throw (InvalidOperation, WrongType)
void createMap (CUrl url, cstr description, double x, double y, double theta, double realWidth, int bitmapWidth, int bitmapHeight) throw (InvalidOperation, WrongType)
void createEmptyMap (cstr url, cstr description) throw (InvalidOperation, WrongType)
template<typename T>
void createVector (CUrl url, cstr description) throw (InvalidOperation, WrongType)
Network utilities
void tryConnectTo (Network::NetProtocol protocol, const string &peerName)
void tryDisconnectFrom (Network::NetProtocol protocol, const string &peerName)
ConnectionStatus getConnectionStatusWith (Network::NetProtocol type, const string &peerName)
bool getInetAddressOf (const string &name, Network::NetProtocol socketType, InetAddress &address) throw (SessionException)
Protected Member Functions
Session (cstr sessionName, cstr description, cstr urlContext, Repository *repository)
Property * lockAndGetProperty (CUrl url, bool followLinks=true) throw (InvalidOperation, NoSuchProperty)
void unlockProperty (Property *p)
Utilities for get/set/create functions
template<typename SimpleType, typename RType>
SimpleType getValue (CUrl url) throw (InvalidOperation, NoSuchProperty, ValueNotSet, WrongType)
Data Structures
struct QueueSubscription
Constructor & Destructor Documentation
RDK2::RepositoryNS::Session::Session (cstr sessionName, cstr description, cstr urlContext, Repository * repository) [protected]
Definition at line 45 of file session.cpp.
References consumerEventQueue, eventQueue, and HERE.
RDK2::RepositoryNS::Session::~Session ()
Definition at line 57 of file session.cpp.
References consumerEventQueue, RDK2::RepositoryNS::RemoteSubscriptionRegister::deleteAllSubscriptionsOfSession(), RDK2::RepositoryNS::Repository::deleteProperty(), DOUT, eventQueue, getAbsoluteUrl(), HERE, RDK2::RepositoryNS::Repository::localProperties, PosixConstructs::PosixMutex::lock(), ownedProperties, ownedPropertiesMutex, RDK2::RepositoryNS::Repository::propertiesMutex, RDK2::RepositoryNS::Repository::remoteProperties, RDK2::RepositoryNS::Repository::remoteSubscriptionRegister, repository, sessionName, RDK2::RepositoryNS::Repository::sessionsListeningToTimer, RDK2::RepositoryNS::Repository::sessionsListeningToTimerMutex, RDK2::RepositoryNS::Repository::sessionsListeningToTree, RDK2::RepositoryNS::Repository::sessionsListeningToTreeMutex, and PosixConstructs::PosixMutex::unlock().
Member Function Documentation
void RDK2::RepositoryNS::Session::start () throw (InvalidOperation)
Start the session.
Start the session. You should do this before accessing any property.
Definition at line 136 of file session.cpp.
References RDK2::Time::TimerR::getSeconds(), lockedProperties, sessionActivityTimer, sessionCurrentScheduleInterval, sessionName, sessionScheduleTimer, RDK2::Profiling::Profiler::start(), RDK2::Time::TimerR::start(), RDK2::Time::TimerT::start(), started, threadId, and threadIdInitialized.
Referenced by RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), and RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::end () throw (InvalidOperation)
End the session and complain for forgot locks.
End the session, and complain if any property has been left lock()-ed.
Definition at line 168 of file session.cpp.
References checkStarted(), RDK2::Profiling::Profiler::end(), getInt(), RDK2::Time::TimerT::getSeconds(), lockedProperties, pendingDiffs, PROPERTY_MODULE_ACTIVITY_COUNTER, PROPERTY_MODULE_ITERATION_DURATION_MEAN, PROPERTY_MODULE_LAST_ITERATION_TIMER, PROPERTY_MODULE_SCHEDULE_INTERVAL_MEAN, RDK_ERROR_PRINTF, sessionActivityCache, sessionActivityTimer, sessionCurrentScheduleInterval, sessionName, sessionScheduleCache, setDouble(), setInt(), started, and unlock().
Referenced by RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), and RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::terminate () throw ()
End the session not complaining for forgot locks.
End the session, not complaining if any property has been left lock()-ed.
This method should be called to end the session when there has been an unexpected error.
Definition at line 219 of file session.cpp.
References RDK2::Profiling::Profiler::end(), getInt(), RDK2::Time::TimerT::getSeconds(), lockedProperties, pendingDiffs, PROPERTY_MODULE_ACTIVITY_COUNTER, PROPERTY_MODULE_LAST_ITERATION_TIMER, RDK_DEBUG_PRINTF, RDK_ERROR_PRINTF, RDK_ERROR_STREAM, sessionActivityTimer, sessionName, setDouble(), setInt(), started, and unlock().
Referenced by RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), and RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::setUrlContext (const string & url) [inline]
Definition at line 126 of file session.h.
Url RDK2::RepositoryNS::Session::getUrlContext () const [inline]
Definition at line 127 of file session.h.
string RDK2::RepositoryNS::Session::getRepositoryName () const
Definition at line 27 of file session_utils.cpp.
References RDK2::RepositoryNS::Repository::getRepositoryName(), and repository.
Referenced by getRPropertyDef(), RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), and RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal().
string RDK2::RepositoryNS::Session::getSessionName () const
Definition at line 28 of file session_utils.cpp.
References sessionName.
Referenced by RDK2::RepositoryNS::RemoteSubscriptionRegister::addPropertyToReceiveSubscription().
string RDK2::RepositoryNS::Session::getDescription () const
Definition at line 29 of file session_utils.cpp.
References description.
void RDK2::RepositoryNS::Session::linkCreate (cstr first, cstr second) throw (NoSuchProperty, InvalidOperation)
Definition at line 507 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, RDK2::RepositoryNS::Property::isLinkB, RDK2::RepositoryNS::Property::linkTo, lockAndGetProperty(), RDK2::RepositoryNS::Property::object, RDK2::RepositoryNS::PropertyDef::setLinkTo(), and unlockProperty().
Referenced by linkRemove().
void RDK2::RepositoryNS::Session::linkRemove (cstr first) throw (NoSuchProperty, InvalidOperation)
Definition at line 519 of file session.cpp.
References linkCreate().
void RDK2::RepositoryNS::Session::createStorage (cstr className, cstr relativecstr, cstr description, RDK2::Object * defaultValue = 0) throw (InvalidOperation)
Create a property with "special" type.
Definition at line 261 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Repository::createStorage(), description, getAbsoluteUrl(), HERE, PosixConstructs::PosixMutex::lock(), ownedProperties, ownedPropertiesMutex, repository, and PosixConstructs::PosixMutex::unlock().
Referenced by createEmptyImage(), createEmptyMap(), createImage(), createMap(), and createVector().
void RDK2::RepositoryNS::Session::setReadonly (cstr url, bool readonly) throw (NoSuchProperty, InvalidOperation)
Set the "read only" attribute on properties.
Definition at line 273 of file session.cpp.
References checkStarted(), lockAndGetProperty(), RDK2::RepositoryNS::Property::setReadonly(), and unlockProperty().
bool RDK2::RepositoryNS::Session::isReadonly (cstr url) throw (NoSuchProperty, InvalidOperation)
Set the "persistent" attribute on properties.
"Persistent" means that the content will be saved when RAgent exits, and will be restored at next restart.
Definition at line 604 of file session.cpp.
References getProperty(), and RDK2::RepositoryNS::Property::isReadonly().
bool RDK2::RepositoryNS::Session::isPersistent (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 599 of file session.cpp.
References getProperty(), and RDK2::RepositoryNS::Property::isPersistent().
void RDK2::RepositoryNS::Session::deleteProperty (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 498 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Repository::deleteProperty(), getAbsoluteUrl(), HERE, PosixConstructs::PosixMutex::lock(), ownedProperties, ownedPropertiesMutex, repository, and PosixConstructs::PosixMutex::unlock().
void RDK2::RepositoryNS::Session::lock (cstr url, Stack w) throw (NoSuchProperty, InvalidOperation)
Lock the selected property.
Don't forget to unlock() it!
The typical value for w is HERE.
Definition at line 346 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), RDK2::RepositoryNS::Repository::lock(), RDK2::Profiling::Profiler::lock(), lockedProperties, repository, and sessionName.
Referenced by getInetAddressOf(), RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), textConfigLineForProperty(), and valueChanged().
void RDK2::RepositoryNS::Session::unlock (cstr url) throw (NoSuchProperty, InvalidOperation)
Unlock the selected property.
Definition at line 356 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), lockedProperties, repository, sessionName, RDK2::Profiling::Profiler::unlock(), and RDK2::RepositoryNS::Repository::unlock().
Referenced by end(), getInetAddressOf(), RDK2::RepositoryNS::UdpManager::init(), RDK2::RepositoryNS::TcpManager::init(), terminate(), textConfigLineForProperty(), and valueChanged().
Property * RDK2::RepositoryNS::Session::lockAndGetProperty (CUrl url, bool followLinks = true) throw (InvalidOperation, NoSuchProperty) [protected]
Definition at line 47 of file session_utils.cpp.
References checkStarted(), getAbsoluteUrl(), RDK2::RepositoryNS::Repository::getProperty(), HERE, RDK2::RepositoryNS::Url::isAbsolute(), RDK2::RepositoryNS::Url::isComplete(), RDK2::RepositoryNS::Property::isLink(), RDK2::RepositoryNS::Property::linkTo, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), MAX_LINK_LEVELS, repository, sessionName, RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
Referenced by getDefaultPropertyDef(), getObjectClone(), getPropertyDef(), haveSameObject(), isSet(), linkCreate(), setEditable(), setExternalFileBinary(), setExternalFileName(), setExternalFileXml(), setKeepThis(), setNotEditable(), setPersistent(), setReadonly(), and setVolatile().
void RDK2::RepositoryNS::Session::unlockProperty (Property * p) [protected]
Definition at line 86 of file session_utils.cpp.
References sessionName, RDK2::Profiling::Profiler::unlock(), PosixConstructs::PosixMutex::unlock(), and RDK2::RepositoryNS::Property::url.
Referenced by getDefaultPropertyDef(), getPropertyDef(), haveSameObject(), isSet(), linkCreate(), setEditable(), setExternalFileBinary(), setExternalFileName(), setExternalFileXml(), setKeepThis(), setNotEditable(), setPersistent(), setReadonly(), and setVolatile().
const RDK2::Object * RDK2::RepositoryNS::Session::getObjectLC (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 371 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), RDK2::RepositoryNS::Property::getObjectLC(), and getProperty().
Referenced by textConfigLineForProperty().
RDK2::Object * RDK2::RepositoryNS::Session::getObjectL (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 406 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), RDK2::RepositoryNS::Property::getObjectL(), getProperty(), and lockedProperties.
Referenced by valueChanged().
template<typename T> const T * RDK2::RepositoryNS::Session::getObjectAsLC (cstr url) throw (NoSuchProperty, InvalidOperation, WrongType, ValueNotSet) [inline]
Definition at line 528 of file session.h.
template<typename T> T * RDK2::RepositoryNS::Session::getObjectAsL (cstr url) throw (NoSuchProperty, InvalidOperation, WrongType, ValueNotSet) [inline]
Definition at line 544 of file session.h.
Referenced by RDK2::RepositoryNS::UdpManager::init(), and RDK2::RepositoryNS::TcpManager::init().
RDK2::Object * RDK2::RepositoryNS::Session::getObjectOrCreateItL (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 487 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), RDK2::RepositoryNS::Repository::getObjectOrCreateItL(), lockedProperties, and repository.
RDK2::Object * RDK2::RepositoryNS::Session::getObjectClone (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 378 of file session.cpp.
References checkStarted(), RDK2::Object::clone(), getAbsoluteUrl(), RDK2::RepositoryNS::Property::getObjectL(), lockAndGetProperty(), repository, sessionName, RDK2::Profiling::Profiler::unlock(), and RDK2::RepositoryNS::Repository::unlock().
template<typename T> T * RDK2::RepositoryNS::Session::getObjectCloneAs (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType) [inline]
Definition at line 566 of file session.h.
bool RDK2::RepositoryNS::Session::haveSameObject (cstr url1, cstr url2) throw (NoSuchProperty, InvalidOperation)
Definition at line 35 of file session_utils.cpp.
References RDK2::RepositoryNS::Property::getObjectL(), lockAndGetProperty(), RDK2::Statistics::r, and unlockProperty().
bool RDK2::RepositoryNS::Session::isSet (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 396 of file session.cpp.
References checkStarted(), lockAndGetProperty(), RDK2::RepositoryNS::Property::object, RDK2::Statistics::r, and unlockProperty().
bool RDK2::RepositoryNS::Session::propertyExists (cstr url) throw (InvalidOperation)
Definition at line 711 of file session.cpp.
References getAbsoluteUrl(), RDK2::RepositoryNS::Repository::getProperty(), RDK2::RepositoryNS::Url::isAbsolute(), RDK2::RepositoryNS::Url::isComplete(), and repository.
string RDK2::RepositoryNS::Session::getPropertyClassName (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 415 of file session.cpp.
References RDK2::RepositoryNS::Property::getObjectClassName(), getProperty(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), sessionName, RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
string RDK2::RepositoryNS::Session::getPropertyDescription (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 427 of file session.cpp.
References RDK2::RepositoryNS::Property::description, getProperty(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), sessionName, RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
string RDK2::RepositoryNS::Session::getPropertyLinkTo (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 474 of file session.cpp.
References getProperty(), HERE, RDK2::RepositoryNS::Property::isLink(), RDK2::RepositoryNS::Property::linkTo, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), sessionName, RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
Referenced by textConfigLineForProperty().
vector< PropertyEnumItem > RDK2::RepositoryNS::Session::getPropertyEnumItems (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 461 of file session.cpp.
References RDK2::RepositoryNS::Property::enumItems, getProperty(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), sessionName, RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
RPropertyDef * RDK2::RepositoryNS::Session::getRPropertyDef (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 566 of file session.cpp.
References getProperty(), getRepositoryName(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), sessionName, RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
Referenced by textConfigLineForProperty().
void RDK2::RepositoryNS::Session::setPropertyOptions (cstr url, PropertyOptions options) throw (NoSuchProperty, InvalidOperation)
Definition at line 609 of file session.cpp.
References RDK2::RepositoryNS::Property::def, getProperty(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), RDK2::RepositoryNS::NOT_PERSISTENT, RDK2::RepositoryNS::Property::options, sessionName, RDK2::RepositoryNS::PropertyDef::setVolatile(), RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
PropertyDef RDK2::RepositoryNS::Session::getPropertyDef (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 579 of file session.cpp.
References RDK2::RepositoryNS::Property::getPropertyDef(), lockAndGetProperty(), RDK2::Statistics::r, and unlockProperty().
PropertyDef RDK2::RepositoryNS::Session::getDefaultPropertyDef (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 589 of file session.cpp.
References RDK2::RepositoryNS::Property::getDefaultPropertyDef(), lockAndGetProperty(), RDK2::Statistics::r, and unlockProperty().
void RDK2::RepositoryNS::Session::setPersistent (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 282 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setPersistent(), and unlockProperty().
void RDK2::RepositoryNS::Session::setVolatile (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 290 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setVolatile(), and unlockProperty().
void RDK2::RepositoryNS::Session::setKeepThis (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 298 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setKeepThis(), and unlockProperty().
void RDK2::RepositoryNS::Session::setEditable (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 306 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setEditable(), and unlockProperty().
void RDK2::RepositoryNS::Session::setNotEditable (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 314 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setNotEditable(), and unlockProperty().
void RDK2::RepositoryNS::Session::setExternalFileName (CUrl url, cstr fileName) throw (NoSuchProperty, InvalidOperation)
Definition at line 322 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setExternalFileName(), and unlockProperty().
void RDK2::RepositoryNS::Session::setExternalFileBinary (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 330 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setExternalFileBinary(), and unlockProperty().
void RDK2::RepositoryNS::Session::setExternalFileXml (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 338 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::def, lockAndGetProperty(), RDK2::RepositoryNS::PropertyDef::setExternalFileXml(), and unlockProperty().
void RDK2::RepositoryNS::Session::setObject (cstr url, RDK2::Object * value) throw (NoSuchProperty, InvalidOperation, WrongType)
Definition at line 621 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), repository, RDK2::RepositoryNS::Repository::setObject(), and valueChanged().
Referenced by createImage(), createMap(), and createVector().
void RDK2::RepositoryNS::Session::declareDiffL (cstr url, ObjectDiff * diff) throw (NoSuchProperty, InvalidOperation)
Definition at line 631 of file session.cpp.
References checkStarted(), RDK2::Geometry::diff(), getAbsoluteUrl(), and pendingDiffs.
const vector< const RDK2::Object * > RDK2::RepositoryNS::Session::diffsFreeze (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 75 of file session_diffs.cpp.
void RDK2::RepositoryNS::Session::storageSubscribeValue (cstr url) throw (NoSuchProperty, InvalidOperation)
Definition at line 667 of file session.cpp.
References getProperty(), and RDK_DEBUG_PRINTF.
void RDK2::RepositoryNS::Session::storageUnsubscribeValue (cstr) throw (NoSuchProperty, InvalidOperation)
Definition at line 673 of file session.cpp.
void RDK2::RepositoryNS::Session::storageSubscribeDiffs (cstr aurl) throw (NoSuchProperty, InvalidOperation)
Definition at line 28 of file session_diffs.cpp.
References PosixQueues::PipeQueue< T >::createConsumer(), RDK2::RepositoryNS::Property::diffsQueue, HERE, RDK2::RepositoryNS::QUEUE_ALL, and PosixQueues::PipeQueue< T >::setSignalSemaphore().
Referenced by getDiffsConsumerQueue().
void RDK2::RepositoryNS::Session::storageUnsubscribeDiffs (cstr aurl) throw (NoSuchProperty, InvalidOperation)
Definition at line 48 of file session_diffs.cpp.
References PosixQueues::PipeQueue< T >::deleteConsumer(), RDK2::RepositoryNS::Property::diffsQueue, and HERE.
void RDK2::RepositoryNS::Session::remotePropertyOptions (cstr url, Network::NetProtocol socketType = Network::TCP_IP, RRemoteSubscription::What what = RRemoteSubscription::STORAGE_DIFFS, RRemoteSubscription::When when = RRemoteSubscription::PERIODIC, double period = 500.) throw (NoSuchProperty, InvalidOperation)
Definition at line 656 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), RDK2::RepositoryNS::Repository::remotePropertyOptions(), and repository.
void RDK2::RepositoryNS::Session::queueCreate (CUrl url, cstr description) throw (NoSuchProperty, InvalidOperation)
Definition at line 34 of file session_queue.cpp.
References HERE, QUEUE_CLASSNAME, and RDK2::RepositoryNS::Property::setObject().
Referenced by createQueue().
void RDK2::RepositoryNS::Session::createQueue (CUrl url, cstr description) throw (NoSuchProperty, InvalidOperation) [inline]
Definition at line 260 of file session.h.
References queueCreate().
void RDK2::RepositoryNS::Session::queueSubscribe (CUrl url, QueueSubscriptionMode qs = QUEUE_ALL) throw (NoSuchProperty, InvalidOperation)
Definition at line 72 of file session_queue.cpp.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::queueUnsubscribe (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 81 of file session_queue.cpp.
References PosixQueues::PipeQueue< T >::deleteConsumer(), RDK2::RepositoryNS::Property::getObjectAsL(), and HERE.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::queueSetInterests (CUrl url, PosixQueues::MyInterests< RDK2::Object > * i) throw (NoSuchProperty, InvalidOperation)
Definition at line 94 of file session_queue.cpp.
References RDK2::RepositoryNS::Property::getObjectAsL(), RDK2::RepositoryNS::QUEUE_ALL, and PosixQueues::PipeQueue< T >::setInterests().
Referenced by RDK2::RepositoryNS::RemotePropertyManager::receiver().
vector< const RDK2::Object * > RDK2::RepositoryNS::Session::queueFreeze (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 104 of file session_queue.cpp.
References RDK2::Profiling::Profiler::addCustomLine(), PosixQueues::PipeQueueConsumer< T >::freeze(), RDK2::RepositoryNS::QUEUE_ALL, and RDK2::Statistics::r.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::receiver().
template<typename T> vector< const T * > RDK2::RepositoryNS::Session::queueFreezeAs (CUrl url) throw (NoSuchProperty, InvalidOperation) [inline]
Definition at line 588 of file session.h.
vector< const RDK2::Object * > RDK2::RepositoryNS::Session::queueContent (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 124 of file session_queue.cpp.
References RDK2::RepositoryNS::QUEUE_ALL.
template<typename T> vector< const T * > RDK2::RepositoryNS::Session::queueContentAs (CUrl url) throw (NoSuchProperty, InvalidOperation) [inline]
Definition at line 602 of file session.h.
void RDK2::RepositoryNS::Session::queueKeep (CUrl url, const RDK2::Object * obj) throw (NoSuchProperty, InvalidOperation)
Definition at line 131 of file session_queue.cpp.
References PosixQueues::PipeQueueConsumer< T >::content(), PosixQueues::PipeQueueConsumer< T >::keep(), and RDK2::RepositoryNS::QUEUE_ALL.
const RDK2::Object * RDK2::RepositoryNS::Session::queueLast (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 146 of file session_queue.cpp.
References RDK2::RepositoryNS::QUEUE_LAST_OBJECT.
template<typename T> const T * RDK2::RepositoryNS::Session::queueLastAs (CUrl url) throw (NoSuchProperty, InvalidOperation, WrongType) [inline]
Definition at line 616 of file session.h.
bool RDK2::RepositoryNS::Session::queuePush (CUrl url, RDK2::Object * obj) throw (NoSuchProperty, InvalidOperation)
Definition at line 50 of file session_queue.cpp.
References PosixQueues::PipeQueue< T >::gc(), RDK2::RepositoryNS::Property::getObjectClassName(), HERE, RDK2::RepositoryNS::Property::isQueue(), PosixQueues::PipeQueue< T >::push(), QUEUE_CLASSNAME, RDK_DEBUG_PRINTF, RDK2::RepositoryNS::Property::setObjectClassName(), and RDK2::RepositoryNS::Property::url.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal(), tryConnectTo(), and tryDisconnectFrom().
size_t RDK2::RepositoryNS::Session::queueSize (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 153 of file session_queue.cpp.
References RDK2::RepositoryNS::Property::getObjectClassName(), RDK2::RepositoryNS::Property::isQueue(), QUEUE_CLASSNAME, RDK2::RepositoryNS::Property::setObjectClassName(), and PosixQueues::PipeQueue< T >::size().
void RDK2::RepositoryNS::Session::valueChanged (CUrl url) throw (NoSuchProperty, InvalidOperation)
NOTE: valueChanged *cannot* be called inside locked region. It assumes that url is unlocked and performes side-effect on it It update timestamp of the object.
Definition at line 640 of file session.cpp.
References checkStarted(), getAbsoluteUrl(), getObjectL(), HERE, lock(), pendingDiffs, repository, unlock(), RDK2::Object::updateTimestamp(), and RDK2::RepositoryNS::Repository::valueChanged().
Referenced by setObject().
void RDK2::RepositoryNS::Session::listen (CUrl url) throw (NoSuchProperty, InvalidOperation)
NOTE: listen implies subscribe.
Definition at line 30 of file session_events.cpp.
References RDK2::RepositoryNS::Property::isQueue(), and RDK2::RepositoryNS::Property::listeningSessions.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::unlisten (CUrl url) throw (NoSuchProperty, InvalidOperation)
Definition at line 41 of file session_events.cpp.
References RDK2::RepositoryNS::Property::isQueue(), and RDK2::RepositoryNS::Property::listeningSessions.
void RDK2::RepositoryNS::Session::listenToTreeChanges (cstr prefix) throw (InvalidOperation)
Definition at line 52 of file session_events.cpp.
References HERE.
void RDK2::RepositoryNS::Session::listenToTimer (double ms) throw (InvalidOperation)
Definition at line 67 of file session_events.cpp.
References HERE.
void RDK2::RepositoryNS::Session::wait () throw ()
Definition at line 88 of file session_events.cpp.
References consumerEventQueue, currentEvents, diffsSubscriptions, exiting, getBool(), queueSubscriptions, RDK_DEBUG_PRINTF, sessionName, and sessionSemaphore.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::receiver().
void RDK2::RepositoryNS::Session::dontWait () throw ()
you need to call this function if you don't wait()
Definition at line 130 of file session_events.cpp.
References consumerEventQueue, currentEvents, and sessionSemaphore.
void RDK2::RepositoryNS::Session::pushEvent (Event * event) throw ()
you can safely call this function from another thread
Definition at line 139 of file session_events.cpp.
References HERE.
vector< const Event * > RDK2::RepositoryNS::Session::events () throw (InvalidOperation)
Definition at line 146 of file session_events.cpp.
References checkStarted(), and currentEvents.
void RDK2::RepositoryNS::Session::wakeUp (int times = 1) throw ()
you can safely call this function from another thread
Definition at line 161 of file session_events.cpp.
References sessionSemaphore.
Referenced by RDK2::RepositoryNS::RemotePropertyManager::~RemotePropertyManager(), RDK2::RepositoryNS::TcpManager::~TcpManager(), and RDK2::RepositoryNS::UdpManager::~UdpManager().
bool RDK2::RepositoryNS::Session::wokenByEvent (cstr eventName) throw (InvalidOperation)
Definition at line 152 of file session_events.cpp.
References checkStarted(), and currentEvents.
PosixConstructs::PosixSemaphore* RDK2::RepositoryNS::Session::getMySemaphore () [inline]
Definition at line 301 of file session.h.
References sessionSemaphore.
void RDK2::RepositoryNS::Session::profilingStartEvent (cstr name) throw (InvalidOperation)
Definition at line 156 of file session.cpp.
References checkStarted(), sessionName, and RDK2::Profiling::Profiler::start().
void RDK2::RepositoryNS::Session::profilingEndEvent (cstr name) throw (InvalidOperation)
Definition at line 162 of file session.cpp.
References checkStarted(), RDK2::Profiling::Profiler::end(), and sessionName.
template<typename SimpleType, typename RType> SimpleType RDK2::RepositoryNS::Session::getValue (CUrl url) throw (InvalidOperation, NoSuchProperty, ValueNotSet, WrongType) [inline, protected]
Definition at line 632 of file session.h.
void RDK2::RepositoryNS::Session::createBool (CUrl url, cstr description, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 26 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createBool (CUrl url, cstr description, bool defaultValue, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 30 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setBool (CUrl url, bool i) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 140 of file session_get_set_create.cpp.
Referenced by setBoolB().
bool RDK2::RepositoryNS::Session::getBool (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 106 of file session_get_set_create.cpp.
Referenced by getBoolB(), and wait().
bool RDK2::RepositoryNS::Session::getBoolB (CUrl url, bool & b) [inline]
Definition at line 325 of file session.h.
References getBool(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setBoolB (CUrl url, bool b) [inline]
Definition at line 326 of file session.h.
References setBool(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createInt (CUrl url, cstr description, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 34 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createInt (CUrl url, cstr description, int defaultValue, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 38 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setInt (CUrl url, int i) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 144 of file session_get_set_create.cpp.
Referenced by end(), setEnumB(), setIntB(), and terminate().
int RDK2::RepositoryNS::Session::getInt (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 110 of file session_get_set_create.cpp.
Referenced by end(), getEnum(), getEnumB(), getIntB(), and terminate().
bool RDK2::RepositoryNS::Session::getIntB (CUrl url, int & i) [inline]
Definition at line 337 of file session.h.
References getInt(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setIntB (CUrl url, int i) [inline]
Definition at line 338 of file session.h.
References setInt(), and TRY_TO_BOOL.
Referenced by RDK2::RepositoryNS::UdpManager::init(), and RDK2::RepositoryNS::TcpManager::init().
void RDK2::RepositoryNS::Session::createString (CUrl url, cstr description, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 42 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createString (CUrl url, cstr description, cstr defaultValue, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 46 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setString (CUrl url, const string & s) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 152 of file session_get_set_create.cpp.
Referenced by setStringB().
string RDK2::RepositoryNS::Session::getString (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 118 of file session_get_set_create.cpp.
Referenced by getConnectionStatusWith(), and getStringB().
bool RDK2::RepositoryNS::Session::getStringB (CUrl url, string & s) [inline]
Definition at line 349 of file session.h.
References getString(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setStringB (CUrl url, const string & s) [inline]
Definition at line 350 of file session.h.
References setString(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createDouble (CUrl url, cstr desc, RDouble::Unit unit, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 50 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createDouble (CUrl url, cstr desc, RDouble::Unit unit, double defValue, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 58 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setDouble (CUrl url, double d) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 148 of file session_get_set_create.cpp.
Referenced by end(), setDoubleB(), and terminate().
double RDK2::RepositoryNS::Session::getDouble (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 114 of file session_get_set_create.cpp.
Referenced by getDoubleB(), RDK2::RepositoryNS::RemotePropertyManager::periodicSender(), and RDK2::RepositoryNS::RemotePropertyManager::periodicUdpRenewal().
bool RDK2::RepositoryNS::Session::getDoubleB (CUrl url, double & d) [inline]
Definition at line 361 of file session.h.
References getDouble(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setDoubleB (CUrl url, double d) [inline]
Definition at line 362 of file session.h.
References setDouble(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createEnum (CUrl url, cstr desc, const vector< PropertyEnumItem > & entries, uint defVal, PropertyOptions options = NORMAL) throw (InvalidOperation)
Definition at line 175 of file session_get_set_create.cpp.
References RDK2::RepositoryNS::Property::enumItems, HERE, RDK2::RepositoryNS::Property::isEnumB, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
void RDK2::RepositoryNS::Session::setEnum (CUrl url, uint v) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 191 of file session_get_set_create.cpp.
int RDK2::RepositoryNS::Session::getEnum (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet) [inline]
Definition at line 372 of file session.h.
References getInt().
string RDK2::RepositoryNS::Session::getEnumString (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 201 of file session_get_set_create.cpp.
References RDK2::RepositoryNS::Property::enumItems, RDK2::RepositoryNS::Property::getObjectAsLC(), HERE, PosixConstructs::PosixMutex::lock(), RDK2::Profiling::Profiler::lock(), RDK2::Profiling::Profiler::unlock(), and PosixConstructs::PosixMutex::unlock().
bool RDK2::RepositoryNS::Session::getEnumB (CUrl url, uint & d) [inline]
Definition at line 375 of file session.h.
References getInt(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setEnumB (CUrl url, uint d) [inline]
Definition at line 376 of file session.h.
References setInt(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::isEnum (CUrl url) throw (InvalidOperation, NoSuchProperty)
Definition at line 196 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createPose (CUrl url, cstr description) throw (InvalidOperation)
Definition at line 68 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createPose (CUrl url, cstr description, const Point2od & defaultValue) throw (InvalidOperation)
Definition at line 72 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setPose (CUrl url, const Point2od & p) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 156 of file session_get_set_create.cpp.
Referenced by setPoseB().
Point2od RDK2::RepositoryNS::Session::getPose (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 122 of file session_get_set_create.cpp.
Referenced by getPoseB().
bool RDK2::RepositoryNS::Session::getPoseB (CUrl url, Point2od & p) [inline]
Definition at line 386 of file session.h.
References getPose(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setPoseB (CUrl url, const Point2od & p) [inline]
Definition at line 387 of file session.h.
References setPose(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createPoint (CUrl url, cstr description) throw (InvalidOperation)
Definition at line 77 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createPoint (CUrl url, cstr description, const Point2d & defaultValue) throw (InvalidOperation)
Definition at line 81 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setPoint (CUrl url, const Point2d & p) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 164 of file session_get_set_create.cpp.
Referenced by setPointB().
Point2d RDK2::RepositoryNS::Session::getPoint (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 130 of file session_get_set_create.cpp.
Referenced by getPointB().
bool RDK2::RepositoryNS::Session::getPointB (CUrl url, Point2d & p) [inline]
Definition at line 396 of file session.h.
References getPoint(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setPointB (CUrl url, const Point2d & p) [inline]
Definition at line 397 of file session.h.
References setPoint(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createPose3 (CUrl url, cstr description) throw (InvalidOperation)
Definition at line 86 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createPose3 (CUrl url, cstr description, const Point3od & defaultValue) throw (InvalidOperation)
Definition at line 90 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setPose3 (CUrl url, const Point3od & p) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 160 of file session_get_set_create.cpp.
Referenced by setPose3B().
Point3od RDK2::RepositoryNS::Session::getPose3 (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 126 of file session_get_set_create.cpp.
Referenced by getPose3B().
bool RDK2::RepositoryNS::Session::getPose3B (CUrl url, Point3od & p) [inline]
Definition at line 406 of file session.h.
References getPose3(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setPose3B (CUrl url, const Point3od & p) [inline]
Definition at line 407 of file session.h.
References setPose3(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createPoint3 (CUrl url, cstr description) throw (InvalidOperation)
Definition at line 95 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::createPoint3 (CUrl url, cstr description, const Point3d & defaultValue) throw (InvalidOperation)
Definition at line 99 of file session_get_set_create.cpp.
void RDK2::RepositoryNS::Session::setPoint3 (CUrl url, const Point3d & p) throw (InvalidOperation, NoSuchProperty, WrongType)
Definition at line 168 of file session_get_set_create.cpp.
Referenced by setPoint3B().
Point3d RDK2::RepositoryNS::Session::getPoint3 (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet)
Definition at line 134 of file session_get_set_create.cpp.
Referenced by getPoint3B().
bool RDK2::RepositoryNS::Session::getPoint3B (CUrl url, Point3d & p) [inline]
Definition at line 416 of file session.h.
References getPoint3(), and TRY_TO_BOOL.
bool RDK2::RepositoryNS::Session::setPoint3B (CUrl url, const Point3d & p) [inline]
Definition at line 417 of file session.h.
References setPoint3(), and TRY_TO_BOOL.
void RDK2::RepositoryNS::Session::createImage (CUrl url, cstr description, int width, int height, RImage::Type type) throw (InvalidOperation, WrongType) [inline]
Definition at line 422 of file session.h.
References createStorage(), and setObject().
void RDK2::RepositoryNS::Session::createEmptyImage (CUrl url, cstr description) throw (InvalidOperation, WrongType) [inline]
Definition at line 425 of file session.h.
References createStorage().
void RDK2::RepositoryNS::Session::createMap (CUrl url, cstr description, double x, double y, double theta, double realWidth, int bitmapWidth, int bitmapHeight) throw (InvalidOperation, WrongType) [inline]
Definition at line 427 of file session.h.
References RDK2::RGraphics::RImage::C8, createStorage(), and setObject().
void RDK2::RepositoryNS::Session::createEmptyMap (cstr url, cstr description) throw (InvalidOperation, WrongType) [inline]
Definition at line 432 of file session.h.
References createStorage().
template<typename T> void RDK2::RepositoryNS::Session::createVector (CUrl url, cstr description) throw (InvalidOperation, WrongType) [inline]
Definition at line 435 of file session.h.
References createStorage(), RDK2::Containers::Vector< RType >::getClassName(), and setObject().
void RDK2::RepositoryNS::Session::tryConnectTo (Network::NetProtocol protocol, const string & peerName)
Definition at line 44 of file session_network.cpp.
References checkStarted(), Network::netProtocolToString(), queuePush(), RDK_ERROR_PRINTF, repository, Network::TCP_IP, RDK2::RepositoryNS::Repository::tcpManager, RDK2::RepositoryNS::TcpManager::tryConnectTo(), and Network::USAR_WC.
void RDK2::RepositoryNS::Session::tryDisconnectFrom (Network::NetProtocol protocol, const string & peerName)
Definition at line 63 of file session_network.cpp.
References checkStarted(), Network::netProtocolToString(), queuePush(), RDK_ERROR_PRINTF, Network::TCP_IP, and Network::USAR_WC.
Network::ConnectionStatus RDK2::RepositoryNS::Session::getConnectionStatusWith (Network::NetProtocol type, const string & peerName)
Definition at line 78 of file session_network.cpp.
References checkStarted(), RDK2::RepositoryNS::TcpManager::getConnectionStatusWith(), getString(), Network::netProtocolToString(), Network::NOT_CONNECTED, RDK_ERROR_PRINTF, repository, Network::stringToConnectionStatus(), Network::TCP_IP, RDK2::RepositoryNS::Repository::tcpManager, RDK2::TextUtils::tokenize(), and Network::USAR_WC.
bool RDK2::RepositoryNS::Session::getInetAddressOf (const string & name, Network::NetProtocol socketType, InetAddress & address) throw (SessionException)
Definition at line 108 of file session_network.cpp.
References RDK2::RNetObjects::RYellowPages::getSocketAddress(), HERE, lock(), PROPERTY_YELLOWPAGES, and unlock().
Repository* RDK2::RepositoryNS::Session::getRepository () [inline]
Definition at line 448 of file session.h.
Url RDK2::RepositoryNS::Session::getAbsoluteUrl (CUrl url)
Get absolute url from (possibly relative).
Definition at line 26 of file session_utils.cpp.
References RDK2::RepositoryNS::Url::contextualize(), and urlContext.
Referenced by createStorage(), declareDiffL(), deleteProperty(), getObjectClone(), getObjectL(), getObjectLC(), getObjectOrCreateItL(), getProperty(), lock(), lockAndGetProperty(), propertyExists(), remotePropertyOptions(), setObject(), unlock(), valueChanged(), and ~Session().
bool RDK2::RepositoryNS::Session::isLocalProperty (CUrl url) const throw ()
Definition at line 130 of file session.cpp.
string RDK2::RepositoryNS::Session::textConfigLineForProperty (CUrl relativeUrl)
Definition at line 678 of file session.cpp.
References RDK2::RepositoryNS::Property::externalFilename, getObjectLC(), getPropertyLinkTo(), getRPropertyDef(), RDK2::Object::getStringRepresentation(), RDK2::Object::hasStringRepresentation(), HERE, lock(), RDK2::Profiling::Profiler::lock(), RDK2::RepositoryNS::Property::savedExternally, sessionName, RDK2::Profiling::Profiler::unlock(), and unlock().
vector< Url > RDK2::RepositoryNS::Session::getPropertyNamesStartingWith (cstr prefix) throw ()
Definition at line 439 of file session.cpp.
References HERE, RDK2::RepositoryNS::Repository::localProperties, PosixConstructs::PosixMutex::lock(), RDK2::RepositoryNS::Repository::propertiesMutex, RDK2::RepositoryNS::Repository::remoteProperties, repository, RDK2::TextUtils::startsWith(), and PosixConstructs::PosixMutex::unlock().
void RDK2::RepositoryNS::Session::checkStarted () throw (InvalidOperation) [protected]
Definition at line 31 of file session_utils.cpp.
References sessionName, and started.
Referenced by createStorage(), declareDiffL(), deleteProperty(), end(), events(), getConnectionStatusWith(), getObjectClone(), getObjectL(), getObjectLC(), getObjectOrCreateItL(), getProperty(), isSet(), linkCreate(), lock(), lockAndGetProperty(), profilingEndEvent(), profilingStartEvent(), remotePropertyOptions(), setEditable(), setExternalFileBinary(), setExternalFileName(), setExternalFileXml(), setKeepThis(), setNotEditable(), setObject(), setPersistent(), setReadonly(), setVolatile(), tryConnectTo(), tryDisconnectFrom(), unlock(), valueChanged(), and wokenByEvent().
Property * RDK2::RepositoryNS::Session::getProperty (cstr url, bool followLinks = true) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 524 of file session.cpp.
References checkStarted(), RDK2::RepositoryNS::Property::deleted, getAbsoluteUrl(), RDK2::RepositoryNS::Url::getPath(), RDK2::RepositoryNS::Repository::getRemoteProperty(), HERE, RDK2::RepositoryNS::Url::isAbsolute(), RDK2::RepositoryNS::Url::isComplete(), RDK2::RepositoryNS::Property::isLink(), RDK2::RepositoryNS::Repository::isLocalProperty(), RDK2::RepositoryNS::Property::linkTo, RDK2::RepositoryNS::Repository::localProperties, PosixConstructs::PosixMutex::lock(), MAX_LINK_LEVELS, RDK2::RepositoryNS::Repository::propertiesMutex, repository, and PosixConstructs::PosixMutex::unlock().
Referenced by getObjectL(), getObjectLC(), getPropertyClassName(), getPropertyDescription(), getPropertyEnumItems(), getPropertyLinkTo(), getRPropertyDef(), isPersistent(), isReadonly(), setPropertyOptions(), and storageSubscribeValue().
map< Url, Session::QueueSubscription >::iterator RDK2::RepositoryNS::Session::queueGetSubscription (CUrl url, bool alsoCreate, QueueSubscriptionMode qsm = QUEUE_ALL) throw (NoSuchProperty, InvalidOperation) [protected]
HERE STARTS SOME UTILITY FUNCTIONS
Definition at line 174 of file session_queue.cpp.
References RDK2::RepositoryNS::Session::QueueSubscription::consumerQueue, PosixQueues::PipeQueue< T >::createConsumer(), RDK2::RepositoryNS::Property::getObjectAsL(), HERE, RDK2::RepositoryNS::Session::QueueSubscription::isListened, RDK2::RepositoryNS::Session::QueueSubscription::mode, and PosixQueues::PipeQueue< T >::setSignalSemaphore().
RConsumerObjectPipeQueue * RDK2::RepositoryNS::Session::getDiffsConsumerQueue (cstr url) [protected]
Definition at line 63 of file session_diffs.cpp.
References diffsSubscriptions, RDK_DEBUG_PRINTF, and storageSubscribeDiffs().
void RDK2::RepositoryNS::Session::listenToQueue (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 202 of file session_queue.cpp.
References RDK2::RepositoryNS::Property::getObjectAsL(), RDK2::RepositoryNS::QUEUE_ALL, and PosixQueues::PipeQueue< T >::setSignalSemaphore().
void RDK2::RepositoryNS::Session::unlistenToQueue (CUrl url) throw (NoSuchProperty, InvalidOperation) [protected]
Definition at line 217 of file session_queue.cpp.
References RDK2::RepositoryNS::Property::getObjectAsL(), and PosixQueues::PipeQueue< T >::setSignalSemaphore().
template<typename T> const T* RDK2::RepositoryNS::Session::getObjectAsLC (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType) [inline]
Definition at line 3 of file session.hpp.
References RDK2::Demangle::Reflective::getClassName().
template<typename T> T* RDK2::RepositoryNS::Session::getObjectAsL (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType) [inline]
Definition at line 19 of file session.hpp.
References RDK2::Demangle::Reflective::getClassName().
template<typename T> T* RDK2::RepositoryNS::Session::getObjectCloneAs (cstr url) throw (NoSuchProperty, InvalidOperation, ValueNotSet, WrongType) [inline]
Definition at line 41 of file session.hpp.
References RDK2::Demangle::Reflective::getClassName().
template<typename T> vector<const T*> RDK2::RepositoryNS::Session::queueFreezeAs (CUrl url) throw (NoSuchProperty, InvalidOperation) [inline]
Definition at line 63 of file session.hpp.
References RDK2::Statistics::r.
template<typename T> vector<const T*> RDK2::RepositoryNS::Session::queueContentAs (CUrl url) throw (NoSuchProperty, InvalidOperation) [inline]
Definition at line 77 of file session.hpp.
References RDK2::Statistics::r.
template<typename T> const T* RDK2::RepositoryNS::Session::queueLastAs (CUrl url) throw (NoSuchProperty, InvalidOperation, WrongType) [inline]
Definition at line 91 of file session.hpp.
References RDK2::Demangle::Reflective::getClassName().
template<typename SimpleType, typename RType> SimpleType RDK2::RepositoryNS::Session::getValue (CUrl url) throw (InvalidOperation, NoSuchProperty, WrongType, ValueNotSet) [inline]
Definition at line 107 of file session.hpp.
References RDK2::RepositoryNS::Property::getObjectAsLC(), RDK2::RepositoryNS::Property::getObjectL(), HERE, PosixConstructs::PosixMutex::lock(), and PosixConstructs::PosixMutex::unlock().
Friends And Related Function Documentation
friend class Repository [friend]
Definition at line 523 of file session.h.
Field Documentation
bool RDK2::RepositoryNS::Session::threadIdInitialized [protected]
Definition at line 462 of file session.h.
Referenced by start().
pthread_t RDK2::RepositoryNS::Session::threadId [protected]
Definition at line 463 of file session.h.
Referenced by start().
TimerT RDK2::RepositoryNS::Session::sessionActivityTimer [protected]
Definition at line 465 of file session.h.
Referenced by end(), start(), and terminate().
TimerR RDK2::RepositoryNS::Session::sessionScheduleTimer [protected]
Definition at line 466 of file session.h.
Referenced by start().
double RDK2::RepositoryNS::Session::sessionCurrentScheduleInterval [protected]
Definition at line 467 of file session.h.
Referenced by end(), and start().
vector<double> RDK2::RepositoryNS::Session::sessionActivityCache [protected]
Definition at line 468 of file session.h.
Referenced by end().
vector<double> RDK2::RepositoryNS::Session::sessionScheduleCache [protected]
Definition at line 469 of file session.h.
Referenced by end().
Url RDK2::RepositoryNS::Session::urlContext [protected]
Definition at line 471 of file session.h.
Referenced by getAbsoluteUrl().
Repository* const RDK2::RepositoryNS::Session::repository [protected]
Definition at line 472 of file session.h.
Referenced by createStorage(), deleteProperty(), getConnectionStatusWith(), getObjectClone(), getObjectOrCreateItL(), getProperty(), getPropertyNamesStartingWith(), getRepositoryName(), lock(), lockAndGetProperty(), propertyExists(), remotePropertyOptions(), setObject(), tryConnectTo(), unlock(), valueChanged(), and ~Session().
string RDK2::RepositoryNS::Session::sessionName [protected]
Definition at line 473 of file session.h.
Referenced by checkStarted(), end(), getObjectClone(), getPropertyClassName(), getPropertyDescription(), getPropertyEnumItems(), getPropertyLinkTo(), getRPropertyDef(), getSessionName(), lock(), lockAndGetProperty(), profilingEndEvent(), profilingStartEvent(), setPropertyOptions(), start(), terminate(), textConfigLineForProperty(), unlock(), unlockProperty(), wait(), and ~Session().
string RDK2::RepositoryNS::Session::description [protected]
Definition at line 474 of file session.h.
Referenced by createStorage(), and getDescription().
bool RDK2::RepositoryNS::Session::started [protected]
Definition at line 476 of file session.h.
Referenced by checkStarted(), end(), start(), and terminate().
PosixConstructs::PosixSemaphore RDK2::RepositoryNS::Session::sessionSemaphore [protected]
Definition at line 480 of file session.h.
Referenced by dontWait(), getMySemaphore(), wait(), and wakeUp().
PosixQueues::PipeQueue<Event>* RDK2::RepositoryNS::Session::eventQueue [protected]
Definition at line 482 of file session.h.
Referenced by Session(), and ~Session().
PosixQueues::PipeQueueConsumer<Event>* RDK2::RepositoryNS::Session::consumerEventQueue [protected]
Definition at line 483 of file session.h.
Referenced by dontWait(), Session(), wait(), and ~Session().
vector<const Event*> RDK2::RepositoryNS::Session::currentEvents [protected]
Definition at line 485 of file session.h.
Referenced by dontWait(), events(), wait(), and wokenByEvent().
map<Url, vector<ObjectDiff*> > RDK2::RepositoryNS::Session::pendingDiffs [protected]
Definition at line 488 of file session.h.
Referenced by declareDiffL(), end(), terminate(), and valueChanged().
set<string> RDK2::RepositoryNS::Session::lockedProperties [protected]
Definition at line 489 of file session.h.
Referenced by end(), getObjectL(), getObjectOrCreateItL(), lock(), start(), terminate(), and unlock().
volatile bool RDK2::RepositoryNS::Session::exiting
Definition at line 494 of file session.h.
Referenced by wait().
PosixConstructs::PosixMutex RDK2::RepositoryNS::Session::ownedPropertiesMutex [protected]
Definition at line 497 of file session.h.
Referenced by createStorage(), deleteProperty(), and ~Session().
set<Url> RDK2::RepositoryNS::Session::ownedProperties [protected]
Definition at line 499 of file session.h.
Referenced by createStorage(), deleteProperty(), and ~Session().
PosixConstructs::PosixMutex RDK2::RepositoryNS::Session::queueSubscriptionsMutex [protected]
Definition at line 510 of file session.h.
map<Url, QueueSubscription> RDK2::RepositoryNS::Session::queueSubscriptions [protected]
Definition at line 511 of file session.h.
Referenced by wait().
map<Url, QueueSubscription> RDK2::RepositoryNS::Session::diffsSubscriptions [protected]
Definition at line 512 of file session.h.
Referenced by getDiffsConsumerQueue(), and wait().
The documentation for this class was generated from the following files:
session.h
session.cpp
session.hpp
session_diffs.cpp
session_events.cpp
session_get_set_create.cpp
session_network.cpp
session_queue.cpp
session_utils.cpp