OpenRDK: RDK2::Meta Namespace Reference
RDK2::Meta Namespace Reference
Data Structures
class Factory
struct ObjectDiff
Typedefs
typedef std::map< std::string,
const RDK2::Object * > Class2prot
Functions
Class2prot & getClass2prot ()
RDK2::Object * forName (cstr name)
void freePrototypeDb ()
Typedef Documentation
typedef std::map<std::string, const RDK2::Object*> RDK2::Meta::Class2prot
Definition at line 175 of file object.h.
Function Documentation
RDK2::Object * RDK2::Meta::forName (cstr name)
Definition at line 69 of file objectmanager.cpp.
References getClass2prot(), and RDK_ERROR_STREAM.
Referenced by RDK2::RepositoryNS::Repository::getObjectOrCreateItL(), main(), RDK2::Serialization::Xml::XmlReader::readObject(), and RDK2::Serialization::Binary::BinaryReader::readObject().
void RDK2::Meta::freePrototypeDb ()
Definition at line 86 of file objectmanager.cpp.
References getClass2prot().
Class2prot & RDK2::Meta::getClass2prot ()
Definition at line 30 of file objectmanager.cpp.
Referenced by RDK2::Meta::Factory::Factory(), forName(), freePrototypeDb(), and main().