OpenRDK: RDK2::RGraphics Namespace Reference
RDK2::RGraphics Namespace Reference
Data Structures
class RC8Set
class RImage
struct RImageDiffJpegPacket
struct RImageDiffPoints
class RImageDiffRect
class RImagePointC8
struct RPoseVector
Typedefs
typedef uint32_t RgbColor
Functions
unsigned char rgbGetRed (RgbColor c)
unsigned char rgbGetGreen (RgbColor c)
unsigned char rgbGetBlue (RgbColor c)
RgbColor rgb (uint8_t red, uint8_t green, uint8_t blue)
void compressImgLine (RImage::Type type, uint8_t **rows, int y, int width, vector< uint8_t > &cLine)
void uncompressImgDiffCBuf (const vector< uint8_t > &cBuf, RImageDiffRect *diff)
RDK2_FACTORY (RC8Set)
RDK2_FACTORY (RImage)
uint8_t reduceC8 (uint8_t color)
uint8_t expandC8 (uint8_t color)
RDK2_FACTORY (RImageDiffJpegPacket)
RDK2_FACTORY (RImageDiffPoints)
RDK2_FACTORY (RImageDiffRect)
RDK2_FACTORY (RImagePointC8)
RDK2_FACTORY (RPoseVector)
Variables
const RgbColor RGB_BLACK = 0x00000000
const RgbColor RGB_WHITE = 0x00ffffff
const RgbColor RGB_RED = 0x00ff0000
const RgbColor RGB_GREEN = 0x0000ff00
const RgbColor RGB_BLUE = 0x000000ff
const RgbColor RGB_YELLOW = 0x00ffff00
const RgbColor RGB_MAGENTA = 0x00ff00ff
const RgbColor RGB_CYAN = 0x0000ffff
const RgbColor RGB_GRAY = 0x00888888
const RgbColor RGB_ORANGE = 0x00ff8800
Typedef Documentation
typedef uint32_t RDK2::RGraphics::RgbColor
Definition at line 27 of file color.h.
Function Documentation
void RDK2::RGraphics::compressImgLine (RImage::Type type, uint8_t ** rows, int y, int width, vector< uint8_t > & cLine)
Definition at line 27 of file imgdiffs.cpp.
References RDK2::RGraphics::RImage::C8, RDK2::RGraphics::RImage::getBytesPerPixel(), reduceC8(), and RDK2::RGraphics::RImage::RGB32.
Referenced by RDK2::RGraphics::RImageDiffRect::split(), and RDK2::RGraphics::RImageDiffRect::write().
uint8_t RDK2::RGraphics::expandC8 (uint8_t color)
Definition at line 52 of file rimage_serialization.cpp.
References RDK2::RGraphics::RImage::C8Black, RDK2::RGraphics::RImage::C8Blue, RDK2::RGraphics::RImage::C8Cyan, RDK2::RGraphics::RImage::C8Green, RDK2::RGraphics::RImage::C8Grey, RDK2::RGraphics::RImage::C8Magenta, RDK2::RGraphics::RImage::C8Red, and RDK2::RGraphics::RImage::C8White.
Referenced by RDK2::RGraphics::RImage::readImpl(), and uncompressImgDiffCBuf().
RDK2::RGraphics::RDK2_FACTORY (RPoseVector)
RDK2::RGraphics::RDK2_FACTORY (RImagePointC8)
RDK2::RGraphics::RDK2_FACTORY (RImageDiffRect)
RDK2::RGraphics::RDK2_FACTORY (RImageDiffPoints)
RDK2::RGraphics::RDK2_FACTORY (RImageDiffJpegPacket)
RDK2::RGraphics::RDK2_FACTORY (RImage)
RDK2::RGraphics::RDK2_FACTORY (RC8Set)
uint8_t RDK2::RGraphics::reduceC8 (uint8_t color)
Definition at line 37 of file rimage_serialization.cpp.
References RDK2::RGraphics::RImage::C8Black, RDK2::RGraphics::RImage::C8Blue, RDK2::RGraphics::RImage::C8Cyan, RDK2::RGraphics::RImage::C8Green, RDK2::RGraphics::RImage::C8Grey, RDK2::RGraphics::RImage::C8Magenta, RDK2::RGraphics::RImage::C8Red, and RDK2::RGraphics::RImage::C8White.
Referenced by compressImgLine(), and RDK2::RGraphics::RImage::writeImpl().
RgbColor RDK2::RGraphics::rgb (uint8_t red, uint8_t green, uint8_t blue) [inline]
Definition at line 44 of file color.h.
unsigned char RDK2::RGraphics::rgbGetBlue (RgbColor c) [inline]
Definition at line 42 of file color.h.
unsigned char RDK2::RGraphics::rgbGetGreen (RgbColor c) [inline]
Definition at line 41 of file color.h.
unsigned char RDK2::RGraphics::rgbGetRed (RgbColor c) [inline]
Definition at line 40 of file color.h.
void RDK2::RGraphics::uncompressImgDiffCBuf (const vector< uint8_t > & cBuf, RImageDiffRect * diff)
Definition at line 78 of file imgdiffs.cpp.
References RDK2::RGraphics::RImage::C8, expandC8(), RDK2::RGraphics::RImage::getBytesPerPixel(), RDK2::RGraphics::RImageDiffRect::getPixels(), RDK_ERROR_PRINTF, RDK2::RGraphics::RImageDiffRect::rectHeight, RDK2::RGraphics::RImageDiffRect::rectWidth, RDK2::RGraphics::RImageDiffRect::refImageType, and RDK2::RGraphics::RImage::RGB32.
Referenced by RDK2::RGraphics::RImageDiffRect::read().
Variable Documentation
const RgbColor RDK2::RGraphics::RGB_BLACK = 0x00000000
Definition at line 29 of file color.h.
const RgbColor RDK2::RGraphics::RGB_BLUE = 0x000000ff
Definition at line 33 of file color.h.
const RgbColor RDK2::RGraphics::RGB_CYAN = 0x0000ffff
Definition at line 36 of file color.h.
const RgbColor RDK2::RGraphics::RGB_GRAY = 0x00888888
Definition at line 37 of file color.h.
const RgbColor RDK2::RGraphics::RGB_GREEN = 0x0000ff00
Definition at line 32 of file color.h.
const RgbColor RDK2::RGraphics::RGB_MAGENTA = 0x00ff00ff
Definition at line 35 of file color.h.
const RgbColor RDK2::RGraphics::RGB_ORANGE = 0x00ff8800
Definition at line 38 of file color.h.
const RgbColor RDK2::RGraphics::RGB_RED = 0x00ff0000
Definition at line 31 of file color.h.
const RgbColor RDK2::RGraphics::RGB_WHITE = 0x00ffffff
Definition at line 30 of file color.h.
const RgbColor RDK2::RGraphics::RGB_YELLOW = 0x00ffff00
Definition at line 34 of file color.h.