OpenRDK: RDK2::Serialization::Binary Namespace Reference
RDK2::Serialization::Binary Namespace Reference
Data Structures
class BinaryReader
class BinaryWriter
Typedefs
typedef std::string Buffer
Functions
Buffer nbo_i16 (int16_t v)
Buffer nbo_i32 (int32_t v)
Buffer nbo_f32 (float32_t v)
Buffer nbo_f64 (float64_t v)
Note: please make sure it is in sync with the companion in binaryreader_bytes.cpp.
Buffer packet_i8 (int8_t c)
Buffer packet_u8 (uint8_t c)
Buffer packet_i16 (int16_t c)
Buffer packet_i32 (int32_t c)
Buffer packet_f32 (float32_t d)
Buffer packet_f64 (float64_t d)
Buffer packet_bytes (const void *v, size_t n)
Buffer packet_string (cstr s)
Buffer packet_objectWithClass (cstr className, unsigned char version, Buffer payload)
Buffer packet_objectWithoutClass (Buffer payload)
Buffer packet_i16 (const int16_t *v, size_t n)
Buffer packet_i32 (const int32_t *v, size_t n)
Buffer packet_f32 (const float32_t *v, size_t n)
Buffer packet_f64 (const float64_t *v, size_t n)
std::string packetName (char c)
Typedef Documentation
typedef std::string RDK2::Serialization::Binary::Buffer
Definition at line 28 of file packets.h.
Function Documentation
Buffer RDK2::Serialization::Binary::nbo_f32 (float32_t v)
Definition at line 48 of file packets.cpp.
Referenced by nbo_f64(), and packet_f32().
Buffer RDK2::Serialization::Binary::nbo_f64 (float64_t v)
Note: please make sure it is in sync with the companion in binaryreader_bytes.cpp.
Definition at line 65 of file packets.cpp.
References nbo_f32(), RDK_INF32, and RDK2::Geometry::RDK_ISINF().
Referenced by packet_f64().
Buffer RDK2::Serialization::Binary::nbo_i16 (int16_t v)
Definition at line 39 of file packets.cpp.
Referenced by packet_i16().
Buffer RDK2::Serialization::Binary::nbo_i32 (int32_t v)
Definition at line 43 of file packets.cpp.
Referenced by packet_bytes(), packet_f32(), packet_f64(), packet_i16(), packet_i32(), packet_objectWithClass(), packet_objectWithoutClass(), and packet_string().
Buffer RDK2::Serialization::Binary::packet_bytes (const void * v, size_t n)
Definition at line 131 of file packets.cpp.
References nbo_i32(), and PACKET_HEADER_ARRAY_INT8.
Referenced by RDK2::Serialization::Binary::BinaryWriter::writeBytes().
Buffer RDK2::Serialization::Binary::packet_f32 (const float32_t * v, size_t n)
Definition at line 192 of file packets.cpp.
References nbo_f32(), nbo_i32(), and PACKET_HEADER_ARRAY_FLOAT32.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_f32().
Buffer RDK2::Serialization::Binary::packet_f32 (float32_t d)
Definition at line 117 of file packets.cpp.
References nbo_f32(), and PACKET_HEADER_FLOAT32.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_f32().
Buffer RDK2::Serialization::Binary::packet_f64 (const float64_t * v, size_t n)
Definition at line 203 of file packets.cpp.
References nbo_f64(), nbo_i32(), and PACKET_HEADER_ARRAY_FLOAT64.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_f64().
Buffer RDK2::Serialization::Binary::packet_f64 (float64_t d)
Definition at line 124 of file packets.cpp.
References nbo_f64(), and PACKET_HEADER_FLOAT64.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_f64().
Buffer RDK2::Serialization::Binary::packet_i16 (const int16_t * v, size_t n)
Definition at line 170 of file packets.cpp.
References nbo_i16(), nbo_i32(), and PACKET_HEADER_ARRAY_INT16.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_i16().
Buffer RDK2::Serialization::Binary::packet_i16 (int16_t c)
Definition at line 102 of file packets.cpp.
References nbo_i16(), and PACKET_HEADER_INT16.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_i16().
Buffer RDK2::Serialization::Binary::packet_i32 (const int32_t * v, size_t n)
Definition at line 181 of file packets.cpp.
References nbo_i32(), and PACKET_HEADER_ARRAY_INT32.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_i32().
Buffer RDK2::Serialization::Binary::packet_i32 (int32_t c)
Definition at line 109 of file packets.cpp.
References nbo_i32(), and PACKET_HEADER_INT32.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_i32().
Buffer RDK2::Serialization::Binary::packet_i8 (int8_t c)
Definition at line 88 of file packets.cpp.
References PACKET_HEADER_INT8.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_i8().
Buffer RDK2::Serialization::Binary::packet_objectWithClass (cstr className, unsigned char version, Buffer payload)
Definition at line 148 of file packets.cpp.
References nbo_i32(), PACKET_HEADER_OBJECTWITHCLASS, and packet_string().
Referenced by RDK2::Serialization::Binary::BinaryWriter::writeObject().
Buffer RDK2::Serialization::Binary::packet_objectWithoutClass (Buffer payload)
Definition at line 161 of file packets.cpp.
References nbo_i32(), and PACKET_HEADER_OBJECTNOCLASS.
Referenced by RDK2::Serialization::Binary::BinaryWriter::writeObject().
Buffer RDK2::Serialization::Binary::packet_string (cstr s)
Definition at line 139 of file packets.cpp.
References nbo_i32(), and PACKET_HEADER_STRING.
Referenced by packet_objectWithClass(), and RDK2::Serialization::Binary::BinaryWriter::writeString().
Buffer RDK2::Serialization::Binary::packet_u8 (uint8_t c)
Definition at line 95 of file packets.cpp.
References PACKET_HEADER_INT8.
Referenced by RDK2::Serialization::Binary::BinaryWriter::write_u8().
std::string RDK2::Serialization::Binary::packetName (char c)
Definition at line 215 of file packets.cpp.
References CASE, PACKET_HEADER_ARRAY_FLOAT32, PACKET_HEADER_ARRAY_FLOAT64, PACKET_HEADER_ARRAY_INT16, PACKET_HEADER_ARRAY_INT32, PACKET_HEADER_ARRAY_INT8, PACKET_HEADER_FLOAT32, PACKET_HEADER_FLOAT64, PACKET_HEADER_INT16, PACKET_HEADER_INT32, PACKET_HEADER_INT8, PACKET_HEADER_NAME, PACKET_HEADER_OBJECTARRAY, PACKET_HEADER_OBJECTNOCLASS, and PACKET_HEADER_OBJECTWITHCLASS.
Referenced by RDK2::Serialization::Binary::BinaryReader::readObject().