OpenRDK: RDK2::Time::Timestamp Struct Reference
RDK2::Time::Timestamp Struct Reference
#include <time.h>
Detailed Description
Definition at line 31 of file time.h.
Public Member Functions
Timestamp ()
Timestamp (double seconds)
void setToNow ()
void setSeconds (double sec)
void setMs (double sec)
double getSeconds () const
double getMs () const
operator double () const
Timestamp operator+ (const Timestamp &ts) const
Timestamp operator- (const Timestamp &ts) const
string getStringRepresentation () const
unsigned long getMsFromMidnight () const
void setMsFromMidnight (unsigned long ms)
bool operator< (const Timestamp &ts) const
bool operator> (const Timestamp &ts) const
Constructor & Destructor Documentation
RDK2::Time::Timestamp::Timestamp () [inline]
Definition at line 32 of file time.h.
References setToNow().
RDK2::Time::Timestamp::Timestamp (double seconds) [inline]
Definition at line 33 of file time.h.
References setSeconds().
Member Function Documentation
void RDK2::Time::Timestamp::setToNow () [inline]
Definition at line 34 of file time.h.
Referenced by RDK2::Time::TimerR::start(), Timestamp(), and RDK2::Object::updateTimestamp().
void RDK2::Time::Timestamp::setSeconds (double sec) [inline]
Definition at line 35 of file time.h.
Referenced by RDK2::Time::operator>>(), setMs(), and Timestamp().
void RDK2::Time::Timestamp::setMs (double sec) [inline]
Definition at line 37 of file time.h.
References setSeconds().
double RDK2::Time::Timestamp::getSeconds () const [inline]
Definition at line 38 of file time.h.
Referenced by operator double(), RDK2::Time::operator<<(), and RDK2::SensorData::LaserParser::write().
double RDK2::Time::Timestamp::getMs () const [inline]
Definition at line 39 of file time.h.
Referenced by RDK2::Time::TimerR::getMs().
RDK2::Time::Timestamp::operator double () const [inline]
Definition at line 40 of file time.h.
References getSeconds().
Timestamp RDK2::Time::Timestamp::operator+ (const Timestamp & ts) const [inline]
Definition at line 41 of file time.h.
Timestamp RDK2::Time::Timestamp::operator- (const Timestamp & ts) const [inline]
Definition at line 47 of file time.h.
References RDK2::Statistics::r.
string RDK2::Time::Timestamp::getStringRepresentation () const [inline]
Definition at line 54 of file time.h.
Referenced by RDK2::LogFile::LogFile().
unsigned long RDK2::Time::Timestamp::getMsFromMidnight () const [inline]
Definition at line 65 of file time.h.
Referenced by RDK2::RMaps::RVictimOnMap::getLogLine(), RDK2::RSensorData::RStereoImageHeightsData::getLogLine(), RDK2::RSensorData::RPantiltData::getLogLine(), RDK2::RSensorData::ROdometryDataWithSpeed::getLogLine(), RDK2::RSensorData::ROdometryData::getLogLine(), RDK2::RSensorData::RLaserData::getLogLine(), RDK2::RMaps::RLandmark::getLogLine(), RDK2::RSensorData::RActuaData::getLogLine(), and RDK2::Object::writeObjectBody().
void RDK2::Time::Timestamp::setMsFromMidnight (unsigned long ms) [inline]
Definition at line 68 of file time.h.
Referenced by RDK2::RSensorData::RStereoImageHeightsData::loadFromLogLine(), RDK2::RSensorData::RPantiltData::loadFromLogLine(), RDK2::RSensorData::ROdometryDataWithSpeed::loadFromLogLine(), RDK2::RSensorData::ROdometryData::loadFromLogLine(), RDK2::RSensorData::RLaserData::loadFromLogLine(), RDK2::RMaps::RLandmark::loadFromLogLine(), RDK2::RSensorData::RActuaData::loadFromLogLine(), and RDK2::Object::readObjectBody().
bool RDK2::Time::Timestamp::operator< (const Timestamp & ts) const [inline]
Definition at line 72 of file time.h.
bool RDK2::Time::Timestamp::operator> (const Timestamp & ts) const [inline]
Definition at line 75 of file time.h.
The documentation for this struct was generated from the following file:
time.h