OpenRDK: RDK2::RMaps::RMapImage Struct Reference
RDK2::RMaps::RMapImage Struct Reference
#include <rmapimage.h>
Detailed Description
An image with spatial placement.
Definition at line 45 of file rmapimage.h.
Public Types
enum RayTracingResult { Obstacle = 0, Free = 1, Unknown = 2, Margin = 3 }
Public Member Functions
RMapImage ()
RMapImage (double x, double y, double theta, double realWidth, RImage *image)
~RMapImage ()
void move (double x, double y, RImage *image)
void canvasReshape (double wd, double hg, double new_x=0, double new_y=0, unsigned char fillValue=(unsigned char) C8Unknown)
bool centeredRobot (double robot_posx, double robot_posy, double *new_x, double *new_y, double off_size)
void read (Reader *r) throw (ReadingException)
void write (Writer *w) const throw (WritingException)
RDK2::Object * clone () const
bool knowsDiffs ()
bool applyDiff (const ObjectDiff *diff)
vector< ObjectDiff * > splitInDiffs (size_t maxSize)
bool world2buf (const RDK2::Geometry::Point2d &w, RDK2::Geometry::Point2i &b) const
ritorna true se dentro
void buf2world (const RDK2::Geometry::Point2i &b, RDK2::Geometry::Point2d &w) const
bool world2buf (double wx, double wy, int &x, int &y) const
void buf2world (int bx, int by, double &wx, double &wy) const
double buf2world (int d) const
int world2buf (double d) const
RDK2::Geometry::Point2d minWorld () const
RDK2::Geometry::Point2d maxWorld () const
double minWorldX () const
double maxWorldX () const
double minWorldY () const
double maxWorldY () const
double getRealWidth () const
double getRealHeight () const
double getMapDelta () const
bool sameGeometry (const RMapImage *mapImage) const
std::string toString () const
void setPixelW (double wx, double wy, unsigned char color)
unsigned char getPixelW (double wx, double wy) const
bool safeSetPixelB (size_t x, size_t y, unsigned char color)
unsigned char safeGetPixelB (size_t x, size_t y, unsigned char defaultColor) const
void setPixelB (size_t x, size_t y, unsigned char color)
unsigned char getPixelB (size_t x, size_t y) const
void line (int x0, int y0, int x1, int y1, unsigned char color)
void rayTracing (const Point2d &start, const Point2d &end, const RC8Set *obstacleColors, bool &hitSomething, RImage::C8Color &colorHit)
void distMapRayTracing (const Point2d &start, const Point2d &end, bool &hitSomething, int min_dist)
double obsDenRayTracing (const Point2d &start, const Point2d &end)
RayTracingResult rayTracing2 (double px, double py, double ptheta, double maxdist, double &result) const
RayTracingResult visibilityCheck (double p0x, double p0y, double p1x, double p1y, double *distancePtr=0)
bool rayTracing (const Point2d &start, const Point2d &end, const RC8Set *obstacleColors, Point2d *collisionPoint=0, RImage::C8Color *colorHit=0)
bool rayTracing (const Point2d &start, double direction, double maxDist, const RC8Set *obstacleColors, double *distance=0, RImage::C8Color *colorHit=0)
double calcClearance_w (double wx, double wy)
double calcClearance_b (int bx, int by)
Static Public Member Functions
static unsigned int markLine (int x0, int y0, int x1, int y1, int width, int height, point *line, unsigned int maxLineLength)
Data Fields
double x
double y
double theta
double realWidth
RImage * image
Data Structures
struct point
Member Enumeration Documentation
enum RDK2::RMaps::RMapImage::RayTracingResult
Enumerator:
Obstacle abbiamo preso un ostacolo, ritorna distanza ostacolo
Free non abbiamo preso niente entro maxdist
Unknown abbiamo attraversato il blu, ritorna distanza libera
Margin abbiamo sforato
Definition at line 164 of file rmapimage.h.
Constructor & Destructor Documentation
RDK2::RMaps::RMapImage::RMapImage ()
Definition at line 39 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::C8, image, realWidth, theta, x, and y.
Referenced by clone().
RDK2::RMaps::RMapImage::RMapImage (double x, double y, double theta, double realWidth, RImage * image)
"image" is not cloned and it is now property of the RMapImage.
Definition at line 63 of file rmapimage.cpp.
RDK2::RMaps::RMapImage::~RMapImage ()
Definition at line 46 of file rmapimage.cpp.
References image.
Member Function Documentation
void RDK2::RMaps::RMapImage::move (double x, double y, RImage * image)
Definition at line 566 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getBuffer(), RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Geometry::max(), RDK2::Geometry::min(), world2buf(), x, and y.
void RDK2::RMaps::RMapImage::canvasReshape (double wd, double hg, double new_x = 0, double new_y = 0, unsigned char fillValue = (unsigned char)C8Unknown)
this is a function that reshape the map, setting appropriately the new position and the new map dimensions. If the new canvas overlaps the old one, the overlapping area of the old map is copied unchanged in the new canvas.
Parameters:
wd the new canvas (map) width
hg the new canvas (map) height
new_x the new x position of the (map) canvas
new_y the new y position of the (map) canvas
fillValue the value (at a byte level) used to fill the area of the new (map) canvas that does not ovelap the old (map) canvas.
Definition at line 596 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::canvasResize(), getMapDelta(), image, realWidth, world2buf(), x, and y.
bool RDK2::RMaps::RMapImage::centeredRobot (double robot_posx, double robot_posy, double * new_x, double * new_y, double off_size)
this is a utility function that check whether or not the robot position is centered in the map. If not, it returns the new suggested position for the new map
Parameters:
robot_posx the x robot position to be tested
robot_posy the y robot position to be tested
new_x the new x map position
new_y the new y map position
off_size the robot is 'centered' if the distance to the map border projected in one of its coordinate axes is greater than off_size.
Definition at line 606 of file rmapimage.cpp.
References getRealHeight(), realWidth, x, and y.
void RDK2::RMaps::RMapImage::read (Reader * r) throw (ReadingException) [virtual]
These default implementations of Writable and Readable serialize empty objects.
Reimplemented from RDK2::Object.
Definition at line 544 of file rmapimage.cpp.
References RDK2::Demangle::Reflective::getClassName(), image, RDK2::Statistics::r, realWidth, theta, x, and y.
void RDK2::RMaps::RMapImage::write (Writer *) const throw (WritingException) [virtual]
Function to be implemented by objects wishing to serialize themselves.
Here are some assumptions:
the object must call startWriting(), then output his data with the writeXXX functions, and then end with endWriting()
the object must let the exceptions generated by the Writer to pass through, as the writer will take care of them.
to serialize a sub-object, use the writeObject function.
Reimplemented from RDK2::Object.
Definition at line 555 of file rmapimage.cpp.
References RDK2::Demangle::Reflective::getClassName(), image, realWidth, theta, x, and y.
RDK2::Object * RDK2::RMaps::RMapImage::clone () const [virtual]
Returns a copy of the object.
Returns:
0 if not implemented
Reimplemented from RDK2::Object.
Definition at line 72 of file rmapimage.cpp.
References image, realWidth, RMapImage(), theta, x, and y.
bool RDK2::RMaps::RMapImage::knowsDiffs () [inline, virtual]
Reimplemented from RDK2::Object.
Definition at line 106 of file rmapimage.h.
bool RDK2::RMaps::RMapImage::applyDiff (const ObjectDiff * diff) [virtual]
Reimplemented from RDK2::Object.
Definition at line 36 of file rmapimage_diffs.cpp.
References RDK2::RGraphics::RImage::applyDiff(), image, RDK2::RMaps::RMapImageDiffPoints::imageDiffPoints, RDK2::RMaps::RMapImageDiffRect::imageDiffRect, realWidth, RDK2::RMaps::RMapImageDiffRect::refMapImageRealWidth, RDK2::RMaps::RMapImageDiffRect::refMapImageTheta, RDK2::RMaps::RMapImageDiffRect::refMapImageX, RDK2::RMaps::RMapImageDiffRect::refMapImageY, theta, x, and y.
vector< ObjectDiff * > RDK2::RMaps::RMapImage::splitInDiffs (size_t maxSize) [virtual]
Reimplemented from RDK2::Object.
Definition at line 28 of file rmapimage_diffs.cpp.
References RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, and RDK2::RMaps::RMapImageDiffRect::split().
bool RDK2::RMaps::RMapImage::world2buf (const RDK2::Geometry::Point2d & w, RDK2::Geometry::Point2i & b) const
ritorna true se dentro
Definition at line 101 of file rmapimage.cpp.
References RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Referenced by calcClearance_w(), canvasReshape(), distMapRayTracing(), getPixelW(), move(), obsDenRayTracing(), rayTracing(), rayTracing2(), and setPixelW().
void RDK2::RMaps::RMapImage::buf2world (const RDK2::Geometry::Point2i & b, RDK2::Geometry::Point2d & w) const
Definition at line 105 of file rmapimage.cpp.
References RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Referenced by rayTracing(), rayTracing2(), and toString().
bool RDK2::RMaps::RMapImage::world2buf (double wx, double wy, int & x, int & y) const
Definition at line 109 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, realWidth, x, and y.
void RDK2::RMaps::RMapImage::buf2world (int bx, int by, double & wx, double & wy) const
Definition at line 115 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getWidth(), image, realWidth, x, and y.
double RDK2::RMaps::RMapImage::buf2world (int d) const
Definition at line 121 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getWidth(), image, and realWidth.
int RDK2::RMaps::RMapImage::world2buf (double d) const
Definition at line 127 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getWidth(), image, and realWidth.
RDK2::Geometry::Point2d RDK2::RMaps::RMapImage::minWorld () const [inline]
Definition at line 118 of file rmapimage.h.
References minWorldX(), and minWorldY().
RDK2::Geometry::Point2d RDK2::RMaps::RMapImage::maxWorld () const [inline]
Definition at line 119 of file rmapimage.h.
References maxWorldX(), and maxWorldY().
double RDK2::RMaps::RMapImage::minWorldX () const
Definition at line 93 of file rmapimage.cpp.
References x.
Referenced by minWorld().
double RDK2::RMaps::RMapImage::maxWorldX () const
Definition at line 95 of file rmapimage.cpp.
References realWidth, and x.
Referenced by maxWorld().
double RDK2::RMaps::RMapImage::minWorldY () const
Definition at line 97 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, realWidth, and y.
Referenced by minWorld().
double RDK2::RMaps::RMapImage::maxWorldY () const
Definition at line 99 of file rmapimage.cpp.
References y.
Referenced by maxWorld().
double RDK2::RMaps::RMapImage::getRealWidth () const [inline]
Definition at line 125 of file rmapimage.h.
References realWidth.
Referenced by sameGeometry().
double RDK2::RMaps::RMapImage::getRealHeight () const [inline]
Definition at line 126 of file rmapimage.h.
References RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, and realWidth.
Referenced by centeredRobot().
double RDK2::RMaps::RMapImage::getMapDelta () const [inline]
Definition at line 127 of file rmapimage.h.
References RDK2::RGraphics::RImage::getWidth(), image, and realWidth.
Referenced by canvasReshape().
bool RDK2::RMaps::RMapImage::sameGeometry (const RMapImage * mapImage) const [inline]
Definition at line 130 of file rmapimage.h.
References EPSILON, RDK2::RGraphics::RImage::getHeight(), getRealWidth(), image, theta, x, and y.
std::string RDK2::RMaps::RMapImage::toString () const
Definition at line 50 of file rmapimage.cpp.
References buf2world(), RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Geometry::max(), RDK2::Geometry::min(), RDK2::Geometry::Point2< Numeric >::toString(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
void RDK2::RMaps::RMapImage::setPixelW (double wx, double wy, unsigned char color)
Modifica immagini
Definition at line 79 of file rmapimage.cpp.
References setPixelB(), and world2buf().
unsigned char RDK2::RMaps::RMapImage::getPixelW (double wx, double wy) const
Definition at line 86 of file rmapimage.cpp.
References C8Obstacle, getPixelB(), and world2buf().
bool RDK2::RMaps::RMapImage::safeSetPixelB (size_t x, size_t y, unsigned char color) [inline]
Definition at line 146 of file rmapimage.h.
References image, and RDK2::RGraphics::RImage::safeSetPixel().
unsigned char RDK2::RMaps::RMapImage::safeGetPixelB (size_t x, size_t y, unsigned char defaultColor) const [inline]
Definition at line 147 of file rmapimage.h.
References image, and RDK2::RGraphics::RImage::safeGetPixel().
void RDK2::RMaps::RMapImage::setPixelB (size_t x, size_t y, unsigned char color) [inline]
Definition at line 150 of file rmapimage.h.
References image, and RDK2::RGraphics::RImage::setPixel().
Referenced by line(), and setPixelW().
unsigned char RDK2::RMaps::RMapImage::getPixelB (size_t x, size_t y) const [inline]
Definition at line 151 of file rmapimage.h.
References RDK2::RGraphics::RImage::getPixel(), and image.
Referenced by calcClearance_b(), distMapRayTracing(), getPixelW(), obsDenRayTracing(), rayTracing(), rayTracing2(), and visibilityCheck().
void RDK2::RMaps::RMapImage::line (int x0, int y0, int x1, int y1, unsigned char color)
Definition at line 228 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getHeight(), RDK2::RGraphics::RImage::getWidth(), image, markLine(), RDK2::Geometry::max(), setPixelB(), RDK2::RMaps::RMapImage::point::x, x, RDK2::RMaps::RMapImage::point::y, and y.
unsigned int RDK2::RMaps::RMapImage::markLine (int x0, int y0, int x1, int y1, int width, int height, point * line, unsigned int maxLineLength) [static]
Definition at line 187 of file rmapimage.cpp.
References RDK2::RMaps::RMapImage::point::x, x, RDK2::RMaps::RMapImage::point::y, and y.
Referenced by line().
void RDK2::RMaps::RMapImage::rayTracing (const Point2d & start, const Point2d & end, const RC8Set * obstacleColors, bool & hitSomething, RImage::C8Color & colorHit)
Definition at line 482 of file rmapimage.cpp.
References C8Obstacle, RDK2::RGraphics::RC8Set::contains(), RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::Geometry::LineWalk::getPoint(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Geometry::LineWalk::next(), world2buf(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
Referenced by rayTracing().
void RDK2::RMaps::RMapImage::distMapRayTracing (const Point2d & start, const Point2d & end, bool & hitSomething, int min_dist)
Definition at line 429 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::Geometry::LineWalk::getPoint(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Geometry::LineWalk::next(), world2buf(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
double RDK2::RMaps::RMapImage::obsDenRayTracing (const Point2d & start, const Point2d & end)
Definition at line 454 of file rmapimage.cpp.
References RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::Geometry::LineWalk::getPoint(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Geometry::LineWalk::next(), world2buf(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
RMapImage::RayTracingResult RDK2::RMaps::RMapImage::rayTracing2 (double px, double py, double ptheta, double maxdist, double & result) const
Definition at line 313 of file rmapimage.cpp.
References buf2world(), C8Obstacle, C8Unknown, Free, RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::RGraphics::RImage::getWidth(), image, Margin, RDK2::RMaps::markLine2(), Obstacle, RDK_ERROR_PRINTF, Unknown, and world2buf().
RMapImage::RayTracingResult RDK2::RMaps::RMapImage::visibilityCheck (double p0x, double p0y, double p1x, double p1y, double * distancePtr = 0)
Definition at line 392 of file rmapimage.cpp.
References C8Obstacle, C8Unknown, Free, RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::RGraphics::RImage::getWidth(), image, Obstacle, Unknown, x, and y.
bool RDK2::RMaps::RMapImage::rayTracing (const Point2d & start, const Point2d & end, const RC8Set * obstacleColors, Point2d * collisionPoint = 0, RImage::C8Color * colorHit = 0)
Definition at line 509 of file rmapimage.cpp.
References buf2world(), RDK2::RGraphics::RC8Set::contains(), RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::Geometry::LineWalk::getPoint(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Geometry::LineWalk::next(), world2buf(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
bool RDK2::RMaps::RMapImage::rayTracing (const Point2d & start, double direction, double maxDist, const RC8Set * obstacleColors, double * distance = 0, RImage::C8Color * colorHit = 0)
Definition at line 534 of file rmapimage.cpp.
References RDK2::Geometry::Point2< Numeric >::distTo(), rayTracing(), RDK2::Geometry::Point2< Numeric >::x, and RDK2::Geometry::Point2< Numeric >::y.
double RDK2::RMaps::RMapImage::calcClearance_w (double wx, double wy)
Definition at line 133 of file rmapimage.cpp.
References calcClearance_b(), and world2buf().
double RDK2::RMaps::RMapImage::calcClearance_b (int bx, int by)
Definition at line 141 of file rmapimage.cpp.
References C8Obstacle, RDK2::RPrimitive::d, RDK2::RGraphics::RImage::getHeight(), getPixelB(), RDK2::RGraphics::RImage::getWidth(), image, RDK2::Statistics::r, realWidth, x, and y.
Referenced by calcClearance_w().
Field Documentation
double RDK2::RMaps::RMapImage::x
Coordinates of (0,0) pixel
Definition at line 48 of file rmapimage.h.
Referenced by applyDiff(), buf2world(), calcClearance_b(), canvasReshape(), centeredRobot(), clone(), line(), markLine(), RDK2::RMaps::markLine2(), maxWorldX(), minWorldX(), move(), read(), RMapImage(), sameGeometry(), visibilityCheck(), world2buf(), and write().
double RDK2::RMaps::RMapImage::y
Definition at line 48 of file rmapimage.h.
Referenced by applyDiff(), buf2world(), calcClearance_b(), canvasReshape(), centeredRobot(), clone(), line(), markLine(), RDK2::RMaps::markLine2(), maxWorldY(), minWorldY(), move(), read(), RMapImage(), sameGeometry(), visibilityCheck(), world2buf(), and write().
double RDK2::RMaps::RMapImage::theta
Direction for segment (0,0)-(width,0)
Definition at line 51 of file rmapimage.h.
Referenced by applyDiff(), clone(), read(), RMapImage(), sameGeometry(), and write().
double RDK2::RMaps::RMapImage::realWidth
Width of image in mm (height is scaled accordingly)
Definition at line 54 of file rmapimage.h.
Referenced by applyDiff(), buf2world(), calcClearance_b(), canvasReshape(), centeredRobot(), clone(), getMapDelta(), getRealHeight(), getRealWidth(), maxWorldX(), minWorldY(), read(), RMapImage(), world2buf(), and write().
RImage* RDK2::RMaps::RMapImage::image
The image data can be used to directly write on the map. You might want to retrieve the data using image->getPixels()
Definition at line 60 of file rmapimage.h.
Referenced by applyDiff(), buf2world(), calcClearance_b(), canvasReshape(), clone(), distMapRayTracing(), getMapDelta(), getPixelB(), getRealHeight(), line(), minWorldY(), move(), obsDenRayTracing(), rayTracing(), rayTracing2(), read(), RMapImage(), RDK2::RMaps::RMapImageDiffPoints::RMapImageDiffPoints(), RDK2::RMaps::RMapImageDiffRect::RMapImageDiffRect(), safeGetPixelB(), safeSetPixelB(), sameGeometry(), setPixelB(), splitInDiffs(), toString(), visibilityCheck(), world2buf(), write(), and ~RMapImage().
The documentation for this struct was generated from the following files:
rmapimage.h
rmapimage.cpp
rmapimage_diffs.cpp