OpenRDK: test_container.cpp File Reference
test_container.cpp File Reference
#include <vector>
#include <iostream>
#include <rdkcore/rprimitive/rint.h>
#include <rdkcore/rprimitive/rdouble.h>
#include <rdkcore/container/container.h>
Typedefs
typedef
RDK2::Containers::Vector< RInt > RIntVector
typedef
RDK2::Containers::Vector
< RDouble > RDoubleVector
typedef
RDK2::Containers::Vector
< RString > RStringVector
Functions
int main ()
Typedef Documentation
typedef RDK2::Containers::Vector<RDouble> RDoubleVector
Definition at line 34 of file test_container.cpp.
typedef RDK2::Containers::Vector<RInt> RIntVector
Definition at line 33 of file test_container.cpp.
typedef RDK2::Containers::Vector<RString> RStringVector
Definition at line 35 of file test_container.cpp.
Function Documentation
int main ()
Definition at line 37 of file test_container.cpp.
References RDK2::Containers::Vector< RType >::begin(), RDK2::Containers::Vector< RType >::copy(), RDK2::Containers::Vector< RType >::end(), and RDK2::Object::getStringRepresentation().