SET(OPENGL_FOUND 0)
IF (NOT "${CMAKE_CROSSCOMPILING}" STREQUAL TRUE)
	FIND_PACKAGE(OpenGL QUIET)
ELSE(NOT "${CMAKE_CROSSCOMPILING}" STREQUAL TRUE)
	MESSAGE(STATUS "OpenGL support is not available for cross-compiled OpenRDK")
ENDIF (NOT "${CMAKE_CROSSCOMPILING}" STREQUAL TRUE)

